obj-$(CONFIG_IMX_DCSS_CORE) += imx-dcss-core.o

imx-dcss-core-objs := dcss-common.o dcss-blkctl.o dcss-ctxld.o \
		      dcss-dpr.o dcss-dtg.o dcss-ss.o dcss-hdr10.o \
		      dcss-scaler.o dcss-dtrc.o dcss-dec400d.o dcss-wrscl.o \
		      dcss-rdsrc.o
