# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_INTEL_SOCFPGA) += socfpga_agilex_n6000.dtb \
				socfpga_agilex_socdk.dtb \
				socfpga_agilex_socdk_nand.dtb \
				socfpga_agilex5_socdk.dtb \
				socfpga_agilex_n6010.dtb \
				socfpga_agilex5_socdk.dtb \
				socfpga_agilex5_socdk_b0.dtb \
				socfpga_agilex5_socdk_debug.dtb \
				socfpga_agilex5_socdk_emmc.dtb \
				socfpga_agilex5_socdk_nand.dtb \
				socfpga_agilex5_socdk_nand_b0.dtb \
				socfpga_agilex5_socdk_swvp.dtb \
				socfpga_agilex5_socdk_swvp_b0.dtb \
				socfpga_agilex5_socdk_tsn_cfg2.dtb \
				socfpga_agilex7m_socdk.dtb \
				socfpga_agilex7f_socdk_pcie_root_port.dtb \
				socfpga_agilex7i_socdk_pcie_root_port.dtb \
				socfpga_agilex7m_socdk_pcie_root_port.dtb \
				socfpga_n5x_socdk.dtb
dtb-$(CONFIG_ARCH_KEEMBAY) += keembay-evm.dtb
