# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for TRX-RF IIO drivers
#
# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_AD9088) += ad9088/
obj-$(CONFIG_ADRV903X) += adrv903x/
obj-$(CONFIG_ADRV904X) += adrv904x/
