# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile iio/frequency
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_AD9523) += ad9523.o
obj-$(CONFIG_ADF4350) += adf4350.o
obj-$(CONFIG_ADF4371) += adf4371.o
obj-$(CONFIG_ADMV1013) += admv1013.o
obj-$(CONFIG_ADMV1014) += admv1014.o
obj-$(CONFIG_ADMV4420) += admv4420.o
obj-$(CONFIG_ADRF6780) += adrf6780.o

cf_axi_dds_drv-y := cf_axi_dds.o cf_axi_dds_buffer_stream.o
obj-$(CONFIG_CF_AXI_DDS) += cf_axi_dds_drv.o
