#
# Makefile iio/frequency
#

obj-$(CONFIG_AD9548) += ad9548.o
obj-$(CONFIG_AD9523) += ad9523.o
obj-$(CONFIG_ADF4350) += adf4350.o
obj-$(CONFIG_CF_AXI_DDS) += cf_axi_dds.o
obj-$(CONFIG_CF_AXI_DDS_AD9122) += ad9122.o
