#
# Makefile iio/frequency
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_AD9508) += ad9508.o
obj-$(CONFIG_AD9523) += ad9523.o
obj-$(CONFIG_AD9548) += ad9548.o
obj-$(CONFIG_ADF4350) += adf4350.o
obj-$(CONFIG_ADF5355) += adf5355.o
