FROM opensuse/leap:16.0

ENV version=v4
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh
ARG git_defaults_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/git-defaults.sh
ARG gh_actions_runner_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/gh-actions-runner.sh

RUN zypper update -y
RUN zypper install -y --no-recommends \
    tar unzip gzip curl jq libicu coreutils

RUN useradd -m runner
WORKDIR /home/runner

ADD ${gh_actions_runner_sh} .
RUN bash ./gh-actions-runner.sh ; rm ./gh-actions-runner.sh

COPY container/install-deps.sh .
RUN chmod +x install-deps.sh ; ./install-deps.sh ; rm ./install-deps.sh
COPY container/install-utils.sh .
RUN chmod +x install-utils.sh ; ./install-utils.sh ; rm ./install-utils.sh
COPY container/install-compilers.sh .
RUN chmod +x install-compilers.sh ; ./install-compilers.sh ; rm ./install-compilers.sh
COPY container/set-alternatives.sh .
RUN chmod +x set-alternatives.sh ; ./set-alternatives.sh ; rm ./set-alternatives.sh
COPY container/install-extra.sh .
RUN chmod +x install-extra.sh ; ./install-extra.sh ; rm ./install-extra.sh

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx ./entrypoint.sh

ADD ${git_defaults_sh} .
RUN bash ./git-defaults.sh ; rm ./git-defaults.sh

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/bin/bash"]

