FROM opensuse/leap:16.0

ENV runner_labels=repo-only,v4
ARG runner_version=2.328.0
ARG runner_version_sha=01066fad3a2893e63e6ca880ae3a1fad5bf9329d60e77ee15f2b97c148c3cd4e
ARG bashrc=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/bashrc
ARG entrypoint_sh=https://raw.githubusercontent.com/analogdevicesinc/doctools/refs/heads/ci/entrypoint.sh

RUN zypper install -y --no-recommends \
    tar gzip curl jq libicu coreutils

RUN useradd -m runner

USER runner
RUN mkdir -p /home/runner/actions-runner
WORKDIR /home/runner/actions-runner

RUN curl -o actions-runner.tar.gz -L https://github.com/actions/runner/releases/download/v${runner_version}/actions-runner-linux-x64-${runner_version}.tar.gz && \
    echo -n "${runner_version_sha} actions-runner.tar.gz" | sha256sum -c && \
    tar xzf actions-runner.tar.gz

USER root
COPY install-deps.sh .
RUN chmod +x install-deps.sh ; ./install-deps.sh
COPY install-utils.sh .
RUN chmod +x install-utils.sh ; ./install-utils.sh
COPY install-compilers.sh .
RUN chmod +x install-compilers.sh ; ./install-compilers.sh
COPY install-extra.sh .
RUN chmod +x install-extra.sh ; ./install-extra.sh
COPY set-alternatives.sh .
RUN chmod +x set-alternatives.sh ; ./set-alternatives.sh

RUN mkdir -p /usr/local/bin
WORKDIR /usr/local/bin
ADD ${entrypoint_sh} .
RUN chmod +rx entrypoint.sh

RUN git config --add --system user.name "CSE CI" ; \
    git config --add --system user.email "cse-ci-notifications@analog.com" ; \
    git config --add --system init.defaultBranch  "__runner_init_branch" ; \
    git config --add --system advice.mergeConflict false ; \
    git config --add --system advice.detachedHead false ; \
    git config --add --system fetch.prune true ; \
    git config --add --system fetch.pruneTags true ; \
    git config --add --system safe.directory '*'

USER runner
WORKDIR /home/runner
RUN curl -o .bashrc -L ${bashrc} ; \
    chmod +x .bashrc

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

