# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-frdm.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1046a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1046a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1088a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1088a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-simu.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2088a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2088a-rdb.dtb
 
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += fsl-imx8qm-lpddr4-arm2.dtb \
				 fsl-imx8qm-ddr4-arm2.dtb \
				 fsl-imx8qm-lpddr4-arm2_ca53.dtb \
				 fsl-imx8qm-lpddr4-arm2_ca72.dtb \
				 fsl-imx8qm-mek.dtb \
				 fsl-imx8qm-mek-mipi-ov5640.dtb \
				 fsl-imx8qm-mek-mipi-two-ov5640.dtb \
				 fsl-imx8qm-mek-8cam.dtb \
				 fsl-imx8qm-mek_ca53.dtb \
				 fsl-imx8qm-mek_ca72.dtb \
				 fsl-imx8qm-mek-hdmi.dtb \
				 fsl-imx8qm-mek-dsi-rm67191.dtb \
				 fsl-imx8qm-mek-enet2-tja1100.dtb \
				 fsl-imx8qm-mek-jdi-wuxga-lvds1-panel.dtb \
				 fsl-imx8qm-mek-dom0.dtb \
				 fsl-imx8qm-mek-domu.dtb \
				 fsl-imx8qm-lpddr4-arm2-dp.dtb \
				 fsl-imx8qm-lpddr4-arm2-8cam.dtb \
				 fsl-imx8qm-lpddr4-arm2-it6263-dual-channel.dtb \
				 fsl-imx8qm-lpddr4-arm2-jdi-wuxga-lvds1-panel.dtb \
				 fsl-imx8qm-lpddr4-arm2-lpspi.dtb \
				 fsl-imx8qm-lpddr4-arm2-spdif.dtb \
				 fsl-imx8qm-lpddr4-arm2-mqs.dtb \
				 fsl-imx8qm-lpddr4-arm2-usb3.dtb \
				 fsl-imx8qm-lpddr4-arm2-dsi-rm67191.dtb \
				 fsl-imx8qm-lpddr4-arm2-enet2-tja1100.dtb \
				 fsl-imx8qm-lpddr4-arm2-hsic.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QP) += fsl-imx8qp-lpddr4-arm2.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += fsl-imx8qxp-lpddr4-arm2.dtb \
				  fsl-imx8qxp-mek.dtb \
				  fsl-imx8qxp-mek-dom0.dtb \
				  fsl-imx8qxp-mek-csi.dtb \
				  fsl-imx8qxp-mek-mipi-ov5640.dtb \
				  fsl-imx8qxp-mek-ov5640.dtb \
				  fsl-imx8qxp-mek-enet2.dtb \
				  fsl-imx8qxp-mek-enet2-tja1100.dtb \
				  fsl-imx8qxp-mek-dsi-rm67191.dtb \
				  fsl-imx8qxp-mek-a0.dtb \
				  fsl-imx8qxp-lpddr4-arm2-enet2.dtb \
				  fsl-imx8qxp-lpddr4-arm2-enet2-tja1100.dtb \
				  fsl-imx8qxp-lpddr4-arm2-gpmi-nand.dtb \
				  fsl-imx8qxp-lpddr4-arm2-lpspi.dtb \
				  fsl-imx8qxp-lpddr4-arm2-spdif.dtb \
				  fsl-imx8qxp-lpddr4-arm2-mlb.dtb \
				  fsl-imx8qxp-lpddr4-arm2-mqs.dtb \
				  fsl-imx8qxp-lpddr4-arm2-wm8962.dtb \
				  fsl-imx8qxp-lpddr4-arm2-dsi-rm67191.dtb \
				  fsl-imx8qxp-lpddr4-arm2-a0.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += fsl-imx8mq-ddr3l-arm2.dtb \
				 fsl-imx8mq-ddr4-arm2.dtb \
				 fsl-imx8mq-ddr4-arm2-gpmi-nand.dtb \
				 fsl-imx8mq-evk.dtb \
				 fsl-imx8mq-evk-m4.dtb \
				 fsl-imx8mq-evk-pcie1-m2.dtb \
				 fsl-imx8mq-evk-lcdif-adv7535.dtb \
				 fsl-imx8mq-evk-mipi-csi2.dtb \
				 fsl-imx8mq-evk-pdm.dtb \
				 fsl-imx8mq-evk-dcss-adv7535.dtb \
				 fsl-imx8mq-evk-dcss-rm67191.dtb \
				 fsl-imx8mq-evk-dual-display.dtb \
				 fsl-imx8mq-evk-ak4497.dtb \
				 fsl-imx8mq-evk-audio-tdm.dtb \
				 fsl-imx8mq-evk-drm.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MM) += fsl-imx8mm-evk.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
