# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-frdm.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1012a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1043a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1046a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1046a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1088a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls1088a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-rdb.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2080a-simu.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2088a-qds.dtb
dtb-$(CONFIG_ARCH_LAYERSCAPE) += fsl-ls2088a-rdb.dtb
 
dtb-$(CONFIG_ARCH_FSL_IMX8QM) += fsl-imx8qm-lpddr4-arm2.dtb \
				 fsl-imx8qm-lpddr4-arm2_ca53.dtb \
				 fsl-imx8qm-lpddr4-arm2_ca72.dtb \
				 fsl-imx8qm-mek.dtb \
				 fsl-imx8qm-mek_ca53.dtb \
				 fsl-imx8qm-mek_ca72.dtb \
				 fsl-imx8qm-mek-it6263.dtb \
				 fsl-imx8qm-lpddr4-arm2-it6263.dtb \
				 fsl-imx8qm-lpddr4-arm2-it6263-dual-channel.dtb \
				 fsl-imx8qm-lpddr4-arm2-lpspi.dtb \
				 fsl-imx8qm-lpddr4-arm2-spdif.dtb \
				 fsl-imx8qm-lpddr4-arm2-mqs.dtb \
				 fsl-imx8qm-lpddr4-arm2-usb3.dtb \
				 fsl-imx8qm-lpddr4-arm2-dsi-adv7535.dtb \
				 fsl-imx8qm-lpddr4-arm2-dsi-rm67191.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8QXP) += fsl-imx8qxp-lpddr4-arm2.dtb \
				  fsl-imx8qxp-mek.dtb \
				  fsl-imx8qxp-mek-enet2.dtb \
				  fsl-imx8qxp-mek-lvds0-it6263.dtb \
				  fsl-imx8qxp-mek-lvds1-it6263.dtb \
				  fsl-imx8qxp-mek-lvds0-lvds1-it6263.dtb \
				  fsl-imx8qxp-mek-dsi-adv7535.dtb \
				  fsl-imx8qxp-lpddr4-arm2-enet2.dtb \
				  fsl-imx8qxp-lpddr4-arm2-gpmi-nand.dtb \
				  fsl-imx8qxp-lpddr4-arm2-it6263.dtb \
				  fsl-imx8qxp-lpddr4-arm2-lpspi.dtb \
				  fsl-imx8qxp-lpddr4-arm2-spdif.dtb \
				  fsl-imx8qxp-lpddr4-arm2-mlb.dtb \
				  fsl-imx8qxp-lpddr4-arm2-mqs.dtb \
				  fsl-imx8qxp-lpddr4-arm2-wm8962.dtb \
				  fsl-imx8qxp-lpddr4-arm2-dsi-adv7535.dtb
dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += fsl-imx8mq-evk.dtb \
				 fsl-imx8mq-evk-od.dtb \
				 fsl-imx8mq-evk-4k.dtb \
				 fsl-imx8mq-evk-drm.dtb \
				 fsl-imx8mq-evk-lcdif-dsi.dtb \
				 fsl-imx8mq-evk-m4.dtb \
				 fsl-imx8mq-evk-pcie1-m2.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
