/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef A2B_REGS_H
#define A2B_REGS_H

#define A2B_CHIP 0x00
#define A2B_NODEADR 0x01
#define A2B_NODEADR_MASK 0x0f
#define A2B_NODEADR_PERI BIT(5)
#define A2B_NODEADR_BRCST BIT(7)

#define A2B_VENDOR 0x02
#define A2B_PRODUCT 0x03
#define A2B_VERSION 0x04

#define A2B_CAPABILITY 0x05
#define A2B_CAPABILITY_I2C BIT(0)

#define A2B_SWCTL 0x09
#define A2B_SWCTL_ENSW BIT(0)
#define A2B_SWCTL_DIAGMODE BIT(3)
#define A2B_SWCTL_MODE(X) (((X)&3) << 4)
#define A2B_SWCTL_MODE_MASK (3 << 4)
#define A2B_SWCTL_DISNXT BIT(6)

#define A2B_BCDNSLOTS 0x0a
#define A2B_BCDNSLOTS_MASK 0x3f

#define A2B_LDNSLOTS 0x0b
#define A2B_LDNSLOTS_MASK 0x3f
#define A2B_LDNSLOTS_DNMASKEN BIT(7)

#define A2B_LUPSLOTS 0x0c
#define A2B_LUPSLOTS_MASK 0x3f

#define A2B_DNSLOTS 0x0d
#define A2B_DNSLOTS_MASK 0x3f

#define A2B_UPSLOTS 0x0e
#define A2B_UPSLOTS_MASK 0x3f

#define A2B_RESPCYCS 0x0f

#define A2B_SLOTFMT 0x10
#define A2B_SLOTFMT_DNSIZE(X) ((((X)-8) >> 2) & 7)
#define A2B_SLOTFMT_DNFMT BIT(3)
#define A2B_SLOTFMT_UPSIZE(X) (((((X)-8) >> 2) & 7) << 4)
#define A2B_SLOTFMT_UPFMT BIT(7)

#define A2B_DATCTL 0x11
#define A2B_DATCTL_DNS BIT(0)
#define A2B_DATCTL_UPS BIT(1)
#define A2B_DATCTL_ENDSNIFF BIT(5)
#define A2B_DATCTL_STANDBY BIT(7)

#define A2B_CONTROL 0x12
#define A2B_CONTROL_NEWSTRCT BIT(0)
#define A2B_CONTROL_ENDDSC BIT(1)
#define A2B_CONTROL_SOFTRST BIT(2)
#define A2B_CONTROL_SWBYP BIT(3)
#define A2B_CONTROL_XCVRBINV BIT(4)
#define A2B_CONTROL_MSTR BIT(7)

#define A2B_DISCVRY 0x13

#define A2B_SWSTAT 0x14
#define A2B_SWSTAT_FIN BIT(0)
#define A2B_SWSTAT_FAULT BIT(1)
#define A2B_SWSTAT_FAULTCODE(X) (((X)&0x7) >> 4)
#define A2B_SWSTAT_FAULT_NLOC BIT(7)

#define A2B_INTSTAT 0x15
#define A2B_INTSTAT_IRQ BIT(0)

#define A2B_INTSRC 0x16
#define A2B_INTSRC_INODE 0x0f
#define A2B_INTSRC_SLVINT BIT(6)
#define A2B_INTSRC_MSTINT BIT(7)

#define A2B_INTTYPE 0x17

#define A2B_INTTYPE_DSCDONE 24
#define A2B_INTTYPE_MSTR_RUNNING 255

#define A2B_INTPND0 0x18
#define A2B_INTPDN0_HDCNTERR BIT(0)
#define A2B_INTPDN0_DDERR BIT(1)
#define A2B_INTPDN0_CRCERR BIT(2)
#define A2B_INTPDN0_DPERR BIT(3)
#define A2B_INTPDN0_PWRERR BIT(4)
#define A2B_INTPDN0_BECOVF BIT(5)
#define A2B_INTPDN0_SRFERR BIT(6)
#define A2B_INTPDN0_SRFCRCERR BIT(7)

#define A2B_INTPND1 0x19
#define A2B_INTPND1_IOPND(X) BIT(X)

#define A2B_INTPND2 0x1a
#define A2B_INTPND2_DSCDONE BIT(0)
#define A2B_INTPND2_I2CERR BIT(1)
#define A2B_INTPND2_ICRCERR BIT(2)
#define A2B_INTPND2_SLVIRQ BIT(3)

#define A2B_INTMSK0 0x1b
#define A2B_INTMSK0_HCEIEN BIT(0)
#define A2B_INTMSK0_DDEIEN BIT(1)
#define A2B_INTMSK0_CRCEIEN BIT(2)
#define A2B_INTMSK0_DPEIEN BIT(3)
#define A2B_INTMSK0_PWREIEN BIT(4)
#define A2B_INTMSK0_BECIEN BIT(5)
#define A2B_INTMSK0_SRFEIEN BIT(6)
#define A2B_INTMSK0_SRFCRCEIEN BIT(7)

#define A2B_INTMSK1 0x1c
#define A2B_INTMSK1_IOIRQEN(X) BIT(X)

#define A2B_INTMSK2 0x1d
#define A2B_INTMSK2_DSCDIEN BIT(0)
#define A2B_INTMSK2_I2CEIEN BIT(1)
#define A2B_INTMSK2_ICRCEIEN BIT(2)
#define A2B_INTMSK2_SLVIRQEN BIT(3)

#define A2B_BECCTL 0x1e
#define A2B_BECCTL_ENHDCNT BIT(0)
#define A2B_BECCTL_ENDD BIT(1)
#define A2B_BECCTL_ENCRC BIT(2)
#define A2B_BECCTL_ENDP BIT(3)
#define A2B_BECCTL_ENICRC BIT(4)
#define A2B_BECCTL_THRESHLD(X) ((X) >> 5)

#define A2B_BECNT 0x1f

#define A2B_TESTMODE 0x20
#define A2B_TESTMODE_PRBSUP BIT(0)
#define A2B_TESTMODE_PRBSDN BIT(1)
#define A2B_TESTMODE_PRBSN2N BIT(2)
#define A2B_TESTMODE_RXDPTH(X) ((X) >> 4)

#define A2B_ERRCNT(x) (0x21 + (x))

#define A2B_NODE 0x29
#define A2B_NODE_MASK 0xf
#define A2B_NODE_DISCVD BIT(5)
#define A2B_NODE_NLAST BIT(6)
#define A2B_NODE_LAST BIT(7)

#define A2B_DISCSTAT 0x2b
#define A2B_DISCSTAT_DNODE(X) ((X)&0xf)
#define A2B_DISCSTAT_DSCACT BIT(7)

#define A2B_TXACTL 0x2e
#define A2B_TXBCTL 0x30
#define A2B_TXCTL_OVERRIDE BIT(7)
#define A2B_TXCTL_LEVEL_HIGH 0
#define A2B_TXCTL_LEVEL_MEDIUM 2
#define A2B_TXCTL_LEVEL_LOW 3

#define A2B_LINTTYPE 0x3e

#define A2B_I2CCFG 0x3f
#define A2B_I2CCFG_DATARATE BIT(0)
#define A2B_I2CCFG_EACK BIT(1)
#define A2B_I2CCFG_FRAMERATE BIT(2)

#define A2B_PLLCTL 0x40
#define A2B_PLLCTL_SSFREQ(X) ((X)&3)
#define A2B_PLLCTL_SSDEPTH BIT(3)
#define A2B_PLLCTL_SSMODE_AB (1 << 6)
#define A2B_PLLCTL_SSMODE_AB_I2S (2 << 6)

#define A2B_I2SGCTL 0x41
#define A2B_I2SGCTL_TDMMODE(X) ((X)&7)
#define A2B_I2SGCTL_RXONDTX1 BIT(3)
#define A2B_I2SGCTL_TDMSS BIT(4)
#define A2B_I2SGCTL_ALT BIT(5)
#define A2B_I2SGCTL_EARLY BIT(6)
#define A2B_I2SGCTL_INV BIT(7)

#define A2B_I2SCTL 0x42
#define A2B_I2SCTL_TX0EN BIT(0)
#define A2B_I2SCTL_TX1EN BIT(1)
#define A2B_I2SCTL_TX2PINTL BIT(2)
#define A2B_I2SCTL_TXBCLKINV BIT(3)
#define A2B_I2SCTL_RX0EN BIT(4)
#define A2B_I2SCTL_RX1EN BIT(5)
#define A2B_I2SCTL_RX2PINTL BIT(6)
#define A2B_I2SCTL_RXBCLKINV BIT(7)

#define A2B_I2SRATE 0x43
#define A2B_I2SRATE_I2SRATE(X) ((X)&3)
#define A2B_I2SRATE_BCLKRATE(X) (((X) << 3) & 3)
#define A2B_I2SRATE_REDUCE BIT(6)
#define A2B_I2SRATE_SHARE BIT(7)

#define A2B_I2STXOFFSET 0x44
#define A2B_I2STXOFFSET_VAR(X) ((X)&0x3f)
#define A2B_I2STXOFFSET_TSAFTER BIT(6)
#define A2B_I2STXOFFSET_TSBEFORE BIT(7)

#define A2B_2SRXOFFSET 0x45
#define A2B_I2SRXOFFSET_VAR(X) ((X)&0x3f)

#define A2B_SYNCOFFSET 0x46

#define A2B_PDMCTL 0x47
#define A2B_PDMCTL_PDM0EN BIT(0)
#define A2B_PDMCTL_PDM0SLOTS BIT(1)
#define A2B_PDMCTL_PDM1EN BIT(2)
#define A2B_PDMCTL_PDM1SLOTS BIT(3)
#define A2B_PDMCTL_HPFEN BIT(4)
#define A2B_PDMCTL_PDMRATE(X) (((X)&3) << 5)

#define A2B_ERRMGMT 0x48
#define A2B_ERRMGMT_ERRLSB BIT(0)
#define A2B_ERRMGMT_ERRSIG BIT(1)
#define A2B_ERRMGMT_ERRSLOT BIT(2)

#define A2B_GPIODAT 0x4a
#define A2B_GPIODAT_SET 0x4b
#define A2B_GPIODAT_CLR 0x4c
#define A2B_GPIOOEN 0x4d
#define A2B_GPIOIEN 0x4e
#define A2B_GPIODAT_IN 0x4f
#define A2B_PINTEN 0x50
#define A2B_PINTINV 0x51

#define A2B_PINCFG 0x52
#define A2B_PINCFG_DRVSTR_HIGH BIT(0)
#define A2B_PINCFG_IRQINV BIT(4)
#define A2B_PINCFG_IRQTS BIT(5)

#define A2B_I2STEST 0x53
#define A2B_I2STEST_PATTRN2TX BIT(0)
#define A2B_I2STEST_LOOPBK2TX BIT(1)
#define A2B_I2STEST_RX2LOOPBK BIT(2)
#define A2B_I2STEST_SELRX1 BIT(3)
#define A2B_I2STEST_BUSLOOPBK BIT(4)

#define A2B_RAISE 0x54

#define A2B_GENERR 0x55
#define A2B_GENERR_GENHCERR BIT(0)
#define A2B_GENERR_GENDDERR BIT(1)
#define A2B_GENERR_GENCRCERR BIT(2)
#define A2B_GENERR_GENDPERR BIT(3)
#define A2B_GENERR_GENICRCERR BIT(4)

#define A2B_I2SRRATE 0x56
#define A2B_I2SRRATE_RRDIV(X) ((X)&0x3f)
#define A2B_I2SRRATE_RBUS BIT(7)

#define A2B_I2SRRCTL 0x57
#define A2B_I2SRRCTL_ENVLSB BIT(0)
#define A2B_I2SRRCTL_ENXBIT BIT(1)
#define A2B_I2SRRCTL_ENSTRB BIT(4)
#define A2B_I2SRRCTL_STRBDIR BIT(5)

#define A2B_I2SRRSOFFS 0x58

#define A2B_CLK1CFG 0x59
#define A2B_CLK2CFG 0x5a
#define A2B_CLKCFG_DIV(X) ((X)&0xf)
#define A2B_CLKCFG_DIVMSK 0xf
#define A2B_CLKCFG_PDIV32 BIT(5)
#define A2B_CLKCFG_INV BIT(6)
#define A2B_CLKCFG_EN BIT(7)

#define A2B_BMMCFG 0x5b
#define A2B_BMMCFG_BMMEN BIT(0)
#define A2B_BMMCFG_BMMRXEN BIT(1)
#define A2B_BMMCFG_BMMNDSC BIT(2)

#define A2B_PDMCTL2 0x5d
#define A2B_PDMCTL2_DEST_A2B 0
#define A2B_PDMCTL2_DEST_DTX 1
#define A2B_PDMCTL2_DEST_A2B_DTX 2

#define A2B_UPMASK(X) (0x60 + ((X)&3))

#define A2B_UPOFFSET 0x64
#define A2B_UPOFFSET_VAL(X) ((X)&0x1f)

#define A2B_DNMASK(X) (0x65 + ((X) % 3))

#define A2B_DNOFFSET 0x69
#define A2B_DNOFFSET_VAL(X) ((X)&0x1f)

#define A2B_CHIPID(X) ((X) + 0x6a)

#define A2B_GPIODEN 0x80
#define A2B_GPIOD_MSK(X) ((X) + 0x81)

#define A2B_GPIODDAT 0x89
#define A2B_GPIODINV 0x8a

#define A2B_MBOXCTL(x) (0x90 + (x)*6)
#define A2B_MBOXSTAT(x) (0x91 + (x)*6)
#define A2B_MBOXDATA(x, y) (0x92 + (x)*6 + (y))

#define A2B_MBOXCTL_EN BIT(0)
#define A2B_MBOXCTL_TX BIT(1)
#define A2B_MBOXCTL_EIEN BIT(2)
#define A2B_MBOXCTL_FIEN BIT(3)
#define A2B_MBOXCTL_LEN(x) (((x)-1) << 4)

#define A2B_MBOXSTAT_EIRQ BIT(5)
#define A2B_MBOXSTAT_FIRQ BIT(4)
#define A2B_MBOXSTAT_EMPTY BIT(1)
#define A2B_MBOXSTAT_FULL BIT(0)

#define A2B_MAX_REG 0x9b

#endif
