obj-$(CONFIG_FB_MXC_DISP_FRAMEWORK)             += mxc_dispdrv.o
obj-$(CONFIG_FB_MXC_MIPI_DSI_NORTHWEST)         += mipi_dsi_northwest.o
obj-$(CONFIG_FB_MXC_EDID)                       += mxc_edid.o
obj-$(CONFIG_FB_MXC_ADV7535)			+= adv7535.o
