# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the SMSC network device drivers.
#

obj-$(CONFIG_SMC91X) += smc91x.o
obj-$(CONFIG_EPIC100) += epic100.o
obj-$(CONFIG_SMSC9420) += smsc9420.o
obj-$(CONFIG_SMSC911X) += smsc911x.o
