# SPDX-License-Identifier: GPL-2.0-only

stm32mp255c-dhcos-dhsbc-overlay-imx219-x10-dtbs := \
	stm32mp255c-dhcos-dhsbc.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtbo

dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp215f-dk.dtb \
	stm32mp235f-dk.dtb \
	stm32mp23xx-dhcos-bb.dtb \
	stm32mp25xx-dhcos-bb.dtb \
	stm32mp255c-dhcos-dhsbc.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtbo \
	stm32mp257d-engicam-microgea-rmm.dtb \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb
