# SPDX-License-Identifier: GPL-2.0-only

stm32mp255c-dhcos-dhsbc-overlay-imx219-x10-dtbs := \
	stm32mp255c-dhcos-dhsbc.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtbo

stm32mp257d-engicam-microgea-rmm-overlay-am-1280800w8tzqw-t00h-dtbs := \
	stm32mp257d-engicam-microgea-rmm.dtb \
	stm32mp257d-engicam-microgea-rmm-overlay-am-1280800w8tzqw-t00h.dtbo

stm32mp257d-engicam-microgea-rmm-overlay-rk050hr345-ct106a-dtbs := \
	stm32mp257d-engicam-microgea-rmm.dtb \
	stm32mp257d-engicam-microgea-rmm-overlay-rk050hr345-ct106a.dtbo

dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp215f-dk.dtb \
	stm32mp235f-dk.dtb \
	stm32mp23xx-dhcos-bb.dtb \
	stm32mp25xx-dhcos-bb.dtb \
	stm32mp255c-dhcos-dhsbc.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtb \
	stm32mp255c-dhcos-dhsbc-overlay-imx219-x10.dtbo \
	stm32mp257d-engicam-microgea-rmm.dtb \
	stm32mp257d-engicam-microgea-rmm-overlay-am-1280800w8tzqw-t00h.dtb \
	stm32mp257d-engicam-microgea-rmm-overlay-am-1280800w8tzqw-t00h.dtbo \
	stm32mp257d-engicam-microgea-rmm-overlay-rk050hr345-ct106a.dtb \
	stm32mp257d-engicam-microgea-rmm-overlay-rk050hr345-ct106a.dtbo \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb
