# SPDX-License-Identifier: GPL-2.0-only
snd-soc-adi-axi-i2s-objs := axi-i2s.o
snd-soc-adi-axi-spdif-objs := axi-spdif.o
snd-soc-sc5xx-pcm-objs := sc5xx-pcm.o
snd-soc-adi-sc5xx-i2s-objs := sc5xx-i2s.o

obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o
obj-$(CONFIG_SND_SC5XX_PCM) += snd-soc-sc5xx-pcm.o
obj-$(CONFIG_SND_SOC_ADI_SC5XX_I2S) += snd-soc-adi-sc5xx-i2s.o
