# SPDX-License-Identifier: GPL-2.0

imx95-dpu-drm-objs := dpu95-core.o dpu95-crtc.o dpu95-dither.o dpu95-drv.o \
		      dpu95-extdst.o  dpu95-fetchlayer.o dpu95-fetchyuv.o \
		      dpu95-hscaler.o dpu95-layerblend.o dpu95-constframe.o \
		      dpu95-domainblend.o dpu95-fetcheco.o dpu95-fetchunit.o \
		      dpu95-framegen.o dpu95-kms.o dpu95-plane.o dpu95-blit.o

obj-$(CONFIG_DRM_IMX95_DPU) += imx95-dpu-drm.o
