# SPDX-License-Identifier: GPL-2.0
max_serdes_all-objs := max_ser.o max_des.o max_serdes.o

obj-$(CONFIG_VIDEO_MAXIM_SERDES) += max_serdes_all.o
obj-$(CONFIG_VIDEO_MAXIM_AGGREGATOR) += max_aggregator.o
obj-$(CONFIG_VIDEO_MAX96717) += max96717.o
obj-$(CONFIG_VIDEO_MAX96724) += max96724.o
obj-$(CONFIG_VIDEO_MAX9296A) += max9296a.o
