# SPDX-License-Identifier: GPL-2.0
max_serdes-objs := max_serdes_core.o max_ser_common.o

obj-$(CONFIG_VIDEO_MAXIM_SERDES) += max_serdes.o
obj-$(CONFIG_VIDEO_MAXIM_SER) += max_ser.o
obj-$(CONFIG_VIDEO_MAXIM_DES) += max_des.o
obj-$(CONFIG_VIDEO_MAX96717) += max96717.o
obj-$(CONFIG_VIDEO_MAX96724) += max96724.o
obj-$(CONFIG_VIDEO_MAX9296A) += max9296a.o
