# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for smbdirect support
#

obj-$(CONFIG_SMBDIRECT) += smbdirect.o

smbdirect-y := \
	socket.o	\
	connection.o	\
	mr.o		\
	rw.o		\
	debug.o		\
	connect.o	\
	listen.o	\
	accept.o	\
	devices.o	\
	main.o
