obj-$(CONFIG_MX8_HDP) += \
	API_Audio.o \
	API_AVI.o \
	API_AFE.o \
	API_General.o \
	API_HDCP.o \
	API_HDMITX.o \
	API_HDMI_Audio.o \
	API_Infoframe.o \
	API_DPTX.o \
	util.o

obj-$(CONFIG_MX8_HDP_RX) += \
	API_HDMIRX.o \
	API_HDMI_RX_Audio.o
