# SPDX-License-Identifier: GPL-2.0
# Analog Devices Inc. pin control drivers
obj-$(CONFIG_PINCTRL_ADI)	 += pinctrl-adi.o
obj-$(CONFIG_PINCTRL_ADI_ADRV906X) += pinctrl-smc.o
obj-$(CONFIG_PINCTRL_ADI_ADRV906X) += pinctrl-adrv906x.o
