// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Analog Devices ADSP family SRU control driver.
 *
 * (C) Copyright 2022 - Analog Devices, Inc.
 *
 * Written and/or maintained by Timesys Corporation
 *
 * Author: Nathan Barrett-Morrison <nathan.morrison@timesys.com>
 * Contact: Greg Malysa <greg.malysa@timesys.com>
 *
 */

#include <linux/device.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/pinctrl/pinconf.h>
#include <linux/pinctrl/pinconf-generic.h>
#include <linux/pinctrl/pinctrl.h>
#include <linux/pinctrl/pinmux.h>
#include <linux/platform_device.h>
#include <linux/soc/adi/adsp-gpio-port.h>
#include <linux/slab.h>

#include <linux/soc/adi/adi_system_config.h>

#include "../core.h"
#include "../pinconf.h"
#include "../pinctrl-utils.h"
#include "sru-ctrl-adsp.h"

static const struct dai_destination dai0_destinations[] = {
	{ "SPT0_ACLK_I", 0x5, 0x00, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT0_BCLK_I", 0x5, 0x01, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT1_ACLK_I", 0x5, 0x02, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT1_BCLK_I", 0x5, 0x03, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT2_ACLK_I", 0x5, 0x04, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT2_BCLK_I", 0x5, 0x05, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SRC0_CLK_IP_I", 0x5, 0x00, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC0_CLK_OP_I", 0x5, 0x01, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC1_CLK_IP_I", 0x5, 0x02, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC1_CLK_OP_I", 0x5, 0x03, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC2_CLK_IP_I", 0x5, 0x04, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC2_CLK_OP_I", 0x5, 0x05, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC3_CLK_IP_I", 0x5, 0x00, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "SRC3_CLK_OP_I", 0x5, 0x01, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "SPDIF0_TX_CLK_I", 0x5, 0x02, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "PDM0_CLK0_I", 0x5, 0x03, REG_DAI_CLK2, REG_DAI_EXTD_CLK2, GROUP_A },	//59x
	{ "PDM0_BCLK_I", 0x5, 0x04, REG_DAI_CLK2, REG_DAI_EXTD_CLK2, GROUP_A },	//59x
	{ "SPDIF0_TX_HFCLK_I", 0x5, 0x05, REG_DAI_CLK3, REG_DAI_EXTD_CLK3,
	 GROUP_A },
	{ "PCG0_EXTCLKA_I", 0x5, 0x00, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "PCG0_EXTCLKB_I", 0x5, 0x01, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "SPDIF0_TX_EXT_SYNC_I", 0x5, 0x03, REG_DAI_CLK4,
	 REG_DAI_EXTD_CLK4, GROUP_A },
	{ "PCG0_SYNC_CLKA_I", 0x5, 0x04, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "PCG0_SYNC_CLKB_I", 0x5, 0x05, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "SPT3_ACLK_I", 0x5, 0x00, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "SPT3_BCLK_I", 0x5, 0x01, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "PCG0_SYNC_CLKE_I", 0x5, 0x02, REG_DAI_CLK5, REG_DAI_EXTD_CLK5, GROUP_A },	//59x
	{ "PCG0_SYNC_CLKF_I", 0x5, 0x03, REG_DAI_CLK5, REG_DAI_EXTD_CLK5, GROUP_A },	//59x
	{ "PCG0_EXTCLKE_I", 0x5, 0x04, REG_DAI_CLK5, REG_DAI_EXTD_CLK5, GROUP_A },	//59x
	{ "PCG0_EXTCLKF_I", 0x5, 0x05, REG_DAI_CLK5, REG_DAI_EXTD_CLK5, GROUP_A },	//59x
	{ "SPT0_AD0_I", 0x6, 0x00, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT0_AD1_I", 0x6, 0x01, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT0_BD0_I", 0x6, 0x02, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT0_BD1_I", 0x6, 0x03, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT1_AD0_I", 0x6, 0x04, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT1_AD1_I", 0x6, 0x00, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT1_BD0_I", 0x6, 0x01, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT1_BD1_I", 0x6, 0x02, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT2_AD0_I", 0x6, 0x03, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT2_AD1_I", 0x6, 0x04, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT2_BD0_I", 0x6, 0x00, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SPT2_BD1_I", 0x6, 0x01, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC0_DAT_IP_I", 0x6, 0x02, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC1_DAT_IP_I", 0x6, 0x03, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC2_DAT_IP_I", 0x6, 0x04, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC3_DAT_IP_I", 0x6, 0x00, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC0_TDM_OP_I", 0x6, 0x01, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC1_TDM_OP_I", 0x6, 0x02, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC2_TDM_OP_I", 0x6, 0x03, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC3_TDM_OP_I", 0x6, 0x04, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SPDIF0_TX_DAT_I", 0x6, 0x00, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "PDM0_DAT0_I", 0x6, 0x01, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "PDM0_DAT1_I", 0x6, 0x02, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "SPDIF0_RX_I", 0x6, 0x04, REG_DAI_DAT5, REG_DAI_EXTD_DAT5,
	 GROUP_B },
	{ "SPT3_AD0_I", 0x6, 0x00, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT3_AD1_I", 0x6, 0x01, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT3_BD0_I", 0x6, 0x02, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT3_BD1_I", 0x6, 0x03, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT0_AFS_I", 0x5, 0x00, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT0_BFS_I", 0x5, 0x01, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT1_AFS_I", 0x5, 0x02, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT1_BFS_I", 0x5, 0x03, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT2_AFS_I", 0x5, 0x04, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT2_BFS_I", 0x5, 0x05, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SRC0_FS_IP_I", 0x5, 0x00, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC0_FS_OP_I", 0x5, 0x01, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC1_FS_IP_I", 0x5, 0x02, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC1_FS_OP_I", 0x5, 0x03, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC2_FS_IP_I", 0x5, 0x04, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC2_FS_OP_I", 0x5, 0x05, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC3_FS_IP_I", 0x5, 0x00, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SRC3_FS_OP_I", 0x5, 0x01, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SPDIF0_TX_FS_I", 0x5, 0x02, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SPT3_AFS_I", 0x5, 0x00, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "SPT3_BFS_I", 0x5, 0x01, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "TM0_ACI14_I", 0x5, 0x02, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "PDM0_LRCLK_I", 0x5, 0x03, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "DAI0_PB01_I", 0x7, 0x00, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI0_PB02_I", 0x7, 0x01, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI0_PB03_I", 0x7, 0x02, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI0_PB04_I", 0x7, 0x03, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI0_PB05_I", 0x7, 0x00, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI0_PB06_I", 0x7, 0x01, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI0_PB07_I", 0x7, 0x02, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI0_PB08_I", 0x7, 0x03, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI0_PB09_I", 0x7, 0x00, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI0_PB10_I", 0x7, 0x01, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI0_PB11_I", 0x7, 0x02, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI0_PB12_I", 0x7, 0x03, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI0_PB13_I", 0x7, 0x00, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI0_PB14_I", 0x7, 0x01, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI0_PB15_I", 0x7, 0x02, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI0_PB16_I", 0x7, 0x03, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI0_PB17_I", 0x7, 0x00, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI0_PB18_I", 0x7, 0x01, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI0_PB19_I", 0x7, 0x02, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI0_PB20_I", 0x7, 0x03, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "INV_DAI0_PB19_I", 0x1, 0x28, REG_DAI_PIN4, REG_DAI_EXTD_PIN4, GROUP_D },	//58x
	{ "INV_DAI0_PB20_I", 0x1, 0x29, REG_DAI_PIN4, REG_DAI_EXTD_PIN4, GROUP_D },	//58x
	{ "DAI0_MISCA0_I", 0x5, 0x00, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_INT_6_I", 0x5, 0x00, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_MISCA1_I", 0x5, 0x01, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_INT_7_I", 0x5, 0x01, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_MISCA2_I", 0x5, 0x02, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_INT_8_I", 0x5, 0x02, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_MISCA3_I", 0x5, 0x03, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_INT_9_I", 0x5, 0x03, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_MISCA4_I", 0x5, 0x04, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_MISCA5_I", 0x5, 0x05, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI0_INV_MISCA4_I", 0x1, 0x30, REG_DAI_MISC0,
	 REG_DAI_EXTD_MISC0, GROUP_E },
	{ "DAI0_INV_MISCA5_I", 0x1, 0x31, REG_DAI_MISC0,
	 REG_DAI_EXTD_MISC0, GROUP_E },
	{ "DAI0_INT_0_I", 0x5, 0x00, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI0_INT_1_I", 0x5, 0x01, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI0_INT_2_I", 0x5, 0x02, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI0_INT_3_I", 0x5, 0x03, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI0_INT_4_I", 0x5, 0x04, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI0_INT_5_I", 0x5, 0x05, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "PCG_HWA_TRIG_I", 0x5, 0x00, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWB_TRIG_I", 0x5, 0x01, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWE_TRIG_I", 0x5, 0x02, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWF_TRIG_I", 0x5, 0x03, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "DAI0_PBEN01_I", 0x6, 0x00, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI0_PBEN02_I", 0x6, 0x01, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI0_PBEN03_I", 0x6, 0x02, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI0_PBEN04_I", 0x6, 0x03, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI0_PBEN05_I", 0x6, 0x04, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI0_PBEN06_I", 0x6, 0x00, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI0_PBEN07_I", 0x6, 0x01, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI0_PBEN08_I", 0x6, 0x02, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI0_PBEN09_I", 0x6, 0x03, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI0_PBEN10_I", 0x6, 0x04, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI0_PBEN11_I", 0x6, 0x00, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI0_PBEN12_I", 0x6, 0x01, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI0_PBEN13_I", 0x6, 0x02, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI0_PBEN14_I", 0x6, 0x03, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI0_PBEN15_I", 0x6, 0x04, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI0_PBEN16_I", 0x6, 0x00, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI0_PBEN17_I", 0x6, 0x01, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI0_PBEN18_I", 0x6, 0x02, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI0_PBEN19_I", 0x6, 0x03, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI0_PBEN20_I", 0x6, 0x04, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F }
};

static const struct dai_destination dai1_destinations[] = {
	{ "SPT4_ACLK_I", 0x5, 0x00, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT4_BCLK_I", 0x5, 0x01, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT5_ACLK_I", 0x5, 0x02, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT5_BCLK_I", 0x5, 0x03, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT6_ACLK_I", 0x5, 0x04, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SPT6_BCLK_I", 0x5, 0x05, REG_DAI_CLK0, REG_DAI_EXTD_CLK0,
	 GROUP_A },
	{ "SRC4_CLK_IP_I", 0x5, 0x00, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC4_CLK_OP_I", 0x5, 0x01, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC5_CLK_IP_I", 0x5, 0x02, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC5_CLK_OP_I", 0x5, 0x03, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC6_CLK_IP_I", 0x5, 0x04, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC6_CLK_OP_I", 0x5, 0x05, REG_DAI_CLK1, REG_DAI_EXTD_CLK1,
	 GROUP_A },
	{ "SRC7_CLK_IP_I", 0x5, 0x00, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "SRC7_CLK_OP_I", 0x5, 0x01, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "SPDIF1_TX_CLK_I", 0x5, 0x02, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "PDM1_CLK0_I", 0x5, 0x03, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "PDM1_BCLK_I", 0x5, 0x04, REG_DAI_CLK2, REG_DAI_EXTD_CLK2,
	 GROUP_A },
	{ "SPDIF1_TX_HFCLK_I", 0x5, 0x05, REG_DAI_CLK3, REG_DAI_EXTD_CLK3,
	 GROUP_A },
	{ "PCG0_EXTCLKC_I", 0x5, 0x00, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "PCG0_EXTCLKD_I", 0x5, 0x01, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "SPDIF1_TX_EXT_SYNC_I", 0x5, 0x03, REG_DAI_CLK4,
	 REG_DAI_EXTD_CLK4, GROUP_A },
	{ "PCG0_SYNC_CLKC_I", 0x5, 0x04, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "PCG0_SYNC_CLKD_I", 0x5, 0x05, REG_DAI_CLK4, REG_DAI_EXTD_CLK4,
	 GROUP_A },
	{ "SPT7_ACLK_I", 0x5, 0x00, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "SPT7_BCLK_I", 0x5, 0x01, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "PCG0_SYNC_CLKG_I", 0x5, 0x02, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "PCG0_SYNC_CLKH_I", 0x5, 0x03, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "PCG0_EXTCLKG_I", 0x5, 0x04, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "PCG0_EXTCLKH_I", 0x5, 0x05, REG_DAI_CLK5, REG_DAI_EXTD_CLK5,
	 GROUP_A },
	{ "SPT4_AD0_I", 0x6, 0x00, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT4_AD1_I", 0x6, 0x01, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT4_BD0_I", 0x6, 0x02, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT4_BD1_I", 0x6, 0x03, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT5_AD0_I", 0x6, 0x04, REG_DAI_DAT0, REG_DAI_EXTD_DAT0,
	 GROUP_B },
	{ "SPT5_AD1_I", 0x6, 0x00, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT5_BD0_I", 0x6, 0x01, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT5_BD1_I", 0x6, 0x02, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT6_AD0_I", 0x6, 0x03, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT6_AD1_I", 0x6, 0x04, REG_DAI_DAT1, REG_DAI_EXTD_DAT1,
	 GROUP_B },
	{ "SPT6_BD0_I", 0x6, 0x00, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SPT6_BD1_I", 0x6, 0x01, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC4_DAT_IP_I", 0x6, 0x02, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC5_DAT_IP_I", 0x6, 0x03, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC6_DAT_IP_I", 0x6, 0x04, REG_DAI_DAT2, REG_DAI_EXTD_DAT2,
	 GROUP_B },
	{ "SRC7_DAT_IP_I", 0x6, 0x00, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC4_TDM_OP_I", 0x6, 0x01, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC5_TDM_OP_I", 0x6, 0x02, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC6_TDM_OP_I", 0x6, 0x03, REG_DAI_DAT3, REG_DAI_EXTD_DAT3,
	 GROUP_B },
	{ "SRC7_TDM_OP_I", 0x6, 0x04, REG_DAI_DAT3, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "SPDIF1_TX_DAT_I", 0x6, 0x00, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "PDM1_DAT0_I", 0x6, 0x01, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "PDM1_DAT1_I", 0x6, 0x02, REG_DAI_DAT4, REG_DAI_EXTD_DAT4,
	 GROUP_B },
	{ "SPDIF1_RX_I", 0x6, 0x04, REG_DAI_DAT5, REG_DAI_EXTD_DAT5,
	 GROUP_B },
	{ "SPT7_AD0_I", 0x6, 0x00, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT7_AD1_I", 0x6, 0x01, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT7_BD0_I", 0x6, 0x02, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT7_BD1_I", 0x6, 0x03, REG_DAI_DAT6, REG_DAI_EXTD_DAT6,
	 GROUP_B },
	{ "SPT4_AFS_I", 0x5, 0x00, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT4_BFS_I", 0x5, 0x01, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT5_AFS_I", 0x5, 0x02, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT5_BFS_I", 0x5, 0x03, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT6_AFS_I", 0x5, 0x04, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SPT6_BFS_I", 0x5, 0x05, REG_DAI_FS0, REG_DAI_EXTD_FS0,
	 GROUP_C },
	{ "SRC4_FS_IP_I", 0x5, 0x00, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC4_FS_OP_I", 0x5, 0x01, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC5_FS_IP_I", 0x5, 0x02, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC5_FS_OP_I", 0x5, 0x03, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC6_FS_IP_I", 0x5, 0x04, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC6_FS_OP_I", 0x5, 0x05, REG_DAI_FS1, REG_DAI_EXTD_FS1,
	 GROUP_C },
	{ "SRC7_FS_IP_I", 0x5, 0x00, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SRC7_FS_OP_I", 0x5, 0x01, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SPDIF1_TX_FS_I", 0x5, 0x02, REG_DAI_FS2, REG_DAI_EXTD_FS2,
	 GROUP_C },
	{ "SPT7_AFS_I", 0x5, 0x00, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "SPT7_BFS_I", 0x5, 0x01, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "TM0_ACI15_I", 0x5, 0x02, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "PDM1_LRCLK_I", 0x5, 0x03, REG_DAI_FS4, REG_DAI_EXTD_FS4,
	 GROUP_C },
	{ "DAI1_PB01_I", 0x7, 0x00, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI1_PB02_I", 0x7, 0x01, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI1_PB03_I", 0x7, 0x02, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI1_PB04_I", 0x7, 0x03, REG_DAI_PIN0, REG_DAI_EXTD_PIN0,
	 GROUP_D },
	{ "DAI1_PB05_I", 0x7, 0x00, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI1_PB06_I", 0x7, 0x01, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI1_PB07_I", 0x7, 0x02, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI1_PB08_I", 0x7, 0x03, REG_DAI_PIN1, REG_DAI_EXTD_PIN1,
	 GROUP_D },
	{ "DAI1_PB09_I", 0x7, 0x00, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI1_PB10_I", 0x7, 0x01, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI1_PB11_I", 0x7, 0x02, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI1_PB12_I", 0x7, 0x03, REG_DAI_PIN2, REG_DAI_EXTD_PIN2,
	 GROUP_D },
	{ "DAI1_PB13_I", 0x7, 0x00, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI1_PB14_I", 0x7, 0x01, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI1_PB15_I", 0x7, 0x02, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI1_PB16_I", 0x7, 0x03, REG_DAI_PIN3, REG_DAI_EXTD_PIN3,
	 GROUP_D },
	{ "DAI1_PB17_I", 0x7, 0x00, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI1_PB18_I", 0x7, 0x01, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI1_PB19_I", 0x7, 0x02, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI1_PB20_I", 0x7, 0x03, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "INV_DAI1_PB19_I", 0x1, 0x28, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "INV_DAI1_PB20_I", 0x1, 0x29, REG_DAI_PIN4, REG_DAI_EXTD_PIN4,
	 GROUP_D },
	{ "DAI1_MISCA0_I", 0x5, 0x00, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_INT_6_I", 0x5, 0x00, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_MISCA1_I", 0x5, 0x01, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_INT_7_I", 0x5, 0x01, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_MISCA2_I", 0x5, 0x02, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_INT_8_I", 0x5, 0x02, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_MISCA3_I", 0x5, 0x03, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_INT_9_I", 0x5, 0x03, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_MISCA4_I", 0x5, 0x04, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_MISCA5_I", 0x5, 0x05, REG_DAI_MISC0, REG_DAI_EXTD_MISC0,
	 GROUP_E },
	{ "DAI1_INV_MISCA4_I", 0x1, 0x30, REG_DAI_MISC0,
	 REG_DAI_EXTD_MISC0, GROUP_E },
	{ "DAI1_INV_MISCA5_I", 0x1, 0x31, REG_DAI_MISC0,
	 REG_DAI_EXTD_MISC0, GROUP_E },
	{ "DAI1_INT_0_I", 0x5, 0x00, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI1_INT_1_I", 0x5, 0x01, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI1_INT_2_I", 0x5, 0x02, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI1_INT_3_I", 0x5, 0x03, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI1_INT_4_I", 0x5, 0x04, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "DAI1_INT_5_I", 0x5, 0x05, REG_DAI_MISC1, REG_DAI_EXTD_MISC1,
	 GROUP_E },
	{ "PCG_HWC_TRIG_I", 0x5, 0x00, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWD_TRIG_I", 0x5, 0x01, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWG_TRIG_I", 0x5, 0x02, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "PCG_HWH_TRIG_I", 0x5, 0x03, REG_DAI_MISC2, REG_DAI_EXTD_MISC2,
	 GROUP_E },
	{ "DAI1_PBEN01_I", 0x6, 0x00, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI1_PBEN02_I", 0x6, 0x01, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI1_PBEN03_I", 0x6, 0x02, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI1_PBEN04_I", 0x6, 0x03, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI1_PBEN05_I", 0x6, 0x04, REG_DAI_PBEN0, REG_DAI_EXTD_PBEN0,
	 GROUP_F },
	{ "DAI1_PBEN06_I", 0x6, 0x00, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI1_PBEN07_I", 0x6, 0x01, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI1_PBEN08_I", 0x6, 0x02, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI1_PBEN09_I", 0x6, 0x03, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI1_PBEN10_I", 0x6, 0x04, REG_DAI_PBEN1, REG_DAI_EXTD_PBEN1,
	 GROUP_F },
	{ "DAI1_PBEN11_I", 0x6, 0x00, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI1_PBEN12_I", 0x6, 0x01, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI1_PBEN13_I", 0x6, 0x02, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI1_PBEN14_I", 0x6, 0x03, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI1_PBEN15_I", 0x6, 0x04, REG_DAI_PBEN2, REG_DAI_EXTD_PBEN2,
	 GROUP_F },
	{ "DAI1_PBEN16_I", 0x6, 0x00, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI1_PBEN17_I", 0x6, 0x01, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI1_PBEN18_I", 0x6, 0x02, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI1_PBEN19_I", 0x6, 0x03, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
	{ "DAI1_PBEN20_I", 0x6, 0x04, REG_DAI_PBEN3, REG_DAI_EXTD_PBEN3,
	 GROUP_F },
};

static const struct dai_source dai0_sources[] = {
	{ "DAI0_PB01_O_ABCDE", 0x00,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB02_O_ABCDE", 0x01,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB03_O_ABCDE", 0x02,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB04_O_ABCDE", 0x03,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB05_O_ABCDE", 0x04,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB06_O_ABCDE", 0x05,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB07_O_ABCDE", 0x06,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB08_O_ABCDE", 0x07,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB09_O_ABCDE", 0x08,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB10_O_ABCDE", 0x09,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB11_O_ABCDE", 0x0a,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB12_O_ABCDE", 0x0b,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB13_O_ABCDE", 0x0c,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB14_O_ABCDE", 0x0d,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB15_O_ABCDE", 0x0e,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB16_O_ABCDE", 0x0f,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB17_O_ABCDE", 0x10,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB18_O_ABCDE", 0x11,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB19_O_ABCDE", 0x12,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_PB20_O_ABCDE", 0x13,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI0_LOW_ACE", 0x1e, GROUP_A | GROUP_C | GROUP_E },
	{ "DAI0_HIGH_ACE", 0x1f, GROUP_A | GROUP_C | GROUP_E },
	{ "SPT0_AD0_O_BD", 0x14, GROUP_B | GROUP_D },
	{ "SPT0_AD1_O_BD", 0x15, GROUP_B | GROUP_D },
	{ "SPT0_BD0_O_BD", 0x16, GROUP_B | GROUP_D },
	{ "SPT0_BD1_O_BD", 0x17, GROUP_B | GROUP_D },
	{ "SPT1_AD0_O_BD", 0x18, GROUP_B | GROUP_D },
	{ "SPT1_AD1_O_BD", 0x19, GROUP_B | GROUP_D },
	{ "SPT1_BD0_O_BD", 0x1a, GROUP_B | GROUP_D },
	{ "SPT1_BD1_O_BD", 0x1b, GROUP_B | GROUP_D },
	{ "SPT2_AD0_O_BD", 0x1c, GROUP_B | GROUP_D },
	{ "SPT2_AD1_O_BD", 0x1d, GROUP_B | GROUP_D },
	{ "SPT2_BD0_O_BD", 0x1e, GROUP_B | GROUP_D },
	{ "SPT2_BD1_O_BD", 0x1f, GROUP_B | GROUP_D },
	{ "DAI0_CRS_PB03_O_A", 0x00, GROUP_A },
	{ "SPT0_ACLK_O_A", 0x14, GROUP_A },
	{ "SPT0_BCLK_O_A", 0x15, GROUP_A },
	{ "SPT1_ACLK_O_A", 0x16, GROUP_A },
	{ "SPT1_BCLK_O_A", 0x17, GROUP_A },
	{ "SPT2_ACLK_O_A", 0x18, GROUP_A },
	{ "SPT2_BCLK_O_A", 0x19, GROUP_A },
	{ "SPDIF0_RX_CLK_O_A", 0x1a, GROUP_A },
	{ "SPDIF0_RX_TDMCLK_O_A", 0x1b, GROUP_A },
	{ "PCG0_CLKA_O_A", 0x1c, GROUP_A },
	{ "PCG0_CLKB_O_A", 0x1d, GROUP_A },
	{ "SRC0_DAT_OP_O_B", 0x20, GROUP_B },
	{ "SRC1_DAT_OP_O_B", 0x21, GROUP_B },
	{ "SRC2_DAT_OP_O_B", 0x22, GROUP_B },
	{ "SRC3_DAT_OP_O_B", 0x23, GROUP_B },
	{ "SRC0_TDM_IP_O_B", 0x24, GROUP_B },
	{ "SRC1_TDM_IP_O_B", 0x25, GROUP_B },
	{ "SRC2_TDM_IP_O_B", 0x26, GROUP_B },
	{ "SRC3_TDM_IP_O_B", 0x27, GROUP_B },
	{ "SPDIF0_RX_DAT_O_B", 0x28, GROUP_B },
	{ "SPT3_AD0_O_B", 0x2c, GROUP_B },
	{ "SPT3_AD1_O_B", 0x2d, GROUP_B },
	{ "SPT3_BD0_O_B", 0x2e, GROUP_B },
	{ "SPT3_BD1_O_B", 0x2f, GROUP_B },
	{ "SPDIF0_TX_O_B", 0x30, GROUP_B },
	{ "SRC7_CRS_DAT_OP_O_B", 0x31, GROUP_B },
	{ "SRC7_CRS_TDM_IP_O_B", 0x32, GROUP_B },
	{ "PDM0_SDATA_O_B", 0x33, GROUP_B },
	{ "DAI0_LOW_B", 0x3e, GROUP_B },
	{ "DAI0_HIGH_B", 0x3f, GROUP_B },
	{ "DAI0_CRS_PB04_O_C", 0x00, GROUP_C },
	{ "SPT0_AFS_O_C", 0x14, GROUP_C },
	{ "SPT0_BFS_O_C", 0x15, GROUP_C },
	{ "SPT1_AFS_O_C", 0x16, GROUP_C },
	{ "SPT1_BFS_O_C", 0x17, GROUP_C },
	{ "SPT2_AFS_O_C", 0x18, GROUP_C },
	{ "SPT2_BFS_O_C", 0x19, GROUP_C },
	{ "SPDIF0_FS_O_C", 0x1a, GROUP_C },
	{ "PCG0_FSA_O_C", 0x1c, GROUP_C },
	{ "PCG0_FSB_O_C", 0x1d, GROUP_C },
	{ "SPT0_ACLK_O_D", 0x20, GROUP_D },
	{ "SPT0_BCLK_O_D", 0x21, GROUP_D },
	{ "SPT1_ACLK_O_D", 0x22, GROUP_D },
	{ "SPT1_BCLK_O_D", 0x23, GROUP_D },
	{ "SPT2_ACLK_O_D", 0x24, GROUP_D },
	{ "SPT2_BCLK_O_D", 0x25, GROUP_D },
	{ "SPT0_AFS_O_D", 0x26, GROUP_D },
	{ "SPT0_BFS_O_D", 0x27, GROUP_D },
	{ "SPT1_AFS_O_D", 0x28, GROUP_D },
	{ "SPT1_BFS_O_D", 0x29, GROUP_D },
	{ "SPT2_AFS_O_D", 0x2a, GROUP_D },
	{ "SPT2_BFS_O_D", 0x2b, GROUP_D },
	{ "SPT3_AD0_O_D", 0x2c, GROUP_D },
	{ "SPT3_AD1_O_D", 0x2d, GROUP_D },
	{ "SPT3_BD0_O_D", 0x2e, GROUP_D },
	{ "SPT3_BD1_O_D", 0x2f, GROUP_D },
	{ "MLB0_CLKOUT_O_D", 0x30, GROUP_D },
	{ "SPDIF0_TX_BLKSTART_O_D", 0x31, GROUP_D },
	{ "SPT3_ACLK_O_D", 0x34, GROUP_D },
	{ "SPT3_BCLK_O_D", 0x35, GROUP_D },
	{ "SPT3_AFS_O_D", 0x36, GROUP_D },
	{ "SPT3_BFS_O_D", 0x37, GROUP_D },
	{ "PCG0_CLKA_O_D", 0x38, GROUP_D },
	{ "PCG0_CLKB_O_D", 0x39, GROUP_D },
	{ "PCG0_FSA_O_D", 0x3a, GROUP_D },
	{ "PCG0_FSB_O_D", 0x3b, GROUP_D },
	{ "SRC0_DAT_OP_O_D", 0x3d, GROUP_D },
	{ "SRC1_DAT_OP_O_D", 0x3e, GROUP_D },
	{ "SRC2_DAT_OP_O_D", 0x3f, GROUP_D },
	{ "SRC3_DAT_OP_O_D", 0x40, GROUP_D },
	{ "SPDIF0_RX_DAT_O_D", 0x41, GROUP_D },
	{ "SPDIF0_RX_FS_O_D", 0x42, GROUP_D },
	{ "SPDIF0_RX_CLK_O_D", 0x43, GROUP_D },
	{ "SPDIF0_RX_TDMCLK_O_D", 0x44, GROUP_D },
	{ "SPDIF0_TX_O_D", 0x45, GROUP_D },
	{ "SPT0_ATDV_O_D", 0x46, GROUP_D },
	{ "SPT0_BTDV_O_D", 0x47, GROUP_D },
	{ "SPT1_ATDV_O_D", 0x48, GROUP_D },
	{ "SPT1_BTDV_O_D", 0x49, GROUP_D },
	{ "SPT2_ATDV_O_D", 0x4a, GROUP_D },
	{ "SPT2_BTDV_O_D", 0x4b, GROUP_D },
	{ "SPT3_ATDV_O_D", 0x4c, GROUP_D },
	{ "SPT3_BTDV_O_D", 0x4d, GROUP_D },
	{ "SPDIF0_RX_LRCLK_REF_O_D", 0x4e, GROUP_D },
	{ "SPDIF0_RX_LRCLK_FB_O_D", 0x4f, GROUP_D },
	{ "PCG0_CRS_CLKC_O_D", 0x50, GROUP_D },
	{ "PCG0_CRS_CLKD_O_D", 0x51, GROUP_D },
	{ "PCG0_CRS_FSC_O_D", 0x52, GROUP_D },
	{ "PCG0_CRS_FSD_O_D", 0x53, GROUP_D },
	{ "DAI0_CRS_PB03_O_D", 0x54, GROUP_D },
	{ "DAI0_CRS_PB04_O_D", 0x55, GROUP_D },
	{ "PCG_CLKE_O_D", 0x56, GROUP_D },
	{ "PCG_CLKF_O_D", 0x57, GROUP_D },
	{ "PCG_FSE_O_D", 0x58, GROUP_D },
	{ "PCG_FSF_O_D", 0x59, GROUP_D },
	{ "PCG_CLKA_INV_O_D", 0x5a, GROUP_D },
	{ "PCG_CLKB_INV_O_D", 0x5b, GROUP_D },
	{ "PCG_CLKE_INV_O_D", 0x5c, GROUP_D },
	{ "PCG_CLKF_INV_O_D", 0x5d, GROUP_D },
	{ "PCG_FSA_INV_O_D", 0x5e, GROUP_D },
	{ "PCG_FSB_INV_O_D", 0x5f, GROUP_D },
	{ "PCG_FSE_INV_O_D", 0x60, GROUP_D },
	{ "PCG_FSF_INV_O_D", 0x61, GROUP_D },
	{ "PDM0_CLK0_O_D", 0x62, GROUP_D },
	{ "PDM0_SDATA_O_D", 0x63, GROUP_D },
	{ "DAI0_LOW_D", 0x7e, GROUP_D },
	{ "DAI0_HIGH_D", 0x7f, GROUP_D },
	{ "SPT0A_FS_O_E", 0x14, GROUP_E },
	{ "SPT0B_FS_O_E", 0x15, GROUP_E },
	{ "SPT1A_FS_O_E", 0x16, GROUP_E },
	{ "SPT1B_FS_O_E", 0x17, GROUP_E },
	{ "SPT2A_FS_O_E", 0x18, GROUP_E },
	{ "SPT2B_FS_O_E", 0x19, GROUP_E },
	{ "SPDIF0_TX_BLKSTART_O_E", 0x1a, GROUP_E },
	{ "PCG0_FSA_O_E", 0x1b, GROUP_E },
	{ "PCG0_CLKB_O_E", 0x1c, GROUP_E },
	{ "PCG0_FSB_O_E", 0x1d, GROUP_E },
	{ "DAI0_LOW_F", 0x00, GROUP_F },
	{ "DAI0_HIGH_F", 0x01, GROUP_F },
	{ "DAI0_MISCA0_O_F", 0x02, GROUP_F },
	{ "DAI0_MISCA1_O_F", 0x03, GROUP_F },
	{ "DAI0_MISCA2_O_F", 0x04, GROUP_F },
	{ "DAI0_MISCA3_O_F", 0x05, GROUP_F },
	{ "DAI0_MISCA4_O_F", 0x06, GROUP_F },
	{ "DAI0_MISCA5_O_F", 0x07, GROUP_F },
	{ "SPT0_ACLK_PBEN_O_F", 0x08, GROUP_F },
	{ "SPT0_AFS_PBEN_O_F", 0x09, GROUP_F },
	{ "SPT0_AD0_PBEN_O_F", 0x0a, GROUP_F },
	{ "SPT0_AD1_PBEN_O_F", 0x0b, GROUP_F },
	{ "SPT0_BCLK_PBEN_O_F", 0x0c, GROUP_F },
	{ "SPT0_BFS_PBEN_O_F", 0x0d, GROUP_F },
	{ "SPT0_BD0_PBEN_O_F", 0x0e, GROUP_F },
	{ "SPT0_BD1_PBEN_O_F", 0x0f, GROUP_F },
	{ "SPT1_ACLK_PBEN_O_F", 0x10, GROUP_F },
	{ "SPT1_AFS_PBEN_O_F", 0x11, GROUP_F },
	{ "SPT1_AD0_PBEN_O_F", 0x12, GROUP_F },
	{ "SPT1_AD1_PBEN_O_F", 0x13, GROUP_F },
	{ "SPT1_BCLK_PBEN_O_F", 0x14, GROUP_F },
	{ "SPT1_BFS_PBEN_O_F", 0x15, GROUP_F },
	{ "SPT1_BD0_PBEN_O_F", 0x16, GROUP_F },
	{ "SPT1_BD1_PBEN_O_F", 0x17, GROUP_F },
	{ "SPT2_ACLK_PBEN_O_F", 0x18, GROUP_F },
	{ "SPT2_AFS_PBEN_O_F", 0x19, GROUP_F },
	{ "SPT2_AD0_PBEN_O_F", 0x1a, GROUP_F },
	{ "SPT2_AD1_PBEN_O_F", 0x1b, GROUP_F },
	{ "SPT2_BCLK_PBEN_O_F", 0x1c, GROUP_F },
	{ "SPT2_BFS_PBEN_O_F", 0x1d, GROUP_F },
	{ "SPT2_BD0_PBEN_O_F", 0x1e, GROUP_F },
	{ "SPT2_BD1_PBEN_O_F", 0x1f, GROUP_F },
	{ "SPT3_ACLK_PBEN_O_F", 0x20, GROUP_F },
	{ "SPT3_AFS_PBEN_O_F", 0x21, GROUP_F },
	{ "SPT3_AD0_PBEN_O_F", 0x22, GROUP_F },
	{ "SPT3_AD1_PBEN_O_F", 0x23, GROUP_F },
	{ "SPT3_BCLK_PBEN_O_F", 0x24, GROUP_F },
	{ "SPT3_BFS_PBEN_O_F", 0x25, GROUP_F },
	{ "SPT3_BD0_PBEN_O_F", 0x26, GROUP_F },
	{ "SPT3_BD1_PBEN_O_F", 0x27, GROUP_F },
	{ "SPT0_ATDV_PBEN_O_F", 0x28, GROUP_F },
	{ "SPT0_BTDV_PBEN_O_F", 0x29, GROUP_F },
	{ "SPT1_ATDV_PBEN_O_F", 0x2a, GROUP_F },
	{ "SPT1_BTDV_PBEN_O_F", 0x2b, GROUP_F },
	{ "SPT2_ATDV_PBEN_O_F", 0x2c, GROUP_F },
	{ "SPT2_BTDV_PBEN_O_F", 0x2d, GROUP_F },
	{ "SPT3_ATDV_PBEN_O_F", 0x2e, GROUP_F },
	{ "SPT3_BTDV_PBEN_O_F", 0x2f, GROUP_F },
	{ "PDM0_CLK0_OE_O_F", 0x30, GROUP_F },
	{ "PDM0_SDATA_OE_O_F", 0x31, GROUP_F },
};

static const struct dai_source dai1_sources[] = {
	{ "DAI1_PB01_O_ABCDE", 0x00, GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB02_O_ABCDE", 0x01,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB03_O_ABCDE", 0x02,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB04_O_ABCDE", 0x03,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB05_O_ABCDE", 0x04,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB06_O_ABCDE", 0x05,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB07_O_ABCDE", 0x06,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB08_O_ABCDE", 0x07,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB09_O_ABCDE", 0x08,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB10_O_ABCDE", 0x09,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB11_O_ABCDE", 0x0a,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB12_O_ABCDE", 0x0b,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB13_O_ABCDE", 0x0c,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB14_O_ABCDE", 0x0d,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB15_O_ABCDE", 0x0e,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB16_O_ABCDE", 0x0f,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB17_O_ABCDE", 0x10,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB18_O_ABCDE", 0x11,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB19_O_ABCDE", 0x12,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_PB20_O_ABCDE", 0x13,
	 GROUP_A | GROUP_B | GROUP_C | GROUP_D | GROUP_E },
	{ "DAI1_LOW_ACE", 0x1e, GROUP_A | GROUP_C | GROUP_E },
	{ "DAI1_HIGH_ACE", 0x1f, GROUP_A | GROUP_C | GROUP_E },
	{ "SPT4_AD0_O_BD", 0x14, GROUP_B | GROUP_D },
	{ "SPT4_AD1_O_BD", 0x15, GROUP_B | GROUP_D },
	{ "SPT4_BD0_O_BD", 0x16, GROUP_B | GROUP_D },
	{ "SPT4_BD1_O_BD", 0x17, GROUP_B | GROUP_D },
	{ "SPT5_AD0_O_BD", 0x18, GROUP_B | GROUP_D },
	{ "SPT5_AD1_O_BD", 0x19, GROUP_B | GROUP_D },
	{ "SPT5_BD0_O_BD", 0x1a, GROUP_B | GROUP_D },
	{ "SPT5_BD1_O_BD", 0x1b, GROUP_B | GROUP_D },
	{ "SPT6_AD0_O_BD", 0x1c, GROUP_B | GROUP_D },
	{ "SPT6_AD1_O_BD", 0x1d, GROUP_B | GROUP_D },
	{ "SPT6_BD0_O_BD", 0x1e, GROUP_B | GROUP_D },
	{ "SPT6_BD1_O_BD", 0x1f, GROUP_B | GROUP_D },
	{ "DAI1_CRS_PB03_O_A", 0x00, GROUP_A },
	{ "SPT4_ACLK_O_A", 0x14, GROUP_A },
	{ "SPT4_BCLK_O_A", 0x15, GROUP_A },
	{ "SPT5_ACLK_O_A", 0x16, GROUP_A },
	{ "SPT5_BCLK_O_A", 0x17, GROUP_A },
	{ "SPT6_ACLK_O_A", 0x18, GROUP_A },
	{ "SPT6_BCLK_O_A", 0x19, GROUP_A },
	{ "SPDIF1_RX_CLK_O_A", 0x1a, GROUP_A },
	{ "SPDIF1_RX_TDMCLK_O_A", 0x1b, GROUP_A },
	{ "PCG0_CLKC_O_A", 0x1c, GROUP_A },
	{ "PCG0_CLKD_O_A", 0x1d, GROUP_A },
	{ "SRC4_DAT_OP_O_B", 0x20, GROUP_B },
	{ "SRC5_DAT_OP_O_B", 0x21, GROUP_B },
	{ "SRC6_DAT_OP_O_B", 0x22, GROUP_B },
	{ "SRC7_DAT_OP_O_B", 0x23, GROUP_B },
	{ "SRC4_TDM_IP_O_B", 0x24, GROUP_B },
	{ "SRC5_TDM_IP_O_B", 0x25, GROUP_B },
	{ "SRC6_TDM_IP_O_B", 0x26, GROUP_B },
	{ "SRC7_TDM_IP_O_B", 0x27, GROUP_B },
	{ "SPDIF1_RX_DAT_O_B", 0x28, GROUP_B },
	{ "SPT7_AD0_O_B", 0x2c, GROUP_B },
	{ "SPT7_AD1_O_B", 0x2d, GROUP_B },
	{ "SPT7_BD0_O_B", 0x2e, GROUP_B },
	{ "SPT7_BD1_O_B", 0x2f, GROUP_B },
	{ "SPDIF1_TX_O_B", 0x30, GROUP_B },
	{ "SRC3_CRS_DAT_OP_O_B", 0x31, GROUP_B },
	{ "SRC3_CRS_TDM_IP_O_B", 0x32, GROUP_B },
	{ "PDM1_SDATA_O_B", 0x33, GROUP_B },
	{ "DAI1_LOW_B", 0x3e, GROUP_B },
	{ "DAI1_HIGH_B", 0x3f, GROUP_B },
	{ "DAI1_CRS_PB04_O_C", 0x00, GROUP_C },
	{ "SPT4_AFS_O_C", 0x14, GROUP_C },
	{ "SPT4_BFS_O_C", 0x15, GROUP_C },
	{ "SPT5_AFS_O_C", 0x16, GROUP_C },
	{ "SPT5_BFS_O_C", 0x17, GROUP_C },
	{ "SPT6_AFS_O_C", 0x18, GROUP_C },
	{ "SPT6_BFS_O_C", 0x19, GROUP_C },
	{ "SPDIF1_FS_O_C", 0x1a, GROUP_C },
	{ "PCG0_FSC_O_C", 0x1c, GROUP_C },
	{ "PCG0_FSD_O_C", 0x1d, GROUP_C },
	{ "SPT4_ACLK_O_D", 0x20, GROUP_D },
	{ "SPT4_BCLK_O_D", 0x21, GROUP_D },
	{ "SPT5_ACLK_O_D", 0x22, GROUP_D },
	{ "SPT5_BCLK_O_D", 0x23, GROUP_D },
	{ "SPT6_ACLK_O_D", 0x24, GROUP_D },
	{ "SPT6_BCLK_O_D", 0x25, GROUP_D },
	{ "SPT4_AFS_O_D", 0x26, GROUP_D },
	{ "SPT4_BFS_O_D", 0x27, GROUP_D },
	{ "SPT5_AFS_O_D", 0x28, GROUP_D },
	{ "SPT5_BFS_O_D", 0x29, GROUP_D },
	{ "SPT6_AFS_O_D", 0x2a, GROUP_D },
	{ "SPT6_BFS_O_D", 0x2b, GROUP_D },
	{ "SPT7_AD0_O_D", 0x2c, GROUP_D },
	{ "SPT7_AD1_O_D", 0x2d, GROUP_D },
	{ "SPT7_BD0_O_D", 0x2e, GROUP_D },
	{ "SPT7_BD1_O_D", 0x2f, GROUP_D },
	{ "MLB0_CLKOUT_O_D", 0x30, GROUP_D },
	{ "SPDIF1_TX_BLKSTART_O_D", 0x31, GROUP_D },
	{ "SPT7_ACLK_O_D", 0x34, GROUP_D },
	{ "SPT7_BCLK_O_D", 0x35, GROUP_D },
	{ "SPT7_AFS_O_D", 0x36, GROUP_D },
	{ "SPT7_BFS_O_D", 0x37, GROUP_D },
	{ "PCG0_CLKC_O_D", 0x38, GROUP_D },
	{ "PCG0_CLKD_O_D", 0x39, GROUP_D },
	{ "PCG0_FSC_O_D", 0x3a, GROUP_D },
	{ "PCG0_FSD_O_D", 0x3b, GROUP_D },
	{ "SRC4_DAT_OP_O_D", 0x3d, GROUP_D },
	{ "SRC5_DAT_OP_O_D", 0x3e, GROUP_D },
	{ "SRC6_DAT_OP_O_D", 0x3f, GROUP_D },
	{ "SRC7_DAT_OP_O_D", 0x40, GROUP_D },
	{ "SPDIF1_RX_DAT_O_D", 0x41, GROUP_D },
	{ "SPDIF1_RX_FS_O_D", 0x42, GROUP_D },
	{ "SPDIF1_RX_CLK_O_D", 0x43, GROUP_D },
	{ "SPDIF1_RX_TDMCLK_O_D", 0x44, GROUP_D },
	{ "SPDIF1_TX_O_D", 0x45, GROUP_D },
	{ "SPT4_ATDV_O_D", 0x46, GROUP_D },
	{ "SPT4_BTDV_O_D", 0x47, GROUP_D },
	{ "SPT5_ATDV_O_D", 0x48, GROUP_D },
	{ "SPT5_BTDV_O_D", 0x49, GROUP_D },
	{ "SPT6_ATDV_O_D", 0x4a, GROUP_D },
	{ "SPT6_BTDV_O_D", 0x4b, GROUP_D },
	{ "SPT7_ATDV_O_D", 0x4c, GROUP_D },
	{ "SPT7_BTDV_O_D", 0x4d, GROUP_D },
	{ "SPDIF1_RX_LRCLK_REF_O_D", 0x4e, GROUP_D },
	{ "SPDIF1_RX_LRCLK_FB_O_D", 0x4f, GROUP_D },
	{ "PCG0_CRS_CLKA_O_D", 0x50, GROUP_D },
	{ "PCG0_CRS_CLKB_O_D", 0x51, GROUP_D },
	{ "PCG0_CRS_FSA_O_D", 0x52, GROUP_D },
	{ "PCG0_CRS_FSB_O_D", 0x53, GROUP_D },
	{ "DAI1_CRS_PB03_O_D", 0x54, GROUP_D },
	{ "DAI1_CRS_PB04_O_D", 0x55, GROUP_D },
	{ "PCG_CLKG_O_D", 0x56, GROUP_D },
	{ "PCG_CLKH_O_D", 0x57, GROUP_D },
	{ "PCG_FSG_O_D", 0x58, GROUP_D },
	{ "PCG_FSH_O_D", 0x59, GROUP_D },
	{ "PCG_CLKC_INV_O_D", 0x5a, GROUP_D },
	{ "PCG_CLKG_INV_O_D", 0x5b, GROUP_D },
	{ "PCG_CLKD_INV_O_D", 0x5c, GROUP_D },
	{ "PCG_CLKH_INV_O_D", 0x5d, GROUP_D },
	{ "PCG_FSC_INV_O_D", 0x5e, GROUP_D },
	{ "PCG_FSD_INV_O_D", 0x5f, GROUP_D },
	{ "PCG_FSG_INV_O_D", 0x60, GROUP_D },
	{ "PCG_FSH_INV_O_D", 0x61, GROUP_D },
	{ "PDM1_CLK0_O_D", 0x62, GROUP_D },
	{ "PDM1_SDATA_O_D", 0x63, GROUP_D },
	{ "DAI1_LOW_D", 0x7e, GROUP_D },
	{ "DAI1_HIGH_D", 0x7f, GROUP_D },
	{ "SPT4A_FS_O_E", 0x14, GROUP_E },
	{ "SPT4B_FS_O_E", 0x15, GROUP_E },
	{ "SPT5A_FS_O_E", 0x16, GROUP_E },
	{ "SPT5B_FS_O_E", 0x17, GROUP_E },
	{ "SPT6A_FS_O_E", 0x18, GROUP_E },
	{ "SPT6B_FS_O_E", 0x19, GROUP_E },
	{ "SPDIF1_TX_BLKSTART_O_E", 0x1a, GROUP_E },
	{ "PCG0_FSC_O_E", 0x1b, GROUP_E },
	{ "PCG0_CLKD_O_E", 0x1c, GROUP_E },
	{ "PCG0_FSD_O_E", 0x1d, GROUP_E },
	{ "DAI1_LOW_F", 0x00, GROUP_F },
	{ "DAI1_HIGH_F", 0x01, GROUP_F },
	{ "DAI1_MISCA0_O_F", 0x02, GROUP_F },
	{ "DAI1_MISCA1_O_F", 0x03, GROUP_F },
	{ "DAI1_MISCA2_O_F", 0x04, GROUP_F },
	{ "DAI1_MISCA3_O_F", 0x05, GROUP_F },
	{ "DAI1_MISCA4_O_F", 0x06, GROUP_F },
	{ "DAI1_MISCA5_O_F", 0x07, GROUP_F },
	{ "SPT4_ACLK_PBEN_O_F", 0x08, GROUP_F },
	{ "SPT4_AFS_PBEN_O_F", 0x09, GROUP_F },
	{ "SPT4_AD0_PBEN_O_F", 0x0a, GROUP_F },
	{ "SPT4_AD1_PBEN_O_F", 0x0b, GROUP_F },
	{ "SPT4_BCLK_PBEN_O_F", 0x0c, GROUP_F },
	{ "SPT4_BFS_PBEN_O_F", 0x0d, GROUP_F },
	{ "SPT4_BD0_PBEN_O_F", 0x0e, GROUP_F },
	{ "SPT4_BD1_PBEN_O_F", 0x0f, GROUP_F },
	{ "SPT5_ACLK_PBEN_O_F", 0x10, GROUP_F },
	{ "SPT5_AFS_PBEN_O_F", 0x11, GROUP_F },
	{ "SPT5_AD0_PBEN_O_F", 0x12, GROUP_F },
	{ "SPT5_AD1_PBEN_O_F", 0x13, GROUP_F },
	{ "SPT5_BCLK_PBEN_O_F", 0x14, GROUP_F },
	{ "SPT5_BFS_PBEN_O_F", 0x15, GROUP_F },
	{ "SPT5_BD0_PBEN_O_F", 0x16, GROUP_F },
	{ "SPT5_BD1_PBEN_O_F", 0x17, GROUP_F },
	{ "SPT6_ACLK_PBEN_O_F", 0x18, GROUP_F },
	{ "SPT6_AFS_PBEN_O_F", 0x19, GROUP_F },
	{ "SPT6_AD0_PBEN_O_F", 0x1a, GROUP_F },
	{ "SPT6_AD1_PBEN_O_F", 0x1b, GROUP_F },
	{ "SPT6_BCLK_PBEN_O_F", 0x1c, GROUP_F },
	{ "SPT6_BFS_PBEN_O_F", 0x1d, GROUP_F },
	{ "SPT6_BD0_PBEN_O_F", 0x1e, GROUP_F },
	{ "SPT6_BD1_PBEN_O_F", 0x1f, GROUP_F },
	{ "SPT7_ACLK_PBEN_O_F", 0x20, GROUP_F },
	{ "SPT7_AFS_PBEN_O_F", 0x21, GROUP_F },
	{ "SPT7_AD0_PBEN_O_F", 0x22, GROUP_F },
	{ "SPT7_AD1_PBEN_O_F", 0x23, GROUP_F },
	{ "SPT7_BCLK_PBEN_O_F", 0x24, GROUP_F },
	{ "SPT7_BFS_PBEN_O_F", 0x25, GROUP_F },
	{ "SPT7_BD0_PBEN_O_F", 0x26, GROUP_F },
	{ "SPT7_BD1_PBEN_O_F", 0x27, GROUP_F },
	{ "SPT4_ATDV_PBEN_O_F", 0x28, GROUP_F },
	{ "SPT4_BTDV_PBEN_O_F", 0x29, GROUP_F },
	{ "SPT5_ATDV_PBEN_O_F", 0x2a, GROUP_F },
	{ "SPT5_BTDV_PBEN_O_F", 0x2b, GROUP_F },
	{ "SPT6_ATDV_PBEN_O_F", 0x2c, GROUP_F },
	{ "SPT6_BTDV_PBEN_O_F", 0x2d, GROUP_F },
	{ "SPT7_ATDV_PBEN_O_F", 0x2e, GROUP_F },
	{ "SPT7_BTDV_PBEN_O_F", 0x2f, GROUP_F },
	{ "PDM1_CLK0_OE_O_F", 0x30, GROUP_F },
	{ "PDM1_SDATA_OE_O_F", 0x31, GROUP_F },
};

static int32_t adsp_populate_group_combinations(struct adsp_sru_ctrl
						*adsp_sru_ctrl)
{
	struct device *dev = adsp_sru_ctrl->dev;

	struct group_combination *grp_combs = adsp_sru_ctrl->grp_combs;
	u32 *grp_combs_cnt = &adsp_sru_ctrl->grp_combs_cnt;

	u32 *poss_grp_combs =
	    (u32 *) kmalloc_array(1024, sizeof(*poss_grp_combs),
				  GFP_KERNEL);
	u32 grps_found = 0;
	u32 found = 0;
	u32 i, j, index;

	if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 0) {
		for (i = 0; i < DAI0_SOURCE_COUNT; i++) {
			for (found = 0, j = 0; j < grps_found; j++) {
				if (poss_grp_combs[j] ==
				    dai0_sources[i].group) {
					found = 1;
					break;
				}
			}
			if (!found)
				poss_grp_combs[grps_found++] =
				    dai0_sources[i].group;
		}
	}

	if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 1) {
		for (i = 0; i < DAI1_SOURCE_COUNT; i++) {
			for (found = 0, j = 0; j < grps_found; j++) {
				if (poss_grp_combs[j] ==
				    dai1_sources[i].group) {
					found = 1;
					break;
				}
			}
			if (!found)
				poss_grp_combs[grps_found++] =
				    dai1_sources[i].group;
		}
	}

	for (i = 0; i < grps_found; i++) {
		grp_combs[*grp_combs_cnt].associated_groups =
		    poss_grp_combs[i];
		grp_combs[*grp_combs_cnt].dest_names =
		    devm_kcalloc(dev, sizeof(*adsp_sru_ctrl->group_names),
				 DAI0_DESTINATION_COUNT +
				 DAI1_DESTINATION_COUNT, GFP_KERNEL);

		if (!grp_combs[*grp_combs_cnt].dest_names) {
			dev_err(dev,
				"Insufficient memory available to allocate group associations\n");
			return -ENOMEM;
		}

		if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 0) {
			for (j = 0; j < DAI0_DESTINATION_COUNT; j++) {
				if (dai0_destinations[j].group &
				    poss_grp_combs[i]) {
					index =
					    grp_combs
					    [*grp_combs_cnt].destination_count;
					grp_combs
					    [*grp_combs_cnt].dest_names
					    [index] =
					    dai0_destinations
					    [j].dest_signal;
					grp_combs
					    [*grp_combs_cnt].destination_count++;
				}
			}
		}

		if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 1) {
			for (j = 0; j < DAI1_DESTINATION_COUNT; j++) {
				if (dai1_destinations[j].group &
				    poss_grp_combs[i]) {
					index =
					    grp_combs
					    [*grp_combs_cnt].destination_count;
					grp_combs
					    [*grp_combs_cnt].dest_names
					    [index] =
					    dai1_destinations
					    [j].dest_signal;
					grp_combs
					    [*grp_combs_cnt].destination_count++;
				}
			}
		}

		(*grp_combs_cnt)++;
	}

	kfree(poss_grp_combs);

	return 0;
}

static int adsp_pinmux_get_functions_count(struct pinctrl_dev *pctldev)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);
	u32 count = 0;

	if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 0)
		count += DAI0_SOURCE_COUNT;

	if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 1)
		count += DAI1_SOURCE_COUNT;

	return count;
}

static const struct dai_source *adsp_find_source(struct adsp_sru_ctrl
						 *adsp_sru_ctrl,
						 unsigned int selector)
{

	if (adsp_sru_ctrl->has_extended || adsp_sru_ctrl->dai == 0) {
		if (selector < DAI0_SOURCE_COUNT)
			return &dai0_sources[selector];
	}

	if (adsp_sru_ctrl->has_extended) {
		if (selector >= DAI0_SOURCE_COUNT &&
		    selector <=
		    (DAI0_SOURCE_COUNT + DAI1_SOURCE_COUNT - 1))
			return &dai1_sources[selector - DAI0_SOURCE_COUNT];
	} else if (adsp_sru_ctrl->dai == 1) {
		if (selector < DAI1_SOURCE_COUNT)
			return &dai1_sources[selector];
	}

	dev_err(adsp_sru_ctrl->dev, "Invalid selector %d\n", selector);
	return NULL;
}

static const char *adsp_pinmux_get_function_name(struct pinctrl_dev
						 *pctldev,
						 unsigned int selector)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);

	return adsp_find_source(adsp_sru_ctrl, selector)->source_signal;
}

static int adsp_pinmux_get_function_groups(struct pinctrl_dev *pctldev,
					   unsigned int selector,
					   const char *const **groups,
					   unsigned *const num_groups)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);
	struct group_combination *grp_combs = adsp_sru_ctrl->grp_combs;
	u32 *grp_combs_cnt = &adsp_sru_ctrl->grp_combs_cnt;
	u32 i, associated_groups;

	associated_groups =
	    adsp_find_source(adsp_sru_ctrl, selector)->group;

	for (i = 0; i < *grp_combs_cnt; i++) {
		if (grp_combs[i].associated_groups == associated_groups) {
			*groups = grp_combs[i].dest_names;
			*num_groups = grp_combs[i].destination_count;
			return 0;
		}
	}

	dev_err(adsp_sru_ctrl->dev,
		"Unable to find associated function group\n");
	return -ENODEV;
}

/* Each group is exactly 1 pin and group id == pin id */
static int adsp_pinmux_set_mux(struct pinctrl_dev *pctldev,
			       unsigned int func, unsigned int group)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);

	u32 selection_code, register_val;
	u32 offset, offset_ext, width, input;
	u8 ext_bits;

	selection_code =
	    adsp_find_source(adsp_sru_ctrl, func)->selection_code;

	offset = adsp_sru_ctrl->dest[group].offset;
	offset_ext = adsp_sru_ctrl->dest[group].offset_ext;
	width = adsp_sru_ctrl->dest[group].width;
	input = adsp_sru_ctrl->dest[group].input;

	register_val = readl(adsp_sru_ctrl->regs + offset);
	register_val &= ~GENMASK((width * input) + width - 1, (width * input));	//Clear bits
	register_val |= selection_code << width * input;	//Set bits
	writel(register_val, adsp_sru_ctrl->regs + offset);

	/*
	 * If we're using the DAI1 source table, we also need to set the corresponding
	 * extended selection bits
	 */
	if (adsp_sru_ctrl->has_extended) {
		if (func >= DAI0_SOURCE_COUNT
		    && func <=
		    (DAI0_SOURCE_COUNT + DAI1_SOURCE_COUNT - 1)) {
			switch (width) {
			case 0x5:
				ext_bits = 0x3;
				break;
			case 0x6:
			case 0x7:
				ext_bits = 0x2;
				break;
			}

			register_val =
			    readl(adsp_sru_ctrl->regs + offset_ext);
			register_val |= ext_bits << 4 * input;
			writel(register_val,
			       adsp_sru_ctrl->regs + offset_ext);
		}
	}

	return 0;
}

static const struct pinmux_ops adsp_pmxops = {
	.get_functions_count = adsp_pinmux_get_functions_count,
	.get_function_name = adsp_pinmux_get_function_name,
	.get_function_groups = adsp_pinmux_get_function_groups,
	.set_mux = adsp_pinmux_set_mux,
	.strict = true,
};

/*
 * We want to make one group per pin so that we can refer to the pins by group
 * later on when mux assignments are made
 */
static int adsp_sru_ctrl_init_groups(struct adsp_sru_ctrl *adsp_sru_ctrl,
				     struct pinctrl_desc *desc)
{
	struct device *dev = adsp_sru_ctrl->dev;
	struct pinctrl_pin_desc *all_pins;
	size_t pin;

	all_pins = devm_kcalloc(dev, sizeof(*all_pins),
				adsp_sru_ctrl->dest_count, GFP_KERNEL);

	adsp_sru_ctrl->pins =
	    devm_kcalloc(dev, sizeof(*adsp_sru_ctrl->pins),
			 adsp_sru_ctrl->dest_count, GFP_KERNEL);
	if (!adsp_sru_ctrl->pins)
		return -ENOMEM;

	adsp_sru_ctrl->group_names =
	    devm_kcalloc(dev, sizeof(*adsp_sru_ctrl->group_names),
			 adsp_sru_ctrl->dest_count, GFP_KERNEL);
	if (!adsp_sru_ctrl->group_names)
		return -ENOMEM;

	for (pin = 0; pin < adsp_sru_ctrl->dest_count; ++pin) {
		adsp_sru_ctrl->group_names[pin] =
		    devm_kasprintf(dev, GFP_KERNEL, "%s",
				   adsp_sru_ctrl->dest[pin].dest_signal);
		adsp_sru_ctrl->pins[pin] = (unsigned int) pin;

		all_pins[pin].name = adsp_sru_ctrl->group_names[pin];
		all_pins[pin].number = (unsigned int) pin;
	}

	desc->pins = all_pins;
	desc->npins = adsp_sru_ctrl->dest_count;

	return 0;
}

static int adsp_sru_ctrl_get_groups_count(struct pinctrl_dev *pctldev)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);

	return adsp_sru_ctrl->dest_count;
}

static const char *adsp_sru_ctrl_get_group_name(struct pinctrl_dev
						*pctldev,
						unsigned int selector)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);

	return adsp_sru_ctrl->group_names[selector];
}

static int adsp_sru_ctrl_dt_subnode_to_map(struct pinctrl_dev *pctldev,
					   struct device_node *np,
					   struct pinctrl_map **map,
					   unsigned int *reserved_maps,
					   unsigned int *num_maps)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);
	struct property *prop;
	const char *dest_name;
	const char *source_name;
	unsigned long *configs;
	unsigned int num_pins, pos;
	unsigned int reserve = 0;
	const __be32 *p1, *p2;
	u32 source, destination, num_entries;
	int ret;

	num_pins = of_property_count_u32_elems(np, "sru-routing");
	if (num_pins <= 0) {
		dev_err(adsp_sru_ctrl->dev,
			"Must have at least one `sru-routing` entry in %pOFn.\n",
			np);
		return -EINVAL;
	}

	reserve = num_pins / 2;

	ret =
	    pinctrl_utils_reserve_map(pctldev, map, reserved_maps,
				      num_maps, reserve);
	if (ret)
		goto exit;

	prop = of_find_property(np, "sru-routing", NULL);
	p2 = NULL;
	num_entries = 0;
	do {
		p1 = of_prop_next_u32(prop, p2, &source);
		if (p1)
			p2 = of_prop_next_u32(prop, p1, &destination);

		if (p1 && p2) {

			num_entries += 2;

			if (adsp_sru_ctrl->dai == 0) {
				if (destination >= DAI0_DST_DTS_BINDING &&
				    destination <=
				    (DAI1_DST_DTS_BINDING - 1)) {
					pos =
					    destination -
					    DAI0_DST_DTS_BINDING;
					dest_name =
					    adsp_sru_ctrl->
					    dest[pos].dest_signal;
				} else {
					dev_err(adsp_sru_ctrl->dev,
						"%d is not a valid destination for DAI0\n",
						destination);
					return -EINVAL;
				}
			}

			if (adsp_sru_ctrl->dai == 1) {
				if (destination >= DAI1_DST_DTS_BINDING &&
				    destination <=
				    (DAI0_SRC_DTS_BINDING - 1)) {
					pos =
					    destination -
					    DAI1_DST_DTS_BINDING;
					dest_name =
					    adsp_sru_ctrl->
					    dest[pos].dest_signal;
				} else {
					dev_err(adsp_sru_ctrl->dev,
						"%d is not a valid destination for DAI1\n",
						destination);
					return -EINVAL;
				}
			}

			if (adsp_sru_ctrl->has_extended
			    || adsp_sru_ctrl->dai == 0) {
				if (source >= DAI0_SRC_DTS_BINDING
				    && source <=
				    (DAI1_SRC_DTS_BINDING - 1)) {
					pos =
					    source - DAI0_SRC_DTS_BINDING;
					source_name =
					    dai0_sources
					    [pos].source_signal;
				}
			}

			if (adsp_sru_ctrl->has_extended
			    || adsp_sru_ctrl->dai == 1) {
				if (source >= DAI1_SRC_DTS_BINDING
				    && source <=
				    (DAI1_SRC_DTS_BINDING_END - 1)) {
					pos =
					    source - DAI1_SRC_DTS_BINDING;
					source_name =
					    dai1_sources
					    [pos].source_signal;
				}
			}

			if (source_name == NULL) {
				dev_err(adsp_sru_ctrl->dev,
					"%d is not a valid source\n",
					source);
				return -EINVAL;
			}

			ret =
			    pinctrl_utils_add_map_mux(pctldev, map,
						      reserved_maps,
						      num_maps, dest_name,
						      source_name);

			if (ret)
				goto exit;
		}
	} while (p1 && p2);

	if ((num_entries <= 0) || (num_entries % 2)) {
		dev_err(adsp_sru_ctrl->dev,
			"`sru-routing` entry in %pOFn must have source/destination pairs\n",
			np);
		return -EINVAL;
	}

exit:
	kfree(configs);
	return ret;
}

static int adsp_sru_ctrl_dt_node_to_map(struct pinctrl_dev *pctldev,
					struct device_node *np,
					struct pinctrl_map **map,
					unsigned int *num_maps)
{
	unsigned int reserved_maps;
	struct device_node *child_np;
	int ret;

	reserved_maps = 0;
	*map = NULL;
	*num_maps = 0;

	for_each_child_of_node(np, child_np) {
		ret =
		    adsp_sru_ctrl_dt_subnode_to_map(pctldev, child_np, map,
						    &reserved_maps,
						    num_maps);
		if (ret < 0)
			goto exit;
	}
	return 0;

exit:
	pinctrl_utils_free_map(pctldev, *map, *num_maps);
	return ret;
}

static int adsp_sru_ctrl_get_group_pins(struct pinctrl_dev *pctldev,
					unsigned int selector,
					unsigned const **pins,
					unsigned *const num_pins)
{
	struct adsp_sru_ctrl *adsp_sru_ctrl =
	    pinctrl_dev_get_drvdata(pctldev);

	*pins = &adsp_sru_ctrl->pins[selector];
	*num_pins = 1;

	return 0;
}

static const struct pinctrl_ops adsp_pctlops = {
	.get_groups_count = adsp_sru_ctrl_get_groups_count,
	.get_group_name = adsp_sru_ctrl_get_group_name,
	.get_group_pins = adsp_sru_ctrl_get_group_pins,
	.dt_node_to_map = adsp_sru_ctrl_dt_node_to_map,
};

static const int adsp_sru_ctrl_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct device_node *np = dev->of_node;
	struct adsp_sru_ctrl *adsp_sru_ctrl;
	struct pinctrl_desc *pnctrl_desc;
	struct resource *res;
	struct regmap *regmap;
	int ret;

	adsp_sru_ctrl =
	    devm_kzalloc(dev, sizeof(*adsp_sru_ctrl), GFP_KERNEL);
	if (!adsp_sru_ctrl)
		return -ENOMEM;

	adsp_sru_ctrl->dev = dev;

	pnctrl_desc = devm_kzalloc(dev, sizeof(*pnctrl_desc), GFP_KERNEL);
	if (!pnctrl_desc)
		return -ENOMEM;

	res = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	adsp_sru_ctrl->regs = devm_ioremap_resource(dev, res);
	if (IS_ERR(adsp_sru_ctrl->regs))
		return PTR_ERR(adsp_sru_ctrl->regs);

	pnctrl_desc->name = dev_name(dev);
	pnctrl_desc->pmxops = &adsp_pmxops;
	pnctrl_desc->pctlops = &adsp_pctlops;
	pnctrl_desc->owner = THIS_MODULE;

	regmap =
	    system_config_regmap_lookup_by_phandle(np,
						   "adi,system-config");
	if (IS_ERR(regmap)) {
		if (PTR_ERR(regmap) == -EPROBE_DEFER)
			return PTR_ERR(regmap);

		dev_err(&pdev->dev,
			"adi,system-config regmap not connected\n");
		return PTR_ERR(regmap);
	}

	adsp_sru_ctrl->dai = of_alias_get_id(np, "sru");
	if (adsp_sru_ctrl->dai == 0) {
		adsp_sru_ctrl->dest = dai0_destinations;
		adsp_sru_ctrl->dest_count = DAI0_DESTINATION_COUNT;
		regmap_write(regmap, ADI_SYSTEM_REG_DAI0_IE, 0xffffffff);
	} else if (adsp_sru_ctrl->dai == 1) {
		adsp_sru_ctrl->dest = dai1_destinations;
		adsp_sru_ctrl->dest_count = DAI1_DESTINATION_COUNT;
		regmap_write(regmap, ADI_SYSTEM_REG_DAI1_IE, 0xffffffff);
	} else {
		dev_err(adsp_sru_ctrl->dev, "Unknown DAI instance (%d)\n",
			adsp_sru_ctrl->dai);
		return -EINVAL;
	}

	if (of_property_read_bool(np, "has-extended")) {
		adsp_sru_ctrl->has_extended = 1;
		dev_info(adsp_sru_ctrl->dev,
			 "Started with extended selection codes (SC594, SC598)\n");
	} else {
		adsp_sru_ctrl->has_extended = 0;
		dev_info(adsp_sru_ctrl->dev,
			 "Started without extended selection codes (SC573, SC584, SC589)\n");
	}

	ret = adsp_sru_ctrl_init_groups(adsp_sru_ctrl, pnctrl_desc);
	if (ret)
		return ret;

	ret = adsp_populate_group_combinations(adsp_sru_ctrl);
	if (ret)
		return ret;

	ret =
	    devm_pinctrl_register_and_init(dev, pnctrl_desc, adsp_sru_ctrl,
					   &adsp_sru_ctrl->pin_dev);
	if (ret)
		return ret;

	platform_set_drvdata(pdev, adsp_sru_ctrl);

	return pinctrl_enable(adsp_sru_ctrl->pin_dev);
}

static const struct of_device_id adsp_sru_ctrl_of_match[] = {
	{.compatible = "adi,adsp-sru-ctrl", },
	{ },
};

MODULE_DEVICE_TABLE(of, adsp_sru_ctrl_of_match);

static struct platform_driver adsp_sru_ctrl_driver = {
	.driver = {
		   .name = "adsp-sru-ctrl",
		   .of_match_table = adsp_sru_ctrl_of_match,
		   .suppress_bind_attrs = true,
		    },
	.probe = adsp_sru_ctrl_probe,
};

static int __init adsp_sru_ctrl_init(void)
{
	return platform_driver_register(&adsp_sru_ctrl_driver);
}

arch_initcall(adsp_sru_ctrl_init);
