# SPDX-License-Identifier: GPL-2.0
#
# Makefile for TMC5222/TMC5221 Stepper Motor Controller drivers
#

obj-$(CONFIG_TMC5222_CORE)	+= tmc5222-core.o
obj-$(CONFIG_TMC5222_I2C)	+= tmc5222-i2c.o
obj-$(CONFIG_TMC5221_SPI)	+= tmc5221-spi.o
