# SPDX-License-Identifier: GPL-2.0
# Copyright (c) Meta Platforms, Inc. and affiliates.

#
# Makefile for the Meta(R) Platforms Network Interface Controller
#

obj-$(CONFIG_MPNIC) += mpnic.o

mpnic-y := \
	mpnic_init.o \
	mpnic_pci.o \
# End of mpnic-y
