#
# Makefile for arch/microblaze/platform directory
#
#obj-$(CONFIG_PLATFORM_GENERIC) += generic/

obj-y	+= platform.o
obj-$(CONFIG_PLATFORM_ML605_ADIXCOMM) += platform_xcomm.o
obj-$(CONFIG_PLATFORM_KC705_ADIXCOMM) += platform_xcomm.o
