#
# Makefile iio/frequency
#

obj-$(CONFIG_AD9523) += ad9523.o
obj-$(CONFIG_AD5930) += ad5930.o
obj-$(CONFIG_AD9832) += ad9832.o
obj-$(CONFIG_AD9834) += ad9834.o
obj-$(CONFIG_AD9850) += ad9850.o
obj-$(CONFIG_AD9852) += ad9852.o
obj-$(CONFIG_AD9910) += ad9910.o
obj-$(CONFIG_AD9951) += ad9951.o
obj-$(CONFIG_ADF4350) += adf4350.o
obj-$(CONFIG_AD9122_CF) += cf_ad9122.o
obj-$(CONFIG_AD9122_CF_DAC) += ad9122.o
obj-$(CONFIG_AD9548) += ad9548.o
