obj-$(CONFIG_DRM_IMX_HDP) += imx-hdp.o \
			imx-dp.o imx-hdmi.o imx-arc.o\
			API_AFE_ss28fdsoi_kiran_hdmitx.o \
			API_AFE_t28hpc_hdmitx.o \
			ss28fdsoi_hdmitx_table.o \
			API_AFE_mcu1_dp.o

obj-$(CONFIG_IMX_HDP_CEC) += imx-cec.o \
