/* SPDX-License-Identifier: GPL-2.0 */
/*
 * an7581-reg.h  --  Airoha AN7581 audio driver reg definition
 */

#ifndef _AN7581_REG_H_
#define _AN7581_REG_H_

#define AFE_DAC_CON0			0x0
#define   AFE_DL1_ENABLE_SHIFT		17
#define   AFE_UL1_ENABLE_SHIFT		1
#define   AFE_AFE_ENABLE_SHIFT		0

#define ETDM_COWORK_CON0		0x4c
#define   EDTM_IN1_SLAVE_SEL		GENMASK(27, 24)
#define     EDTM_IN1_SLAVE_FROM_ETDMIN1_SLAVE FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0x1)
#define     EDTM_IN1_SLAVE_FROM_ETDMIN2_MASTER FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0x2)
#define     EDTM_IN1_SLAVE_FROM_ETDMIN2_SLAVE FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0x3)
#define     EDTM_IN1_SLAVE_FROM_ETDMOUT1_MASTER FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0x8)
#define     EDTM_IN1_SLAVE_FROM_ETDMOUT1_SLAVE FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0x9)
#define     EDTM_IN1_SLAVE_FROM_ETDMOUT2_MASTER FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0xa)
#define     EDTM_IN1_SLAVE_FROM_ETDMOUT2_SLAVE FIELD_PREP_CONST(EDTM_IN1_SLAVE_SEL, 0xb)
#define   EDTM_OUT1_SLAVE_SEL		GENMASK(11, 8)
#define     EDTM_OUT1_SLAVE_FROM_ETDMIN1_MASTER FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0x0)
#define     EDTM_OUT1_SLAVE_FROM_ETDMIN1_SLAVE FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0x1)
#define     EDTM_OUT1_SLAVE_FROM_ETDMIN2_MASTER FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0x2)
#define     EDTM_OUT1_SLAVE_FROM_ETDMIN2_SLAVE FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0x3)
#define     EDTM_OUT1_SLAVE_FROM_ETDMOUT1_SLAVE FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0x9)
#define     EDTM_OUT1_SLAVE_FROM_ETDMOUT2_MASTER FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0xa)
#define     EDTM_OUT1_SLAVE_FROM_ETDMOUT2_SLAVE FIELD_PREP_CONST(EDTM_OUT1_SLAVE_SEL, 0xb)
#define ETDM_COWORK_CON1		0x50
#define   EDTM_IN1_SDATA0_SEL		GENMASK(3, 0)
#define     EDTM_IN1_SDATA0_FROM_PAD FIELD_PREP_CONST(EDTM_IN1_SDATA0_SEL, 0x0)
#define     EDTM_IN1_SDATA0_FROM_ETDMIN2 FIELD_PREP_CONST(EDTM_IN1_SDATA0_SEL, 0x2)
#define     EDTM_IN1_SDATA0_FROM_ETDMOUT1 FIELD_PREP_CONST(EDTM_IN1_SDATA0_SEL, 0x8)
#define     EDTM_IN1_SDATA0_FROM_ETDMOUT2 FIELD_PREP_CONST(EDTM_IN1_SDATA0_SEL, 0xa)
#define ETDM_IN1_CON0			0x5c
#define   ETDM_CH_NUM			GENMASK(26, 23)
#define   ETDM_WRD_LEN			GENMASK(20, 16)
#define   ETDM_BIT_LEN			GENMASK(15, 11)
#define   ETDM_FMT			GENMASK(8, 6)
#define   ETDM_SLAVE_MODE		BIT(5)
#define   ETDM_IN_EN			BIT(0)
#define ETDM_IN1_CON1			0x60
#define   EDTM_LRCK_AUTO_MODE		BIT(29)
#define   EDTM_DIRECT_INPUT_MASTER_BCK	BIT(30)
#define   EDTM_CKEN_SEL			BIT(12)
#define   EDTM_LRCK_AUTO_OFF		BIT(10)
#define   EDTM_INITIAL_POINT		GENMASK(9, 5)
#define   EDTM_INITIAL_COUNT		GENMASK(4, 0)
#define ETDM_IN1_CON2			0x64
#define   IN_CLK_SRC			GENMASK(12, 10)
#define ETDM_IN1_CON3			0x68
#define   IN_SEL_FS			GENMASK(30, 26)
#define ETDM_IN1_CON4			0x6c
#define   IN_RELATCH			GENMASK(24, 20)
#define   IN_CLK_INV			BIT(18)
#define ETDM_IN1_CON5			0x70
#define ETDM_IN1_CON6			0x74
#define ETDM_OUT1_CON0			0x7c
#define   ETDM_SYNC_MODE		BIT(1)
#define   ETDM_OUT_EN			BIT(0)
#define ETDM_OUT1_CON1			0x80
#define ETDM_OUT1_CON2			0x84
#define ETDM_OUT1_CON3			0x88
#define ETDM_OUT1_CON4			0x8c
#define   OUT_RELATCH			GENMASK(28, 24)
#define   OUT_CLK_SRC			GENMASK(8, 6)
#define   OUT_SEL_FS			GENMASK(4, 0)
#define ETDM_OUT1_CON5			0x90
#define   ETDM_CLK_DIV			BIT(12)
#define   OUT_CLK_INV			BIT(9)
#define ETDM_OUT1_CON6			0x94
#define ETDM_OUT1_CON7			0x98

#define AFE_DL1_BASE			0xa8
#define AFE_DL1_END			0xb0
#define AFE_DL1_CUR			0xac
#define AFE_DL1_CON0			0xb4
#define   AFE_PBUF_SIZE_SHIFT		16
#define   AFE_PBUF_SIZE_MASK		GENMASK(1, 0)
#define   AFE_MINLEN_SHIFT		8
#define   AFE_MINLEN_MASK		GENMASK(3, 0)
#define   AFE_HD_SHIFT			5

#define AFE_UL1_BASE			0xc4
#define AFE_UL1_END			0xc8
#define AFE_UL1_CUR			0xcc
#define AFE_UL1_CON0			0xd0
#define   AFE_HD_ALIGN_SHIFT		6

#define AFE_IRQ_CON0			0xe4
#define   AFE_IRQ_EN_SEL		BIT(4)
#define   AFE_IRQ_EN_SEL_I2SIN		FIELD_PREP_CONST(AFE_IRQ_EN_SEL, 0x0)
#define   AFE_IRQ_EN_SEL_I2SOUT		FIELD_PREP_CONST(AFE_IRQ_EN_SEL, 0x1)
#define   AFE_IRQ_MISS_FLG_CLR_SHIFT	3
#define   AFE_IRQ_CLR_SHIFT		2
#define   AFE_IRQ_ON_SHIFT		0
#define AFE_IRQ_CNT			0xe8
#define   AFE_IRQ_CNT_SHIFT		0
#define   AFE_IRQ_CNT_MASK		GENMASK(31, 0)

#define AFE_IRQ_STS			0xf8
#define  AFE_IRQ_STS_PLAY		BIT(1)
#define  AFE_IRQ_STS_RECORD		BIT(0)

#define AFE_MAX_REGISTER		AFE_IRQ_STS

#define AFE_IRQ1_CON0			0x0
#define AFE_IRQ1_CNT			0x4

#define AFE_IRQ1_MAX_REGISTER		AFE_IRQ1_CNT

#endif
