# SPDX-License-Identifier: GPL-2.0

# platform driver
snd-soc-an7581-afe-y := \
	an7581-afe-pcm.o \
	an7581-dai-etdm.o

obj-$(CONFIG_SND_SOC_AN7581) += snd-soc-an7581-afe.o
obj-$(CONFIG_SND_SOC_AN7581_WM8960) += an7581-wm8960.o
