# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ZYNQ) += \
	zynq-zed-adv7511-hmcad15xx.dtb \
	zynq-zed-adv7511-hmcad15xx_12b.dtb \
	zynq-zed-adv7511-hmcad15xx_dual.dtb \
	zynq-zed-adv7511-hmcad15xx_12b_dual.dtb \
	zynq-zed-adv7511-hmcad15xx_quad.dtb \
	zynq-zed-adv7511-hmcad15xx_12b_quad.dtb \
	ynq-zed-adv7511-hmcad15xx_14b.dtb \
	zynq-cc108.dtb \
	zynq-ebaz4205.dtb \
	zynq-microzed.dtb \
	zynq-parallella.dtb \
	zynq-zc702.dtb \
	zynq-zc706.dtb \
	zynq-zc770-xm010.dtb \
	zynq-zc770-xm011.dtb \
	zynq-zc770-xm012.dtb \
	zynq-zc770-xm013.dtb \
	zynq-zed.dtb \
	zynq-zturn.dtb \
	zynq-zturn-v5.dtb \
	zynq-zybo.dtb \
	zynq-zybo-z7.dtb
