obj-$(CONFIG_HAVE_IMX_GPC) += gpc.o
obj-$(CONFIG_IMX7_PM_DOMAINS) += gpcv2.o
obj-$(CONFIG_HAVE_IMX_MU) += mu/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += sc/
obj-$(CONFIG_ARCH_FSL_IMX8QM) += pm-domains.o
obj-$(CONFIG_ARCH_FSL_IMX8MQ) += gpc-psci.o
obj-$(CONFIG_HAVE_IMX_SOC) += soc-imx8.o
