# SPDX-License-Identifier: GPL-2.0-only
ifeq ($(CONFIG_ARM),y)
obj-$(CONFIG_ARCH_MXC) += soc-imx.o
endif
obj-$(CONFIG_SOC_IMX8M) += soc-imx8m.o
obj-$(CONFIG_IMX8M_BUSFREQ) += busfreq-imx8mq.o
obj-$(CONFIG_SOC_IMX9) += imx93-src.o soc-imx9.o
obj-$(CONFIG_IMX9_LPM_CTRL) += imx93_lpm.o
obj-${CONFIG_SECVIO_SC} += secvio/
obj-$(CONFIG_RPMSG_LIFE_CYCLE) += rpmsg_life_cycle.o
obj-$(CONFIG_IMX8M_PM_DOMAINS) += imx8m_pm_domains.o
obj-$(CONFIG_IMX8ULP_LPM_CTRL) += imx8ulp_lpm.o
