# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_ANLOGIC_DR1_CRU)		+= anlogic-dr1-cru.o
anlogic-dr1-cru-y			+= cru_dr1.o

obj-$(CONFIG_ANLOGIC_DR1V90_CRU)	+= anlogic-dr1v90-cru.o
anlogic-dr1v90-cru-y			+= cru-dr1v90.o
