// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (c) 2023-2025, Analog Devices Incorporated, All Rights Reserved
 */
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_TRAFFIC_MAP_MEMMAP_H_
#define _MACSEC_TOP_TRAFFIC_MAP_MEMMAP_H_

/* Rules for Tx/Rx traffic mapping table */
#define TRAFFIC_MAP_BASE_ADDR                                                                                 0x00000800
#define TRAFFIC_MAP_STRIDE                                                                                    0x00000100
/******************************************************************************/
/* Control and status indicator for rule / configuration insert */
#define TRAFFIC_MAP_TT_CTRL_BASE_ADDR                                                                         0x00000000
/* RD_TRIGGER W1C Trigger a read operation */
#define TRAFFIC_MAP_TT_CTRL_RD_TRIGGER_MASK                                                                   0x00010000
#define TRAFFIC_MAP_TT_CTRL_RD_TRIGGER_SHIFT                                                                          16

/* WR_TRIGGER W1C Trigger a write operation */
#define TRAFFIC_MAP_TT_CTRL_WR_TRIGGER_MASK                                                                   0x00008000
#define TRAFFIC_MAP_TT_CTRL_WR_TRIGGER_SHIFT                                                                          15

/* RX_CONFIG_EN RW Select Rx table */
#define TRAFFIC_MAP_TT_CTRL_RX_CONFIG_EN_MASK                                                                 0x00004000
#define TRAFFIC_MAP_TT_CTRL_RX_CONFIG_EN_SHIFT                                                                        14

/* TX_CONFIG_EN RW Select Tx table */
#define TRAFFIC_MAP_TT_CTRL_TX_CONFIG_EN_MASK                                                                 0x00002000
#define TRAFFIC_MAP_TT_CTRL_TX_CONFIG_EN_SHIFT                                                                        13

/* FIELD_SELECT_WR RW Each bit asserted high means the following field to be performed
 * [0] - Destination MAC address
 * [1] - VLAN
 * [2] - Ethertype
 * [3] - Other */
#define TRAFFIC_MAP_TT_CTRL_FIELD_SELECT_WR_MASK                                                              0x00001e00
#define TRAFFIC_MAP_TT_CTRL_FIELD_SELECT_WR_SHIFT                                                                      9

/* INDEX RW Index number of rule to read/write */
#define TRAFFIC_MAP_TT_CTRL_INDEX_MASK                                                                        0x000001ff
#define TRAFFIC_MAP_TT_CTRL_INDEX_SHIFT                                                                                0

/******************************************************************************/
/* First 4-bytes of a mac address to insert */
#define TRAFFIC_MAP_TT_MAC_ADDR_0_WR_BASE_ADDR                                                                0x00000004
/* VAL RW Most significant bytes of the MAC address. */
#define TRAFFIC_MAP_TT_MAC_ADDR_0_WR_VAL_MASK                                                                 0xffffffff
#define TRAFFIC_MAP_TT_MAC_ADDR_0_WR_VAL_SHIFT                                                                         0

/******************************************************************************/
/* Second part of the MAC address to insert */
#define TRAFFIC_MAP_TT_MAC_ADDR_1_WR_BASE_ADDR                                                                0x00000008
/* VAL RW Least significant bytes of the MAC address. */
#define TRAFFIC_MAP_TT_MAC_ADDR_1_WR_VAL_MASK                                                                 0x0000ffff
#define TRAFFIC_MAP_TT_MAC_ADDR_1_WR_VAL_SHIFT                                                                         0

/******************************************************************************/
/* First 4-bytes of a mac address to read */
#define TRAFFIC_MAP_TT_MAC_ADDR_0_RD_BASE_ADDR                                                                0x0000000c
/* VAL RO Most significant bytes of the MAC address. */
#define TRAFFIC_MAP_TT_MAC_ADDR_0_RD_VAL_MASK                                                                 0xffffffff
#define TRAFFIC_MAP_TT_MAC_ADDR_0_RD_VAL_SHIFT                                                                         0

/******************************************************************************/
/* Second part of the MAC address to read */
#define TRAFFIC_MAP_TT_MAC_ADDR_1_RD_BASE_ADDR                                                                0x00000010
/* VAL RO Least significant bytes of the MAC address. */
#define TRAFFIC_MAP_TT_MAC_ADDR_1_RD_VAL_MASK                                                                 0x0000ffff
#define TRAFFIC_MAP_TT_MAC_ADDR_1_RD_VAL_SHIFT                                                                         0

/******************************************************************************/
/* vlan id to insert */
#define TRAFFIC_MAP_TT_VLAN_WR_BASE_ADDR                                                                      0x00000014
/* VAL RW vlan id */
#define TRAFFIC_MAP_TT_VLAN_WR_VAL_MASK                                                                       0x00000fff
#define TRAFFIC_MAP_TT_VLAN_WR_VAL_SHIFT                                                                               0

/******************************************************************************/
/* vlan id to read */
#define TRAFFIC_MAP_TT_VLAN_RD_BASE_ADDR                                                                      0x00000018
/* VAL RO vlan id */
#define TRAFFIC_MAP_TT_VLAN_RD_VAL_MASK                                                                       0x00000fff
#define TRAFFIC_MAP_TT_VLAN_RD_VAL_SHIFT                                                                               0

/******************************************************************************/
/* ethertype to insert */
#define TRAFFIC_MAP_TT_ETYPE_WR_BASE_ADDR                                                                     0x0000001c
/* VAL RW ethertype */
#define TRAFFIC_MAP_TT_ETYPE_WR_VAL_MASK                                                                      0x0000ffff
#define TRAFFIC_MAP_TT_ETYPE_WR_VAL_SHIFT                                                                              0

/******************************************************************************/
/* ethertype to read */
#define TRAFFIC_MAP_TT_ETYPE_RD_BASE_ADDR                                                                     0x00000020
/* VAL RO ethertype */
#define TRAFFIC_MAP_TT_ETYPE_RD_VAL_MASK                                                                      0x0000ffff
#define TRAFFIC_MAP_TT_ETYPE_RD_VAL_SHIFT                                                                              0

/******************************************************************************/
/* other field rule to insert */
#define TRAFFIC_MAP_TT_OTHER_WR_BASE_ADDR                                                                     0x00000024
/* VAL RW other */
#define TRAFFIC_MAP_TT_OTHER_WR_VAL_MASK                                                                      0x0000ffff
#define TRAFFIC_MAP_TT_OTHER_WR_VAL_SHIFT                                                                              0

/******************************************************************************/
/* other field rule to read */
#define TRAFFIC_MAP_TT_OTHER_RD_BASE_ADDR                                                                     0x00000028
/* VAL RO other */
#define TRAFFIC_MAP_TT_OTHER_RD_VAL_MASK                                                                      0x0000ffff
#define TRAFFIC_MAP_TT_OTHER_RD_VAL_SHIFT                                                                              0

/******************************************************************************/
/* SecY associated to the rule to insert */
#define TRAFFIC_MAP_TT_SECY_WR_BASE_ADDR                                                                      0x0000002c
/* VAL RW Index of SecY */
#define TRAFFIC_MAP_TT_SECY_WR_VAL_MASK                                                                       0x0000001f
#define TRAFFIC_MAP_TT_SECY_WR_VAL_SHIFT                                                                               0

/******************************************************************************/
/* SecY associated to the rule to read */
#define TRAFFIC_MAP_TT_SECY_RD_BASE_ADDR                                                                      0x00000030
/* VAL RO Index of SecY */
#define TRAFFIC_MAP_TT_SECY_RD_VAL_MASK                                                                       0x0000001f
#define TRAFFIC_MAP_TT_SECY_RD_VAL_SHIFT                                                                               0

/******************************************************************************/
/* Each bit asserted high means the following is performed
 * [0] - Destination MAC address
 * [1] - VLAN
 * [2] - Ethertype
 * [3] - Other */
#define TRAFFIC_MAP_TT_FIELD_SELECT_RD_BASE_ADDR                                                              0x00000034
/* VAL RO ---- */
#define TRAFFIC_MAP_TT_FIELD_SELECT_RD_VAL_MASK                                                               0x0000000f
#define TRAFFIC_MAP_TT_FIELD_SELECT_RD_VAL_SHIFT                                                                       0

#endif /* _MACSEC_TOP_TRAFFIC_MAP_MEMMAP_H_ */
