// SPDX-License-Identifier: GPL-2.0
// -----------------------------------------------------------------------------
// Comcores ApS (R) all rights reserved.
//
// *****************************************************************************
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_MACSEC_CORE_MEMMAP_H_
#define _MACSEC_TOP_MACSEC_CORE_MEMMAP_H_

/* Top level register bank */
#define MACSEC_CORE_BASE_ADDR                                                                                 0x00000000
#define MACSEC_CORE_STRIDE                                                                                    0x00000100
/******************************************************************************/
/* Unique IP ID */
#define MACSEC_CORE_IP_ID_BASE_ADDR                                                                           0x00000000
/* IP_ID RO_STATIC IP ID */
#define MACSEC_CORE_IP_ID_IP_ID_MASK                                                                          0xffffffff
#define MACSEC_CORE_IP_ID_IP_ID_SHIFT                                                                                  0

/******************************************************************************/
/* IP version */
#define MACSEC_CORE_IP_VERSION_BASE_ADDR                                                                      0x00000004
/* MAJOR RO_STATIC Incrementing version number */
#define MACSEC_CORE_IP_VERSION_MAJOR_MASK                                                                     0xffff0000
#define MACSEC_CORE_IP_VERSION_MAJOR_SHIFT                                                                            16

/* REVISION RO_STATIC Incrementing revision number */
#define MACSEC_CORE_IP_VERSION_REVISION_MASK                                                                  0x0000ffff
#define MACSEC_CORE_IP_VERSION_REVISION_SHIFT                                                                          0

/******************************************************************************/
/* Static IP configuration - Core */
#define MACSEC_CORE_IP_CAPABILITIES_1_BASE_ADDR                                                               0x00000008
/* NO_OF_PEERS RO_STATIC Maximum number of peers per CA. */
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_PEERS_MASK                                                        0xff000000
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_PEERS_SHIFT                                                               24

/* NO_OF_CS_ENTRIES_RX RO_STATIC Maximum number of supported ciphersuites in ingress. */
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_CS_ENTRIES_RX_MASK                                                0x00ff0000
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_CS_ENTRIES_RX_SHIFT                                                       16

/* NO_OF_CS_ENTRIES_TX RO_STATIC Maximum number of supported ciphersuites in egress. */
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_CS_ENTRIES_TX_MASK                                                0x0000ff00
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_CS_ENTRIES_TX_SHIFT                                                        8

/* NO_OF_SECYS RO_STATIC Maximum number of virtual ports/SecYs instantiated. */
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_SECYS_MASK                                                        0x000000ff
#define MACSEC_CORE_IP_CAPABILITIES_1_NO_OF_SECYS_SHIFT                                                                0

/******************************************************************************/
/* Static IP configuration - Core */
#define MACSEC_CORE_IP_CAPABILITIES_2_BASE_ADDR                                                               0x0000000c
/* CONFIDENTIALITY_OFFSET RO_STATIC Confidentiality offset per SecY */
#define MACSEC_CORE_IP_CAPABILITIES_2_CONFIDENTIALITY_OFFSET_MASK                                             0x0f000000
#define MACSEC_CORE_IP_CAPABILITIES_2_CONFIDENTIALITY_OFFSET_SHIFT                                                    24

/* AVAILABLE_CIPHERSUITES RO_STATIC Available Cipher Suites
 * [0] - AES-GCM-128
 * [1] - AES-GCM-256
 * [2] - AES-GCM-XPN-128
 * [3] - AES-GCM-XPN-256 */
#define MACSEC_CORE_IP_CAPABILITIES_2_AVAILABLE_CIPHERSUITES_MASK                                             0x00f00000
#define MACSEC_CORE_IP_CAPABILITIES_2_AVAILABLE_CIPHERSUITES_SHIFT                                                    20

/* VLAN_IN_CLEAR RO_STATIC Support for Vlan in clear */
#define MACSEC_CORE_IP_CAPABILITIES_2_VLAN_IN_CLEAR_MASK                                                      0x000f0000
#define MACSEC_CORE_IP_CAPABILITIES_2_VLAN_IN_CLEAR_SHIFT                                                             16

/* NO_TT_ENTRIES_RX RO_STATIC Maximum number of rules for traffic mapping table in ingress. */
#define MACSEC_CORE_IP_CAPABILITIES_2_NO_TT_ENTRIES_RX_MASK                                                   0x0000ff00
#define MACSEC_CORE_IP_CAPABILITIES_2_NO_TT_ENTRIES_RX_SHIFT                                                           8

/* NO_TT_ENTRIES_TX RO_STATIC Maximum number of rules for traffic mapping table in egress. */
#define MACSEC_CORE_IP_CAPABILITIES_2_NO_TT_ENTRIES_TX_MASK                                                   0x000000ff
#define MACSEC_CORE_IP_CAPABILITIES_2_NO_TT_ENTRIES_TX_SHIFT                                                           0

/******************************************************************************/
/* AES-GCM-128 Cipher Suite:
 * A globally unique 64-bit (EUI-64) identifier
 * 31 downto 0 */
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_0_BASE_ADDR                                                  0x00000010
/* VAL RO_STATIC ---- */
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_0_VAL_MASK                                                   0xffffffff
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_0_VAL_SHIFT                                                           0

/******************************************************************************/
/* AES-GCM-128 Cipher Suite:
 * A globally unique 64-bit (EUI-64) identifier
 * 63 downto 32 */
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_1_BASE_ADDR                                                  0x00000014
/* VAL RO_STATIC ---- */
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_1_VAL_MASK                                                   0xffffffff
#define MACSEC_CORE_IP_AES_GCM_128_CS_IDENTIFIER_1_VAL_SHIFT                                                           0

/******************************************************************************/
/* AES-GCM-256 Cipher Suite:
 * A globally unique 64-bit (EUI-64) identifier
 * 31 downto 0 */
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_0_BASE_ADDR                                                  0x00000018
/* VAL RO_STATIC ---- */
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_0_VAL_MASK                                                   0xffffffff
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_0_VAL_SHIFT                                                           0

/******************************************************************************/
/* AES-GCM-256 Cipher Suite:
 * A globally unique 64-bit (EUI-64) identifier
 * 63 downto 32 */
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_1_BASE_ADDR                                                  0x0000001c
/* VAL RO_STATIC ---- */
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_1_VAL_MASK                                                   0xffffffff
#define MACSEC_CORE_IP_AES_GCM_256_CS_IDENTIFIER_1_VAL_SHIFT                                                           0

/******************************************************************************/
/* Cipher Suite capabilities */
#define MACSEC_CORE_IP_CS_CAPABILITY_BASE_ADDR                                                                0x00000020
/* ICVLENGTH RO_STATIC Cipher Suite capability:
 * Number of octets in the ICV */
#define MACSEC_CORE_IP_CS_CAPABILITY_ICVLENGTH_MASK                                                           0x000001f0
#define MACSEC_CORE_IP_CS_CAPABILITY_ICVLENGTH_SHIFT                                                                   4

/* CHANGESDATALENGTH RO_STATIC Cipher Suite capability:
 * True if the data length is changed */
#define MACSEC_CORE_IP_CS_CAPABILITY_CHANGESDATALENGTH_MASK                                                   0x00000008
#define MACSEC_CORE_IP_CS_CAPABILITY_CHANGESDATALENGTH_SHIFT                                                           3

/* OFFSETCONFIDENTIALITY RO_STATIC Cipher Suite capability:
 * True if a selectable offset for confidentiality can be provided */
#define MACSEC_CORE_IP_CS_CAPABILITY_OFFSETCONFIDENTIALITY_MASK                                               0x00000004
#define MACSEC_CORE_IP_CS_CAPABILITY_OFFSETCONFIDENTIALITY_SHIFT                                                       2

/* CONFIDENTIALITYPROTECTION RO_STATIC Cipher Suite capability:
 * True if confidentiality with integrity protection can be provided */
#define MACSEC_CORE_IP_CS_CAPABILITY_CONFIDENTIALITYPROTECTION_MASK                                           0x00000002
#define MACSEC_CORE_IP_CS_CAPABILITY_CONFIDENTIALITYPROTECTION_SHIFT                                                   1

/* INTEGRITYPROTECTION RO_STATIC Cipher Suite capability:
 * True if integrity protection without confidentiality can be provided */
#define MACSEC_CORE_IP_CS_CAPABILITY_INTEGRITYPROTECTION_MASK                                                 0x00000001
#define MACSEC_CORE_IP_CS_CAPABILITY_INTEGRITYPROTECTION_SHIFT                                                         0

/******************************************************************************/
/* General core control */
#define MACSEC_CORE_GENERAL_CTRL_BASE_ADDR                                                                    0x00000024
/* COMMONPORT_MAC_OPERATIONAL RW Common Port MAC_Operational status insert */
#define MACSEC_CORE_GENERAL_CTRL_COMMONPORT_MAC_OPERATIONAL_MASK                                              0x00000008
#define MACSEC_CORE_GENERAL_CTRL_COMMONPORT_MAC_OPERATIONAL_SHIFT                                                      3

/* COMMONPORT_MAC_ENABLED RW Common Port MAC_Enabled status insert */
#define MACSEC_CORE_GENERAL_CTRL_COMMONPORT_MAC_ENABLED_MASK                                                  0x00000004
#define MACSEC_CORE_GENERAL_CTRL_COMMONPORT_MAC_ENABLED_SHIFT                                                          2

/* MACSEC_EN RW Enable MACsec protection using Aggregated Controlled Port
 * Disable MACsec: all traffic through Uncontrolled Port
 * Enable MACsec: traffic according to Traffic Mapping Table for Controlled and Uncontrolled Port */
#define MACSEC_CORE_GENERAL_CTRL_MACSEC_EN_MASK                                                               0x00000002
#define MACSEC_CORE_GENERAL_CTRL_MACSEC_EN_SHIFT                                                                       1

/* SOFT_RESET_ALL RW Software reset register for all domains, ACTIVE HIGH software reset */
#define MACSEC_CORE_GENERAL_CTRL_SOFT_RESET_ALL_MASK                                                          0x00000001
#define MACSEC_CORE_GENERAL_CTRL_SOFT_RESET_ALL_SHIFT                                                                  0

/******************************************************************************/
/* Transmit PN threshold for almost PN exhaustion interrupt */
#define MACSEC_CORE_TX_SC_PN_THRESHOLD_BASE_ADDR                                                              0x00000028
/* VAL RW ---- */
#define MACSEC_CORE_TX_SC_PN_THRESHOLD_VAL_MASK                                                               0xffffffff
#define MACSEC_CORE_TX_SC_PN_THRESHOLD_VAL_SHIFT                                                                       0

/******************************************************************************/
/* General core interrupt */
#define MACSEC_CORE_INTERRUPT_BASE_ADDR                                                                       0x0000002c
/* PN_EXHAUSTION W1C pn_exhaustion interrupt */
#define MACSEC_CORE_INTERRUPT_PN_EXHAUSTION_MASK                                                              0xffff0000
#define MACSEC_CORE_INTERRUPT_PN_EXHAUSTION_SHIFT                                                                     16

/* ALMOST_PN_EXHAUSTION W1C almost_pn_exhaustion interrupt */
#define MACSEC_CORE_INTERRUPT_ALMOST_PN_EXHAUSTION_MASK                                                       0x0000ffff
#define MACSEC_CORE_INTERRUPT_ALMOST_PN_EXHAUSTION_SHIFT                                                               0

#endif /* _MACSEC_TOP_MACSEC_CORE_MEMMAP_H_ */
