// SPDX-License-Identifier: GPL-2.0
// -----------------------------------------------------------------------------
// Comcores ApS (R) all rights reserved.
//
// *****************************************************************************
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_TRANSMITSA_MEMMAP_H_
#define _MACSEC_TOP_TRANSMITSA_MEMMAP_H_

/* transmitAssociations */
#define TRANSMITSA_BASE_ADDR                                                                                  0x00000400
#define TRANSMITSA_STRIDE                                                                                     0x00000100
/******************************************************************************/
/* Control and status indicator for rule / configuration insert */
#define TRANSMITSA_TX_SA_CTRL_BASE_ADDR                                                                       0x00000000
/* RD_TRIGGER W1C Trigger a read operation */
#define TRANSMITSA_TX_SA_CTRL_RD_TRIGGER_MASK                                                                 0x00000020
#define TRANSMITSA_TX_SA_CTRL_RD_TRIGGER_SHIFT                                                                         5

/* WR_TRIGGER W1C Trigger a write operation */
#define TRANSMITSA_TX_SA_CTRL_WR_TRIGGER_MASK                                                                 0x00000010
#define TRANSMITSA_TX_SA_CTRL_WR_TRIGGER_SHIFT                                                                         4

/* SECY_INDEX RW Index number of SecY to read/write SA */
#define TRANSMITSA_TX_SA_CTRL_SECY_INDEX_MASK                                                                 0x0000000f
#define TRANSMITSA_TX_SA_CTRL_SECY_INDEX_SHIFT                                                                         0

/******************************************************************************/
/* Transmit SA ID:
 * association number for the SA */
#define TRANSMITSA_TX_SA_AN_BASE_ADDR                                                                         0x00000004
/* VAL RW ---- */
#define TRANSMITSA_TX_SA_AN_VAL_MASK                                                                          0x00000003
#define TRANSMITSA_TX_SA_AN_VAL_SHIFT                                                                                  0

/******************************************************************************/
/* Transmit SA creation:
 * the initial value of Transmit PN (10.5.2) for the SA */
#define TRANSMITSA_TX_SA_NEXT_PN_BASE_ADDR                                                                    0x00000008
/* VAL RW ---- */
#define TRANSMITSA_TX_SA_NEXT_PN_VAL_MASK                                                                     0xffffffff
#define TRANSMITSA_TX_SA_NEXT_PN_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Transmit SA creation:
 * A reference to an SAK that is unchanged for the life of the SA */
#define TRANSMITSA_TX_SA_KEY_INDEX_WR_BASE_ADDR                                                               0x0000000c
/* VAL RW ---- */
#define TRANSMITSA_TX_SA_KEY_INDEX_WR_VAL_MASK                                                                0x00000fff
#define TRANSMITSA_TX_SA_KEY_INDEX_WR_VAL_SHIFT                                                                        0

/******************************************************************************/
/* Transmit SA status:
 * A reference to an SAK that is unchanged for the life of the SA */
#define TRANSMITSA_TX_SA_KEY_INDEX_RD_BASE_ADDR                                                               0x00000010
/* VAL RO ---- */
#define TRANSMITSA_TX_SA_KEY_INDEX_RD_VAL_MASK                                                                0x00000fff
#define TRANSMITSA_TX_SA_KEY_INDEX_RD_VAL_SHIFT                                                                        0

/******************************************************************************/
/* Transmit SA creation and status:
 * if the Current Cipher Suite uses extended packet numbering
 * the SSCI for this transmit SA */
#define TRANSMITSA_TX_SA_SSCI_WR_BASE_ADDR                                                                    0x00000014
/* VAL RW For XPN cipher suites */
#define TRANSMITSA_TX_SA_SSCI_WR_VAL_MASK                                                                     0xffffffff
#define TRANSMITSA_TX_SA_SSCI_WR_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Transmit SA creation and status:
 * if the Current Cipher Suite uses extended packet numbering
 * the SSCI for this transmit SA */
#define TRANSMITSA_TX_SA_SSCI_RD_BASE_ADDR                                                                    0x00000018
/* VAL RO For XPN cipher suites */
#define TRANSMITSA_TX_SA_SSCI_RD_VAL_MASK                                                                     0xffffffff
#define TRANSMITSA_TX_SA_SSCI_RD_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Transmit SA controls configuration */
#define TRANSMITSA_TX_SA_TRANSMITSA_CFG_BASE_ADDR                                                             0x0000001c
/* CONFIDENTIALITY_RD RO Transmit SA creation and status read:
 * True if the SA is to provide confidentiality as well as integrity
 * for transmitted frames */
#define TRANSMITSA_TX_SA_TRANSMITSA_CFG_CONFIDENTIALITY_RD_MASK                                               0x00000002
#define TRANSMITSA_TX_SA_TRANSMITSA_CFG_CONFIDENTIALITY_RD_SHIFT                                                       1

/* CONFIDENTIALITY_WR RW Transmit SA creation and status insert:
 * True if the SA is to provide confidentiality as well as integrity
 * for transmitted frames */
#define TRANSMITSA_TX_SA_TRANSMITSA_CFG_CONFIDENTIALITY_WR_MASK                                               0x00000001
#define TRANSMITSA_TX_SA_TRANSMITSA_CFG_CONFIDENTIALITY_WR_SHIFT                                                       0

/******************************************************************************/
/* Transmit SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 31 downto 0 */
#define TRANSMITSA_TX_SA_SCI_0_RD_BASE_ADDR                                                                   0x00000020
/* VAL RO ---- */
#define TRANSMITSA_TX_SA_SCI_0_RD_VAL_MASK                                                                    0xffffffff
#define TRANSMITSA_TX_SA_SCI_0_RD_VAL_SHIFT                                                                            0

/******************************************************************************/
/* Transmit SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 63 downto 32 */
#define TRANSMITSA_TX_SA_SCI_1_RD_BASE_ADDR                                                                   0x00000024
/* VAL RO ---- */
#define TRANSMITSA_TX_SA_SCI_1_RD_VAL_MASK                                                                    0xffffffff
#define TRANSMITSA_TX_SA_SCI_1_RD_VAL_SHIFT                                                                            0

#endif /* _MACSEC_TOP_TRANSMITSA_MEMMAP_H_ */
