// SPDX-License-Identifier: GPL-2.0
// -----------------------------------------------------------------------------
// Comcores ApS (R) all rights reserved.
//
// *****************************************************************************
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_RECEIVESA_MEMMAP_H_
#define _MACSEC_TOP_RECEIVESA_MEMMAP_H_

/* receiveAssociations */
#define RECEIVESA_BASE_ADDR                                                                                   0x00000600
#define RECEIVESA_STRIDE                                                                                      0x00000100
/******************************************************************************/
/* Control and status indicator for rule / configuration insert */
#define RECEIVESA_RX_SA_CTRL_BASE_ADDR                                                                        0x00000000
/* UPDATE_PN_TRIGGER W1C Trigger a PN update operation */
#define RECEIVESA_RX_SA_CTRL_UPDATE_PN_TRIGGER_MASK                                                           0x00001000
#define RECEIVESA_RX_SA_CTRL_UPDATE_PN_TRIGGER_SHIFT                                                                  12

/* RD_TRIGGER W1C Trigger a read operation */
#define RECEIVESA_RX_SA_CTRL_RD_TRIGGER_MASK                                                                  0x00000800
#define RECEIVESA_RX_SA_CTRL_RD_TRIGGER_SHIFT                                                                         11

/* WR_TRIGGER W1C Trigger a write operation */
#define RECEIVESA_RX_SA_CTRL_WR_TRIGGER_MASK                                                                  0x00000400
#define RECEIVESA_RX_SA_CTRL_WR_TRIGGER_SHIFT                                                                         10

/* PEER_INDEX RW Index number of secy table associated to the peer to read/write peer SA */
#define RECEIVESA_RX_SA_CTRL_PEER_INDEX_MASK                                                                  0x000003f0
#define RECEIVESA_RX_SA_CTRL_PEER_INDEX_SHIFT                                                                          4

/* SECY_INDEX RW Index number of SecY associated to the peer to read/write peer SA */
#define RECEIVESA_RX_SA_CTRL_SECY_INDEX_MASK                                                                  0x0000000f
#define RECEIVESA_RX_SA_CTRL_SECY_INDEX_SHIFT                                                                          0

/******************************************************************************/
/* Receive SA ID:
 * association number for the SA */
#define RECEIVESA_RX_SA_AN_BASE_ADDR                                                                          0x00000004
/* VAL RW ---- */
#define RECEIVESA_RX_SA_AN_VAL_MASK                                                                           0x00000003
#define RECEIVESA_RX_SA_AN_VAL_SHIFT                                                                                   0

/******************************************************************************/
/* Receive SA creation:
 * Initial value of nextPN */
#define RECEIVESA_RX_SA_NEXTPN_BASE_ADDR                                                                      0x00000008
/* VAL RW ---- */
#define RECEIVESA_RX_SA_NEXTPN_VAL_MASK                                                                       0xffffffff
#define RECEIVESA_RX_SA_NEXTPN_VAL_SHIFT                                                                               0

/******************************************************************************/
/* Receive SA creation:
 * Lowest acceptable PN value for a received frame */
#define RECEIVESA_RX_SA_LOWESTPN_BASE_ADDR                                                                    0x0000000c
/* VAL RW ---- */
#define RECEIVESA_RX_SA_LOWESTPN_VAL_MASK                                                                     0xffffffff
#define RECEIVESA_RX_SA_LOWESTPN_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Receive SA creation:
 * A reference to an SAK that is unchanged for the life of the SA */
#define RECEIVESA_RX_SA_KEY_INDEX_WR_BASE_ADDR                                                                0x00000010
/* VAL RW ---- */
#define RECEIVESA_RX_SA_KEY_INDEX_WR_VAL_MASK                                                                 0x00000fff
#define RECEIVESA_RX_SA_KEY_INDEX_WR_VAL_SHIFT                                                                         0

/******************************************************************************/
/* Receive SA status:
 * A reference to an SAK that is unchanged for the life of the SA */
#define RECEIVESA_RX_SA_KEY_INDEX_RD_BASE_ADDR                                                                0x00000014
/* VAL RO ---- */
#define RECEIVESA_RX_SA_KEY_INDEX_RD_VAL_MASK                                                                 0x00000fff
#define RECEIVESA_RX_SA_KEY_INDEX_RD_VAL_SHIFT                                                                         0

/******************************************************************************/
/* Receive SA creation and status insert:
 * If the Current Cipher Suite uses extended packet numbering,
 * the KaY also supplies the SSCI for the SA */
#define RECEIVESA_RX_SA_SSCI_WR_BASE_ADDR                                                                     0x00000018
/* VAL RW For XPN cipher suites */
#define RECEIVESA_RX_SA_SSCI_WR_VAL_MASK                                                                      0xffffffff
#define RECEIVESA_RX_SA_SSCI_WR_VAL_SHIFT                                                                              0

/******************************************************************************/
/* Receive SA creation and status read:
 * If the Current Cipher Suite uses extended packet numbering,
 * the KaY also supplies the SSCI for the SA */
#define RECEIVESA_RX_SA_SSCI_RD_BASE_ADDR                                                                     0x0000001c
/* VAL RO For XPN cipher suites */
#define RECEIVESA_RX_SA_SSCI_RD_VAL_MASK                                                                      0xffffffff
#define RECEIVESA_RX_SA_SSCI_RD_VAL_SHIFT                                                                              0

/******************************************************************************/
/* Receive SA control */
#define RECEIVESA_RX_SA_UPDTNEXTPN_BASE_ADDR                                                                  0x00000020
/* VAL RW ---- */
#define RECEIVESA_RX_SA_UPDTNEXTPN_VAL_MASK                                                                   0xffffffff
#define RECEIVESA_RX_SA_UPDTNEXTPN_VAL_SHIFT                                                                           0

/******************************************************************************/
/* Receive SA control */
#define RECEIVESA_RX_SA_UPDTLOWESTPN_BASE_ADDR                                                                0x00000024
/* VAL RW ---- */
#define RECEIVESA_RX_SA_UPDTLOWESTPN_VAL_MASK                                                                 0xffffffff
#define RECEIVESA_RX_SA_UPDTLOWESTPN_VAL_SHIFT                                                                         0

/******************************************************************************/
/* Receive SA status and configuration */
#define RECEIVESA_RX_SA_RECEIVESA_CFG_BASE_ADDR                                                               0x00000028
/* ENABLERECEIVE_RD RO Receive SA control read:
 * When the SA is created, enableReceive and inUse are False
 * and the SA cannot be used to receive frames. The SA shall
 * be able to receive, and inUse shall be True, when enableReceive
 * is set. The SA shall stop receiving, and inUse shall be False,
 * when enableReceive is reset. */
#define RECEIVESA_RX_SA_RECEIVESA_CFG_ENABLERECEIVE_RD_MASK                                                   0x00000002
#define RECEIVESA_RX_SA_RECEIVESA_CFG_ENABLERECEIVE_RD_SHIFT                                                           1

/* ENABLERECEIVE_WR RW Receive SA control insert:
 * When the SA is created, enableReceive and inUse are False
 * and the SA cannot be used to receive frames. The SA shall
 * be able to receive, and inUse shall be True, when enableReceive
 * is set. The SA shall stop receiving, and inUse shall be False,
 * when enableReceive is reset. */
#define RECEIVESA_RX_SA_RECEIVESA_CFG_ENABLERECEIVE_WR_MASK                                                   0x00000001
#define RECEIVESA_RX_SA_RECEIVESA_CFG_ENABLERECEIVE_WR_SHIFT                                                           0

/******************************************************************************/
/* Receive SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 31 downto 0 */
#define RECEIVESA_RX_SA_SCI_0_RD_BASE_ADDR                                                                    0x0000002c
/* VAL RO ---- */
#define RECEIVESA_RX_SA_SCI_0_RD_VAL_MASK                                                                     0xffffffff
#define RECEIVESA_RX_SA_SCI_0_RD_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Receive SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 63 downto 32 */
#define RECEIVESA_RX_SA_SCI_1_RD_BASE_ADDR                                                                    0x00000030
/* VAL RO ---- */
#define RECEIVESA_RX_SA_SCI_1_RD_VAL_MASK                                                                     0xffffffff
#define RECEIVESA_RX_SA_SCI_1_RD_VAL_SHIFT                                                                             0

#endif /* _MACSEC_TOP_RECEIVESA_MEMMAP_H_ */
