// SPDX-License-Identifier: GPL-2.0
// -----------------------------------------------------------------------------
// Comcores ApS (R) all rights reserved.
//
// *****************************************************************************
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_SECY_CONFIG_MEMMAP_H_
#define _MACSEC_TOP_SECY_CONFIG_MEMMAP_H_

/* Configuration registers per SecY */
#define SECY_CONFIG_BASE_ADDR                                                                                 0x00000100
#define SECY_CONFIG_STRIDE                                                                                    0x00000100
/******************************************************************************/
/* Control and status indicator for configuration insert */
#define SECY_CONFIG_CONFIG_CTRL_BASE_ADDR                                                                     0x00000000
/* CIPHERSUITE_CONFIG_EN RW Select Ciphersuite registers */
#define SECY_CONFIG_CONFIG_CTRL_CIPHERSUITE_CONFIG_EN_MASK                                                    0x00000200
#define SECY_CONFIG_CONFIG_CTRL_CIPHERSUITE_CONFIG_EN_SHIFT                                                            9

/* RX_CONFIG_EN RW Select Frame Verification and Validation registers */
#define SECY_CONFIG_CONFIG_CTRL_RX_CONFIG_EN_MASK                                                             0x00000100
#define SECY_CONFIG_CONFIG_CTRL_RX_CONFIG_EN_SHIFT                                                                     8

/* TX_CONFIG_EN RW Select Frame Generation and Protection registers */
#define SECY_CONFIG_CONFIG_CTRL_TX_CONFIG_EN_MASK                                                             0x00000080
#define SECY_CONFIG_CONFIG_CTRL_TX_CONFIG_EN_SHIFT                                                                     7

/* PORT_CONFIG_EN RW Select Provided Interface registers */
#define SECY_CONFIG_CONFIG_CTRL_PORT_CONFIG_EN_MASK                                                           0x00000040
#define SECY_CONFIG_CONFIG_CTRL_PORT_CONFIG_EN_SHIFT                                                                   6

/* RD_TRIGGER W1C Trigger a read operation */
#define SECY_CONFIG_CONFIG_CTRL_RD_TRIGGER_MASK                                                               0x00000020
#define SECY_CONFIG_CONFIG_CTRL_RD_TRIGGER_SHIFT                                                                       5

/* WR_TRIGGER W1C Trigger a write operation */
#define SECY_CONFIG_CONFIG_CTRL_WR_TRIGGER_MASK                                                               0x00000010
#define SECY_CONFIG_CONFIG_CTRL_WR_TRIGGER_SHIFT                                                                       4

/* SECY_INDEX RW Index number of SecY to read/write */
#define SECY_CONFIG_CONFIG_CTRL_SECY_INDEX_MASK                                                               0x0000000f
#define SECY_CONFIG_CONFIG_CTRL_SECY_INDEX_SHIFT                                                                       0

/******************************************************************************/
/* Provided Interface registers for controlled port:
 * 1) ControlledPortEnabled
 * 2) vlan-in-clear
 * 3) max_frame_lenght */
#define SECY_CONFIG_PORT_CONFIG_BASE_ADDR                                                                     0x00000004
/* VLANINCLEAR_RD RO Status of vlan-in-clear enable for SecY */
#define SECY_CONFIG_PORT_CONFIG_VLANINCLEAR_RD_MASK                                                           0x00000008
#define SECY_CONFIG_PORT_CONFIG_VLANINCLEAR_RD_SHIFT                                                                   3

/* VLANINCLEAR_WR RW vlan-in-clear enable for SecY */
#define SECY_CONFIG_PORT_CONFIG_VLANINCLEAR_WR_MASK                                                           0x00000004
#define SECY_CONFIG_PORT_CONFIG_VLANINCLEAR_WR_SHIFT                                                                   2

/* CONTROLLEDPORTENABLED_RD RO Controlled Port control read:
 * False: the KaY can prohibit use of the Controlled Port until the secure
 * connectivity required has been configured */
#define SECY_CONFIG_PORT_CONFIG_CONTROLLEDPORTENABLED_RD_MASK                                                 0x00000002
#define SECY_CONFIG_PORT_CONFIG_CONTROLLEDPORTENABLED_RD_SHIFT                                                         1

/* CONTROLLEDPORTENABLED_WR RW Controlled Port control insert:
 * False: the KaY can prohibit use of the Controlled Port until the secure
 * connectivity required has been configured */
#define SECY_CONFIG_PORT_CONFIG_CONTROLLEDPORTENABLED_WR_MASK                                                 0x00000001
#define SECY_CONFIG_PORT_CONFIG_CONTROLLEDPORTENABLED_WR_SHIFT                                                         0

/******************************************************************************/
/* Frame Generation and Protection read registers */
#define SECY_CONFIG_TX_CONFIG_BASE_ADDR                                                                       0x00000008
/* USESCB_RD RO Frame generation controls read:
 * True or False, with a default of False */
#define SECY_CONFIG_TX_CONFIG_USESCB_RD_MASK                                                                  0x00020000
#define SECY_CONFIG_TX_CONFIG_USESCB_RD_SHIFT                                                                         17

/* USESCB_WR RW Frame generation controls insert:
 * True or False, with a default of False */
#define SECY_CONFIG_TX_CONFIG_USESCB_WR_MASK                                                                  0x00010000
#define SECY_CONFIG_TX_CONFIG_USESCB_WR_SHIFT                                                                         16

/* USEES_RD RO Frame generation controls read:
 * True or False, with a default of False */
#define SECY_CONFIG_TX_CONFIG_USEES_RD_MASK                                                                   0x00008000
#define SECY_CONFIG_TX_CONFIG_USEES_RD_SHIFT                                                                          15

/* USEES_WR RW Frame generation controls insert:
 * True or False, with a default of False */
#define SECY_CONFIG_TX_CONFIG_USEES_WR_MASK                                                                   0x00004000
#define SECY_CONFIG_TX_CONFIG_USEES_WR_SHIFT                                                                          14

/* ALWAYSINCLUDESCI_RD RO Frame generation controls read:
 * True or False, with a default of False */
#define SECY_CONFIG_TX_CONFIG_ALWAYSINCLUDESCI_RD_MASK                                                        0x00002000
#define SECY_CONFIG_TX_CONFIG_ALWAYSINCLUDESCI_RD_SHIFT                                                               13

/* ALWAYSINCLUDESCI_WR RW Frame generation controls insert:
 * True or False, with a default of False
 * In Tx, SCI explicit (included in SecTAG) when: G_NO_OF_SECYS=1 and alwaysIncludeSCI=1, or G_NO_OF_SECYS>1 */
#define SECY_CONFIG_TX_CONFIG_ALWAYSINCLUDESCI_WR_MASK                                                        0x00001000
#define SECY_CONFIG_TX_CONFIG_ALWAYSINCLUDESCI_WR_SHIFT                                                               12

/* PROTECTFRAMES_RD RO Frame generation controls read:
 * True or False, with a default of True */
#define SECY_CONFIG_TX_CONFIG_PROTECTFRAMES_RD_MASK                                                           0x00000800
#define SECY_CONFIG_TX_CONFIG_PROTECTFRAMES_RD_SHIFT                                                                  11

/* PROTECTFRAMES_WR RW Frame generation controls insert:
 * True or False, with a default of True */
#define SECY_CONFIG_TX_CONFIG_PROTECTFRAMES_WR_MASK                                                           0x00000400
#define SECY_CONFIG_TX_CONFIG_PROTECTFRAMES_WR_SHIFT                                                                  10

/* MAXTRANSMITKEYS RO Maximum number of keys in simultaneous use for transmission */
#define SECY_CONFIG_TX_CONFIG_MAXTRANSMITKEYS_MASK                                                            0x000003f0
#define SECY_CONFIG_TX_CONFIG_MAXTRANSMITKEYS_SHIFT                                                                    4

/* MAXTRANSMITCHANNELS RO Maximum number of transmit channels */
#define SECY_CONFIG_TX_CONFIG_MAXTRANSMITCHANNELS_MASK                                                        0x0000000f
#define SECY_CONFIG_TX_CONFIG_MAXTRANSMITCHANNELS_SHIFT                                                                0

/******************************************************************************/
/* Frame Verification and Validation read registers */
#define SECY_CONFIG_RX_CONFIG_BASE_ADDR                                                                       0x0000000c
/* REPLAYPROTECT_RD RO Frame verification controls rd
 * Values:
 * True or False, with a default of True */
#define SECY_CONFIG_RX_CONFIG_REPLAYPROTECT_RD_MASK                                                           0x00020000
#define SECY_CONFIG_RX_CONFIG_REPLAYPROTECT_RD_SHIFT                                                                  17

/* REPLAYPROTECT_WR RW Frame verification controls insert
 * Values:
 * True or False, with a default of True */
#define SECY_CONFIG_RX_CONFIG_REPLAYPROTECT_WR_MASK                                                           0x00010000
#define SECY_CONFIG_RX_CONFIG_REPLAYPROTECT_WR_SHIFT                                                                  16

/* VALIDATEFRAMES_RD RO Frame verification controls read
 * Values:
 * 0x0: Null,
 * 0x1: Disabled,
 * 0x2: Check, or
 * 0x3: Strict, with a default of Strict */
#define SECY_CONFIG_RX_CONFIG_VALIDATEFRAMES_RD_MASK                                                          0x0000c000
#define SECY_CONFIG_RX_CONFIG_VALIDATEFRAMES_RD_SHIFT                                                                 14

/* VALIDATEFRAMES_WR RW Frame verification controls insert
 * Values:
 * 0x0: Null,
 * 0x1: Disabled,
 * 0x2: Check, or
 * 0x3: Strict, with a default of Strict */
#define SECY_CONFIG_RX_CONFIG_VALIDATEFRAMES_WR_MASK                                                          0x00003000
#define SECY_CONFIG_RX_CONFIG_VALIDATEFRAMES_WR_SHIFT                                                                 12

/* MAXRECEIVEKEYS RO Frame verification capabilities.
 * Maximum number of keys in simultaneous use for reception */
#define SECY_CONFIG_RX_CONFIG_MAXRECEIVEKEYS_MASK                                                             0x00000fc0
#define SECY_CONFIG_RX_CONFIG_MAXRECEIVEKEYS_SHIFT                                                                     6

/* MAXRECEIVECHANNELS RO Frame verification capabilities.
 * Maximum number of receive channels */
#define SECY_CONFIG_RX_CONFIG_MAXRECEIVECHANNELS_MASK                                                         0x0000003f
#define SECY_CONFIG_RX_CONFIG_MAXRECEIVECHANNELS_SHIFT                                                                 0

/******************************************************************************/
/* Frame verification controls insert
 * Values:
 * Between 0 and 232-1, with a default of 0 */
#define SECY_CONFIG_RX_REPLAYWINDOW_WR_BASE_ADDR                                                              0x00000010
/* VAL RW ---- */
#define SECY_CONFIG_RX_REPLAYWINDOW_WR_VAL_MASK                                                               0xffffffff
#define SECY_CONFIG_RX_REPLAYWINDOW_WR_VAL_SHIFT                                                                       0

/******************************************************************************/
/* Frame verification controls insert
 * Values:
 * Between 0 and 232-1, with a default of 0 */
#define SECY_CONFIG_RX_REPLAYWINDOW_RD_BASE_ADDR                                                              0x00000014
/* VAL RO ---- */
#define SECY_CONFIG_RX_REPLAYWINDOW_RD_VAL_MASK                                                               0xffffffff
#define SECY_CONFIG_RX_REPLAYWINDOW_RD_VAL_SHIFT                                                                       0

/******************************************************************************/
/* Cipher Suite configuration for SecY */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_BASE_ADDR                                                              0x00000018
/* CONFIDENTIALITYOFFSET_RD RO Cipher Suite selection read:
 * Number of initial octets of each MSDU without confidentiality protection */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CONFIDENTIALITYOFFSET_RD_MASK                                          0x000fe000
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CONFIDENTIALITYOFFSET_RD_SHIFT                                                 13

/* CONFIDENTIALITYOFFSET_WR RW Cipher Suite selection insert:
 * Number of initial octets of each MSDU without confidentiality protection */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CONFIDENTIALITYOFFSET_WR_MASK                                          0x00001fc0
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CONFIDENTIALITYOFFSET_WR_SHIFT                                                  6

/* CURRENTCIPHERSUITE_RD RO Cipher Suite selection:
 * The Cipher Suite Identifier (10.7.25) for the cipher suite
 * 0x0: AES-GCM-128
 * 0x1: AES-GCM-256
 * 0x2: AES-GCM-XPN-128
 * 0x3: AES-GCM-XPN-256 */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CURRENTCIPHERSUITE_RD_MASK                                             0x00000030
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CURRENTCIPHERSUITE_RD_SHIFT                                                     4

/* CURRENTCIPHERSUITE_WR RW Cipher Suite selection:
 * The Cipher Suite Identifier (10.7.25) for the cipher suite
 * 0x0: AES-GCM-128
 * 0x1: AES-GCM-256
 * 0x2: AES-GCM-XPN-128
 * 0x3: AES-GCM-XPN-256 */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CURRENTCIPHERSUITE_WR_MASK                                             0x0000000c
#define SECY_CONFIG_CIPHERSUITE_CONFIG_CURRENTCIPHERSUITE_WR_SHIFT                                                     2

/* REQUIRECONFIDENTIALITY_RD RO Cipher Suite use read:
 * True if the Cipher Suite can only be used to provide both
 * confidentiality and integrity (and not integrity only, or
 * confidentiality with an offset) */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_REQUIRECONFIDENTIALITY_RD_MASK                                         0x00000002
#define SECY_CONFIG_CIPHERSUITE_CONFIG_REQUIRECONFIDENTIALITY_RD_SHIFT                                                 1

/* REQUIRECONFIDENTIALITY_WR RW Cipher Suite use insert:
 * True if the Cipher Suite can only be used to provide both
 * confidentiality and integrity (and not integrity only, or
 * confidentiality with an offset) */
#define SECY_CONFIG_CIPHERSUITE_CONFIG_REQUIRECONFIDENTIALITY_WR_MASK                                         0x00000001
#define SECY_CONFIG_CIPHERSUITE_CONFIG_REQUIRECONFIDENTIALITY_WR_SHIFT                                                 0

/******************************************************************************/
/* Max frame lenght to transmit */
#define SECY_CONFIG_MAX_FRAME_LENGHT_WR_BASE_ADDR                                                             0x0000001c
/* VAL RW ---- */
#define SECY_CONFIG_MAX_FRAME_LENGHT_WR_VAL_MASK                                                              0x0000ffff
#define SECY_CONFIG_MAX_FRAME_LENGHT_WR_VAL_SHIFT                                                                      0

/******************************************************************************/
/* Max frame lenght to transmit */
#define SECY_CONFIG_MAX_FRAME_LENGHT_RD_BASE_ADDR                                                             0x00000020
/* VAL RO ---- */
#define SECY_CONFIG_MAX_FRAME_LENGHT_RD_VAL_MASK                                                              0x0000ffff
#define SECY_CONFIG_MAX_FRAME_LENGHT_RD_VAL_SHIFT                                                                      0

#endif /* _MACSEC_TOP_SECY_CONFIG_MEMMAP_H_ */
