// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (c) 2023-2025, Analog Devices Incorporated, All Rights Reserved
 */
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_CIPHERSUITE_MEMMAP_H_
#define _MACSEC_TOP_CIPHERSUITE_MEMMAP_H_

/* Cipher Suite capability, control and status */
#define CIPHERSUITE_BASE_ADDR                                                                                 0x00000700
#define CIPHERSUITE_STRIDE                                                                                    0x00000100
/******************************************************************************/
/* Control and status indicator for rule / configuration insert */
#define CIPHERSUITE_CS_CTRL_BASE_ADDR                                                                         0x00000000
/* WR_TRIGGER W1C Trigger a write operation */
#define CIPHERSUITE_CS_CTRL_WR_TRIGGER_MASK                                                                   0x00010000
#define CIPHERSUITE_CS_CTRL_WR_TRIGGER_SHIFT                                                                          16

/* AES_MODE_SEL RW Cipher Suite selection:
 * The Cipher Suite Identifier (10.7.25) for the cipher suite
 * 0x0: AES-GCM-128
 * 0x1: AES-GCM-256
 * 0x2: AES-GCM-XPN-128
 * 0x3: AES-GCM-XPN-256 */
#define CIPHERSUITE_CS_CTRL_AES_MODE_SEL_MASK                                                                 0x0000c000
#define CIPHERSUITE_CS_CTRL_AES_MODE_SEL_SHIFT                                                                        14

/* RECEIVE_SEL RW Rx key table selection insert
 * SAK creation:
 * True if the key is to be installed for reception */
#define CIPHERSUITE_CS_CTRL_RECEIVE_SEL_MASK                                                                  0x00002000
#define CIPHERSUITE_CS_CTRL_RECEIVE_SEL_SHIFT                                                                         13

/* TRANSMIT_SEL RW Tx key table selection insert
 * SAK creation:
 * True if the key is to be installed for transmission */
#define CIPHERSUITE_CS_CTRL_TRANSMIT_SEL_MASK                                                                 0x00001000
#define CIPHERSUITE_CS_CTRL_TRANSMIT_SEL_SHIFT                                                                        12

/* INDEX RW Index number of key to read/write */
#define CIPHERSUITE_CS_CTRL_INDEX_MASK                                                                        0x00000fff
#define CIPHERSUITE_CS_CTRL_INDEX_SHIFT                                                                                0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 31 downto 0 */
#define CIPHERSUITE_CS_SAK_0_BASE_ADDR                                                                        0x00000004
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_0_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_0_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 63 downto 32 */
#define CIPHERSUITE_CS_SAK_1_BASE_ADDR                                                                        0x00000008
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_1_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_1_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 95 downto 64 */
#define CIPHERSUITE_CS_SAK_2_BASE_ADDR                                                                        0x0000000c
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_2_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_2_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 127 downto 96 */
#define CIPHERSUITE_CS_SAK_3_BASE_ADDR                                                                        0x00000010
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_3_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_3_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 159 downto 128 */
#define CIPHERSUITE_CS_SAK_4_BASE_ADDR                                                                        0x00000014
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_4_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_4_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 191 downto 160 */
#define CIPHERSUITE_CS_SAK_5_BASE_ADDR                                                                        0x00000018
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_5_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_5_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 223 downto 192 */
#define CIPHERSUITE_CS_SAK_6_BASE_ADDR                                                                        0x0000001c
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_6_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_6_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation:
 * The SAK value
 * 255 downto 224 */
#define CIPHERSUITE_CS_SAK_7_BASE_ADDR                                                                        0x00000020
/* VAL RW ---- */
#define CIPHERSUITE_CS_SAK_7_VAL_MASK                                                                         0xffffffff
#define CIPHERSUITE_CS_SAK_7_VAL_SHIFT                                                                                 0

/******************************************************************************/
/* SAK creation insert:
 * If the Current Cipher Suite uses extended packet numbering,
 * Salt (McGrew [B11]), a 96-bit parameter provided to the Current
 * Cipher Suite for subsequent protection and validation operations
 * 32 downto 0 */
#define CIPHERSUITE_CS_SALT_0_BASE_ADDR                                                                       0x00000024
/* VAL RW ---- */
#define CIPHERSUITE_CS_SALT_0_VAL_MASK                                                                        0xffffffff
#define CIPHERSUITE_CS_SALT_0_VAL_SHIFT                                                                                0

/******************************************************************************/
/* SAK creation insert:
 * If the Current Cipher Suite uses extended packet numbering,
 * Salt (McGrew [B11]), a 96-bit parameter provided to the Current
 * Cipher Suite for subsequent protection and validation operations
 * 63 downto 32 */
#define CIPHERSUITE_CS_SALT_1_BASE_ADDR                                                                       0x00000028
/* VAL RW ---- */
#define CIPHERSUITE_CS_SALT_1_VAL_MASK                                                                        0xffffffff
#define CIPHERSUITE_CS_SALT_1_VAL_SHIFT                                                                                0

/******************************************************************************/
/* SAK creation insert:
 * If the Current Cipher Suite uses extended packet numbering,
 * Salt (McGrew [B11]), a 96-bit parameter provided to the Current
 * Cipher Suite for subsequent protection and validation operations
 * 95 downto 64 */
#define CIPHERSUITE_CS_SALT_2_BASE_ADDR                                                                       0x0000002c
/* VAL RW ---- */
#define CIPHERSUITE_CS_SALT_2_VAL_MASK                                                                        0xffffffff
#define CIPHERSUITE_CS_SALT_2_VAL_SHIFT                                                                                0

#endif /* _MACSEC_TOP_CIPHERSUITE_MEMMAP_H_ */
