// SPDX-License-Identifier: GPL-2.0
// -----------------------------------------------------------------------------
// Comcores ApS (R) all rights reserved.
//
// *****************************************************************************
/******************************************************************************/
/*                                DO NOT MODIFY                               */
/*           THIS FILE IS AUTOGENERATED AND ALL CHANGES WILL BE LOST          */
/******************************************************************************/
#ifndef _MACSEC_TOP_RECEIVESC_MEMMAP_H_
#define _MACSEC_TOP_RECEIVESC_MEMMAP_H_

/* receiveChannels */
#define RECEIVESC_BASE_ADDR                                                                                   0x00000500
#define RECEIVESC_STRIDE                                                                                      0x00000100
/******************************************************************************/
/* Control and status indicator for rule / configuration insert */
#define RECEIVESC_RX_SC_CTRL_BASE_ADDR                                                                        0x00000000
/* RD_TRIGGER W1C Trigger a read operation */
#define RECEIVESC_RX_SC_CTRL_RD_TRIGGER_MASK                                                                  0x00000800
#define RECEIVESC_RX_SC_CTRL_RD_TRIGGER_SHIFT                                                                         11

/* WR_TRIGGER W1C Trigger a write operation */
#define RECEIVESC_RX_SC_CTRL_WR_TRIGGER_MASK                                                                  0x00000400
#define RECEIVESC_RX_SC_CTRL_WR_TRIGGER_SHIFT                                                                         10

/* PEER_INDEX RW Index number of secy table to read/write peer SCI */
#define RECEIVESC_RX_SC_CTRL_PEER_INDEX_MASK                                                                  0x000003f0
#define RECEIVESC_RX_SC_CTRL_PEER_INDEX_SHIFT                                                                          4

/* SECY_INDEX RW Index number of SecY to read/write peer SCI */
#define RECEIVESC_RX_SC_CTRL_SECY_INDEX_MASK                                                                  0x0000000f
#define RECEIVESC_RX_SC_CTRL_SECY_INDEX_SHIFT                                                                          0

/******************************************************************************/
/* Receive SC ID to insert
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 31 downto 0 */
#define RECEIVESC_RX_SC_SCI_0_WR_BASE_ADDR                                                                    0x00000004
/* VAL RW ---- */
#define RECEIVESC_RX_SC_SCI_0_WR_VAL_MASK                                                                     0xffffffff
#define RECEIVESC_RX_SC_SCI_0_WR_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Receive SC ID to insert
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 63 downto 32 */
#define RECEIVESC_RX_SC_SCI_1_WR_BASE_ADDR                                                                    0x00000008
/* VAL RW ---- */
#define RECEIVESC_RX_SC_SCI_1_WR_VAL_MASK                                                                     0xffffffff
#define RECEIVESC_RX_SC_SCI_1_WR_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Receive SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 31 downto 0 */
#define RECEIVESC_RX_SC_SCI_0_RD_BASE_ADDR                                                                    0x0000000c
/* VAL RO ---- */
#define RECEIVESC_RX_SC_SCI_0_RD_VAL_MASK                                                                     0xffffffff
#define RECEIVESC_RX_SC_SCI_0_RD_VAL_SHIFT                                                                             0

/******************************************************************************/
/* Receive SC ID to read
 * Each SC has a unique SCI comprising a 48-bit MAC address
 * concatenated with a 16-bit Port Identifier
 * 63 downto 32 */
#define RECEIVESC_RX_SC_SCI_1_RD_BASE_ADDR                                                                    0x00000010
/* VAL RO ---- */
#define RECEIVESC_RX_SC_SCI_1_RD_VAL_MASK                                                                     0xffffffff
#define RECEIVESC_RX_SC_SCI_1_RD_VAL_SHIFT                                                                             0

#endif /* _MACSEC_TOP_RECEIVESC_MEMMAP_H_ */
