obj-$(CONFIG_FB_MX8_HDMI) += \
	API_Audio.o \
	API_AVI.o \
	API_AFE.o \
	API_AFE_t28hpc_hdmitx.o \
	API_General.o \
	API_HDCP.o \
	API_HDMI_Audio.o \
	API_HDMITX.o \
	API_Infoframe.o \
	edid_parser.o \
	test_base_sw.o \
	util.o \
	vic_table.o
