blank_issues_enabled: false
contact_links:
  - name: "⛔ Question"
    url: https://forums.raspberrypi.com
    about: "Please do not use GitHub for asking questions. If you simply have a question, then the Raspberry Pi forums are the best place to ask it. Thanks in advance for helping us keep the issue tracker clean!"
  - name: "⛔ Problems with Raspberry Pi OS packages"
    url: https://github.com/RPi-Distro/repo
    about: "If you have problems with a Raspberry Pi OS package, please report them at https://github.com/RPi-Distro/repo."

