#
# Makefile for the AXI4 drivers.
#

obj-$(CONFIG_MATHWORKS_IP_CORE) += mathworks_ip_common.o
obj-$(CONFIG_MATHWORKS_GENERIC_OF) += mathworks_generic_of.o
obj-$(CONFIG_MATHWORKS_GENERIC_PCI) += mathworks_generic_pci.o

obj-$(CONFIG_MWIPCORE) += mwipcore.o

mwipcore-objs := mwadma.o

