#
# Makefile for the AXI4 drivers.
#

obj-$(CONFIG_MWGENERIC) += mwgeneric_common.o
obj-$(CONFIG_MWGENERIC_OF) += mwgeneric_of.o
obj-$(CONFIG_MWGENERIC_PCI) += mwgeneric_pci.o

obj-$(CONFIG_MWIPCORE) += mwipcore.o mwadma.o


