obj-$(CONFIG_IMX_DPU_CORE) += imx-dpu-core.o

imx-dpu-core-objs := dpu-common.o dpu-constframe.o dpu-disengcfg.o \
		     dpu-extdst.o dpu-fetchdecode.o dpu-fetcheco.o \
		     dpu-framegen.o dpu-fetchlayer.o dpu-hscaler.o \
		     dpu-layerblend.o dpu-tcon.o dpu-vscaler.o
