obj-$(CONFIG_MXC_HANTRO) += hantro/
obj-$(CONFIG_MXC_HANTRO_845) += hantro_845/
obj-$(CONFIG_MXC_HANTRO_845_H1) += hantro_845_h1/
obj-$(CONFIG_MXC_HANTRO_VC8000E) += hantro_vc8000e/
obj-$(CONFIG_MXC_HANTRO_V4L2) += hantro_v4l2/
obj-$(CONFIG_MXC_VPU) += vpu/
