snd-soc-xilinx-pcm-objs := xilinx-pcm.o
snd-soc-axi-spdif-objs := axi-spdif.o
snd-soc-adv7511-hdmi-objs := adv7511_hdmi.o

obj-$(CONFIG_SND_SOC_XILINX) += snd-soc-xilinx-pcm.o
obj-$(CONFIG_SND_SOC_AXI_SPDIF) += snd-soc-axi-spdif.o
obj-$(CONFIG_SND_SOC_ADV7511_HDMI) += snd-soc-adv7511-hdmi.o
