# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2026 Meta Platforms, Inc. and affiliates
# Copyright (c) 2026 Breno Leitao <leitao@debian.org>

CFLAGS += -Wall -Werror
TEST_GEN_PROGS := configfs_test

include ../../lib.mk
