/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_BINDINGS_AIROHA_SCU_SSR_H
#define __DT_BINDINGS_AIROHA_SCU_SSR_H

#define AIROHA_SCU_SERDES_PCIE1		0
#define AIROHA_SCU_SERDES_PCIE2		1
#define AIROHA_SCU_SERDES_USB1		2
#define AIROHA_SCU_SERDES_USB2		3

#endif /* __DT_BINDINGS_AIROHA_SCU_SSR_H */
