# SPDX-License-Identifier: BSD-2-Clause-Views
# Copyright (c) 2019-2023 The Regents of the University of California

obj-$(CONFIG_MQNIC) += mqnic.o

mqnic-objs += mqnic_main.o mqnic_res.o mqnic_reg_block.o mqnic_irq.o mqnic_dev.o mqnic_if.o mqnic_port.o mqnic_netdev.o mqnic_sched_block.o mqnic_scheduler.o mqnic_ptp.o mqnic_i2c.o mqnic_board.o mqnic_clk_info.o mqnic_stats.o mqnic_tx.o mqnic_rx.o mqnic_cq.o mqnic_eq.o mqnic_ethtool.o

