# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Industrial I/O Generic Regmap Access Drivers
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_IIO_REGMAP) += iio-regmap.o
obj-$(CONFIG_IIO_REGMAP_I2C) += iio-regmap-i2c.o
obj-$(CONFIG_IIO_REGMAP_SPI) += iio-regmap-spi.o
