# SPDX-License-Identifier: GPL-2.0+
#
# Makefile for the JESD204 core.
#

obj-$(CONFIG_JESD204) += jesd204.o
jesd204-y := \
	jesd204-fsm.o \
	jesd204-sysfs.o \
	jesd204-core.o

obj-$(CONFIG_JESD204_TOP_DEVICE) += jesd204_top_device.o
