obj-$(CONFIG_IMX8_PRG)	+= imx8_prg.o
obj-$(CONFIG_IMX8_DPRC)	+= imx8_dprc.o

obj-$(CONFIG_IMX_IPUV3_CORE)	+= ipu-v3/
obj-$(CONFIG_IMX_DPU_CORE)	+= dpu/
obj-$(CONFIG_IMX_DPU_BLIT)      += dpu-blit/
obj-$(CONFIG_IMX_DCSS_CORE)	+= dcss/
obj-$(CONFIG_IMX_LCDIF_CORE)	+= lcdif/
