mxc-capture-objs := mxc-isi-core.o mxc-isi-cap.o mxc-isi-hw.o mxc-isi-m2m.o

obj-$(CONFIG_IMX8_CAPTURE_DRIVER) += mxc-capture.o
obj-$(CONFIG_IMX8_MIPI_CSI2) += mxc-mipi-csi2.o
obj-$(CONFIG_IMX8_PARALLEL_CSI) += mxc-parallel-csi.o
obj-$(CONFIG_IMX8_MIPI_CSI2_YAV) += mxc-mipi-csi2_yav.o
ov5640_camera_v3-objs := ov5640_v3.o
obj-$(CONFIG_MXC_CAMERA_OV5640_V3) += ov5640_camera_v3.o
obj-$(CONFIG_MXC_CAMERA_OV5640_MIPI_V3) += ov5640_mipi_v3.o
max9286_gmsl-objs := max9286.o
obj-$(CONFIG_GMSL_MAX9286) += max9286_gmsl.o
obj-$(CONFIG_IMX8_MEDIA_DEVICE) += mxc-media-dev.o
obj-$(CONFIG_IMX8_JPEG) += mxc-jpeg-hw.o mxc-jpeg.o
obj-$(CONFIG_IMX8_HDMI_RX) += hdmi/
