mxc-capture-objs := mxc-isi-core.o mxc-isi-cap.o mxc-isi-hw.o

obj-$(CONFIG_IMX8_CAPTURE_DRIVER) += mxc-capture.o
obj-$(CONFIG_IMX8_MIPI_CSI2) += mxc-mipi-csi2.o
max9286_gmsl-objs := max9286.o
obj-$(CONFIG_GMSL_MAX9286) += max9286_gmsl.o
obj-$(CONFIG_IMX8_MEDIA_DEVICE) += mxc-media-dev.o
obj-$(CONFIG_IMX8_JPEG) += mxc-jpeg-hw.o mxc-jpeg.o
