# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)

obj-y := core.o spu.o
obj-$(CONFIG_ARCH_SC57X) += sc57x-ezkit.o
obj-$(CONFIG_ARCH_SC58X) += sc58x-ezkit.o
obj-$(CONFIG_ARCH_SC59X) += sc59x-ezkit.o
