
#ifndef _DT_BINDINGS_ADI_AD5592R_H
#define _DT_BINDINGS_ADI_AD5592R_H


#define CH_MODE_ADC			1
#define CH_MODE_DAC			2
#define CH_MODE_DAC_AND_ADC		3
#define CH_MODE_UNUSED_PULL_DOWN	4
#define CH_MODE_UNUSED_OUT_LOW		5
#define CH_MODE_UNUSED_OUT_HIGH		6
#define CH_MODE_UNUSED_OUT_TRISTATE	7
#define CH_MODE_GPIO			8
#define CH_MODE_GPIO_OPEN_DRAIN		9

#endif /* _DT_BINDINGS_ADI_AD5592R_H */
