# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)
dtb-$(CONFIG_ARCH_SC59X_64) += sc598-som-ezkit.dtb sc598-som-ezkit-sd.dtb sc598-som-ezlite.dtb sc598-htol.dtb
dtb-$(CONFIG_ARCH_SC84X) += sc846-som.dtb sc846-som-ezkit.dtb sc846-som-ezkit-adema127.dtb
