# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ADRV906X) += adrv906x-denali-4.dtb
dtb-$(CONFIG_ARCH_ADRV906X) += adrv906x-denali-8.dtb
dtb-$(CONFIG_ARCH_ADRV906X) += adrv906x-titan-4.dtb
dtb-$(CONFIG_ARCH_ADRV906X) += adrv906x-titan-8.dtb
dtb-$(CONFIG_ARCH_ADRV906X) += adrv906x-secondary.dtb
