#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

analogdrm-y := analog_drm_encoder.o analog_drm_crtc.o analog_drm_drv.o \
	analog_drm_gem.o analog_drm_fbdev.o

obj-y += analogdrm.o
