/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES */
#ifndef __KICK_TEST_H__
#define __KICK_TEST_H__

enum kick_scenario {
	KICK_IMMEDIATE,
	KICK_LAZY,
	KICK_LAZY_THEN_IMMEDIATE,
	KICK_IMMEDIATE_THEN_LAZY,
	KICK_PLAIN_THEN_LAZY,
	KICK_LAZY_THEN_PLAIN,
	KICK_BOTH,
	KICK_LAZY_WAIT,
	ENQ_BOTH,
	TICK_EXPIRY,
	INVALID_KICK_IDLE,
	INVALID_KICK_UNKNOWN,
};

enum kick_state {
	KICK_STATE_IDLE,
	KICK_STATE_ARMED,
	KICK_STATE_QUEUED,
	KICK_STATE_RESCHED,
	KICK_STATE_DONE,
};

#endif /* __KICK_TEST_H__ */
