// SPDX-License-Identifier: GPL-2.0-only
/*
 * (C) Copyright 2022 - Analog Devices Inc.
 *
 * ADSP SC5XX clock device tree bindings
 *
 * This header defines the clocks that the ADSP-SC5XX
 * clock controllers provide.
 *
 * Author: Qasim Ijaz <qasim.ijaz@analog.com>
 */

#ifndef DT_BINDINGS_CLOCK_ADI_SC5XX_CLOCK_H
#define DT_BINDINGS_CLOCK_ADI_SC5XX_CLOCK_H

/* CGU0 and CGU1 clocks common to SC5xx SoCs */
#define ADSP_SC5XX_CLK_CGU_DF_DIV	0
#define ADSP_SC5XX_CLK_CGU_PLLCLK	1
#define ADSP_SC5XX_CLK_CGU_CSEL_DIV	2
#define ADSP_SC5XX_CLK_CGU_SYSSEL_DIV	3
#define ADSP_SC5XX_CLK_CGU_DSEL_DIV	4
#define ADSP_SC5XX_CLK_CGU_OSEL_DIV	5
#define ADSP_SC5XX_CLK_CGU_CCLK0_GATE	6
#define ADSP_SC5XX_CLK_CGU_S0SEL_DIV	7
#define ADSP_SC5XX_CLK_CGU_S1SEL_DIV	8
#define ADSP_SC5XX_CLK_CGU_DCLK_GATE	9
#define ADSP_SC5XX_CLK_CGU_OCLK_GATE		10
#define ADSP_SC5XX_CLK_CGU_SCLK1_GATE	11
#define ADSP_SC5XX_CLK_CGU_SCLK0_GATE	12
#define ADSP_SC5XX_CLK_CGU_VCO_OUT	13

/* ADSP-SC598 CGU0 and CGU1 clocks */
#define ADSP_SC598_CLK_CGU_DCLK_HALF 	14
#define ADSP_SC598_CLK_CGU_S1SELEX_DIV	15
#define ADSP_SC598_CLK_CGU_CCLK2	16
#define ADSP_SC598_CLK_CGU_S1SELEXEN	17

/* ADSP-SC598 CGU1 clocks */
#define ADSP_SC598_CLK_CGU_SCLK_HALF	18
#define ADSP_SC598_CLK_CGU_S0SELEX_DIV	19
#define ADSP_SC598_CLK_CGU_S0SELEXNEN	20

/* ADSP-SC58X CGU0 and CGU1 clocks */
#define ADSP_SC58X_CLK_CGU_CCLK1	14

/* ADSP-SC58X CGU0 clocks */
#define ADSP_SC58X_CLK_CGU_OCLK_HALF	15

/* ADSP-SC58X CGU1 clocks */
#define ADSP_SC58X_CLK_CGU_CCLK1_1_HALF	15

/* ADSP-SC57X CGU0 and CGU1 clocks */
#define ADSP_SC57X_CLK_CGU_CCLK1	14

/* ADSP-SC57X CGU0 clocks */
#define ADSP_SC57X_CLK_CGU_OCLK0_HALF	15

/* ADSP-SC57X CGU1 clocks */
#define ADSP_SC57X_CLK_CGU_CCLK1_1_HALF	15

/* ADSP-SC594 CGU0 and CGU1 clocks */
#define ADSP_SC594_CLK_CGU_CCLK1	14
#define ADSP_SC594_CLK_CGU_S1SELEXEN	15
#define ADSP_SC594_CLK_CGU_S1SELEX_DIV	16

/* CDU clocks common to SC5xx SoCs */
#define ADSP_SC5XX_CLK_CDU_SHARC0	0
#define ADSP_SC5XX_CLK_CDU_SHARC1	1
#define ADSP_SC5XX_CLK_CDU_ARM		2
#define ADSP_SC5XX_CLK_CDU_CLKINSEL	3
#define ADSP_SC5XX_CLK_CDU_CAN		4
#define ADSP_SC5XX_CLK_CDU_SPDIF	5
#define ADSP_SC5XX_CLK_CDU_GIGE		6
#define ADSP_SC5XX_CLK_CDU_DDR		7

/* ADSP-SC594 CDU clocks */
#define ADSP_SC594_CLK_CDU_SPI		8
#define ADSP_SC594_CLK_CDU_LP		9
#define ADSP_SC594_CLK_CDU_LPDDR	10
#define ADSP_SC594_CLK_CDU_OSPI_REFCLK	11
#define ADSP_SC594_CLK_CDU_TRACE	12

/* ADSP-SC598 CDU clocks */
#define ADSP_SC598_CLK_CDU_SPI		  	8
#define ADSP_SC598_CLK_CDU_LP		  	9
#define ADSP_SC598_CLK_CDU_LPDDR	  	10
#define ADSP_SC598_CLK_CDU_OSPI_REFCLK	  	11
#define ADSP_SC598_CLK_CDU_EMMC_TIMER_QMC	12
#define ADSP_SC598_CLK_CDU_EMMC		  	13
#define ADSP_SC598_CLK_CDU_TRACE		14

/* ADSP-SC58X CDU clocks */
#define ADSP_SC58X_CLK_CDU_RESERVED		8
#define ADSP_SC58X_CLK_CDU_LP			9
#define ADSP_SC58X_CLK_CDU_SDIO			10

/* ADSP-SC57X CDU clocks */
#define ADSP_SC57X_CLK_CDU_SDIO			8

/* ADSP-SC598 PLL2 clocks */
#define ADSP_SC598_CLK_PLL2_DF_DIV		0
#define ADSP_SC598_CLK_PLL2_VCO_OUT		1
#define ADSP_SC598_CLK_PLL2_PLLCLK		2
#define ADSP_SC598_CLK_PLL2_DDIV		3
#define ADSP_SC598_CLK_DDR			4

#endif	/* DT_BINDINGS_CLOCK_ADI_SC5XX_CLOCK_H */
