/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright 2018 NXP
 *   Dong Aisheng <aisheng.dong@nxp.com>
 */

#ifndef __DT_BINDINGS_CLOCK_IMX_H
#define __DT_BINDINGS_CLOCK_IMX_H

/* LPCG clocks */

#define IMX_ADMA_ACM_AUD_CLK0_SEL			0
#define IMX_ADMA_ACM_AUD_CLK1_SEL			1
#define IMX_ADMA_ACM_MCLKOUT0_SEL			2
#define IMX_ADMA_ACM_MCLKOUT1_SEL			3
#define IMX_ADMA_ACM_ESAI0_MCLK_SEL			4
#define IMX_ADMA_ACM_ESAI1_MCLK_SEL			5
#define IMX_ADMA_ACM_GPT0_MUX_CLK_SEL			6
#define IMX_ADMA_ACM_GPT1_MUX_CLK_SEL			7
#define IMX_ADMA_ACM_GPT2_MUX_CLK_SEL			8
#define IMX_ADMA_ACM_GPT3_MUX_CLK_SEL			9
#define IMX_ADMA_ACM_GPT4_MUX_CLK_SEL			10
#define IMX_ADMA_ACM_GPT5_MUX_CLK_SEL			11
#define IMX_ADMA_ACM_SAI0_MCLK_SEL			12
#define IMX_ADMA_ACM_SAI1_MCLK_SEL			13
#define IMX_ADMA_ACM_SAI2_MCLK_SEL			14
#define IMX_ADMA_ACM_SAI3_MCLK_SEL			15
#define IMX_ADMA_ACM_SAI4_MCLK_SEL			16
#define IMX_ADMA_ACM_SAI5_MCLK_SEL			17
#define IMX_ADMA_ACM_SAI6_MCLK_SEL			18
#define IMX_ADMA_ACM_SAI7_MCLK_SEL			19
#define IMX_ADMA_ACM_SPDIF0_TX_CLK_SEL			20
#define IMX_ADMA_ACM_SPDIF1_TX_CLK_SEL			21
#define IMX_ADMA_ACM_MQS_TX_CLK_SEL			22
#define IMX_ADMA_ACM_ASRC0_MUX_CLK_SEL			23
#define IMX_ADMA_ACM_ASRC1_MUX_CLK_SEL			24

#define IMX_ADMA_ACM_CLK_END				25

#endif /* __DT_BINDINGS_CLOCK_IMX_H */
