# SPDX-License-Identifier: GPL-2.0+
# Copyright 2023 NXP
#

obj-$(CONFIG_NEUTRON) = neutron.o

neutron-objs := neutron_driver.o \
		neutron_device.o \
		neutron_buffer.o \
		neutron_inference.o \
		neutron_mailbox.o
