obj-$(CONFIG_M2K_LOGIC_ANALYZER) += m2k-logic-analyzer.o
obj-$(CONFIG_M2K_LOGIC_ANALYZER) += m2k-fabric.o
obj-$(CONFIG_M2K_LOGIC_ANALYZER) += m2k-trigger-ad.o
obj-$(CONFIG_AXI_AION_TRIG) += axi_aion_trig.o