
obj-$(CONFIG_A2B) += a2b-core.o a2b-of.o a2b-io.o a2b-misc.o a2b-irq.o a2b-sysfs.o
obj-$(CONFIG_A2B) += a2b-mailbox.o

obj-$(CONFIG_AD2428) += ad2428-i2c.o
obj-$(CONFIG_AD2428) += ad2428-a2b.o
obj-$(CONFIG_AD2428) += ad2428-common.o
