// SPDX-License-Identifier: GPL-2.0-only
/*
 * Clock distribution unit (CDU) CCF support for Analog
 * Devices ADSP SoCs.
 *
 * Copyright (C) 2026 Analog Devices Inc.
 *
 * The CDU provides the gateable peripheral clocks of the
 * SoC. For each peripheral clock, a CDU mux controls which
 * CGU clock it is to be derived from.
 *
 * The CDU is made up of multiple multiplexers that select
 * clocks generated from the CGU (Clock Generation Unit).
 * After being generated by the CGU, the clocks are divided
 * down via upstream divider clocks and routed to the CDU.
 * Each multiplexer across the CDU has 4 clock input sources
 * (some of which are grounded/not selectable) as well as
 * multiplexer gating functionality.
 *
 * Root clock	    CGU				CDU
 * 		  +------+ ..		+------------------+
 *		  |+---+ | --> CCLK --> | [ ] [x] [ ] [ ]  | --> ARM core
 * SYS_CLKINx --> ||PLL| | ..		| [ ] [ ] [x] [ ]  | --> SHARC core
 *		  |+---+ | --> DCLK --> | [x] [ ] [ ] [ ]  | --> DDR
 *		  |	 | --> SCLK --> | [ ] [ ] [ ] [x]  | --> EMMC
 *		  +------+ ..		+------------------+
 */

#include <dt-bindings/clock/adi,adsp-sc573-cdu.h>
#include <dt-bindings/clock/adi,adsp-sc589-cdu.h>
#include <dt-bindings/clock/adi,adsp-sc594-cdu.h>
#include <dt-bindings/clock/adi,adsp-sc598-cdu.h>
#include <linux/bitfield.h>
#include <linux/bits.h>
#include <linux/clk-provider.h>
#include <linux/debugfs.h>
#include <linux/device.h>
#include <linux/err.h>
#include <linux/io.h>
#include <linux/iopoll.h>
#include <linux/module.h>
#include <linux/of_device.h>
#include <linux/platform_device.h>
#include <linux/seq_file.h>
#include <linux/slab.h>
#include <linux/spinlock.h>

#include "clk.h"

#define IN0_CLKON       0x0
#define IN1_CLKON       0x1
#define IN2_CLKON       0x2
#define IN3_CLKON       0x3

#define CDU_CLKO0       0x0
#define CDU_CLKO1       0x1
#define CDU_CLKO2       0x2
#define CDU_CLKO3       0x3
#define CDU_CLKO4       0x4
#define CDU_CLKO5       0x5
#define CDU_CLKO6       0x6
#define CDU_CLKO7       0x7
#define CDU_CLKO8       0x8
#define CDU_CLKO9       0x9
#define CDU_CLKO10      0xA
#define CDU_CLKO12      0xC
#define CDU_CLKO13      0xD
#define CDU_CLKO14      0xE

#define PDATA(_name)	\
	static const struct clk_parent_data _name[]

#define MUX_TABLE(_name)	\
	static const u32 _name[]

#define ADSP_CDU_CLK_FLAGS	\
	(CLK_SET_RATE_PARENT | CLK_OPS_PARENT_ENABLE)

#define ADSP_CDU_CLK_FLAGS_CRITICAL	\
	(ADSP_CDU_CLK_FLAGS | CLK_IS_CRITICAL)

#define ADSP_CDU_CFG(n)		((n) * sizeof(u32))

#define ADSP_CDU_LOCK		BIT(31)

#define ADSP_CDU_CLKINSEL	0x44
#define ADSP_CDU_CLKINSEL_CGU1	BIT(0)

#define ADSP_CDU_STAT		0x40
#define ADSP_CDU_STAT_LWERR	BIT(17)
#define ADSP_CDU_STAT_ADRERR	BIT(16)

#define ADSP_CDU_CFG_EN		BIT(0)
#define ADSP_CDU_CFG_SEL	GENMASK(2, 1)

#define ADSP_CDU_REVID		0x48
#define ADSP_CDU_REVID_MAJOR	GENMASK(7, 4)
#define ADSP_CDU_REVID_REV	GENMASK(3, 0)

#define ADSP_CDU_POLL_DELAY	5
#define ADSP_CDU_POLL_TIMEOUT	50

/**
 * struct adsp_cdu_clks - information about cdu clock
 * @parent_data: parent clock descriptions used by CCF
 * @mux_table: input clock SEL table for this clock
 * @clock_name: name of this clock
 * @clock_flags: common clock framework flags for this clock
 * @id: clock provider onecell identifier
 * @cdu_clko: the CDU CLKO bit
 * @num_parents: number of entries in @parent_data
 */
struct adsp_cdu_clks {
	const struct clk_parent_data	*parent_data;
	const u32			*mux_table;
	const char			*clock_name;
	unsigned long			clock_flags;
	unsigned int			id;
	u8				cdu_clko;
	u8				num_parents;
};

#define CDU(_id, _parents, _mux, _name, _flags, _clko)	\
	{							\
		.id		= _id,				\
		.parent_data	= _parents,			\
		.mux_table	= _mux,				\
		.clock_name	= _name,			\
		.clock_flags	= _flags,			\
		.cdu_clko	= _clko,			\
		.num_parents	= ARRAY_SIZE(_parents),		\
	}

/**
 * struct adsp_cdu_match_data - SoC specific CDU clock data
 * @clks: array of CDU clock descriptions for the SoC
 * @num_clks: number of entries in @clks
 * @reserved_mask: mask of non configurable CDU outputs
 * @has_clkin: indication if CDU has CLKINSEL clock
 */
struct adsp_cdu_match_data {
	const struct adsp_cdu_clks	*clks;
	unsigned int			num_clks;
	unsigned int			reserved_mask;
	bool				has_clkin;
};

/* CDU CLKOn input clock source configurations */
MUX_TABLE(CDU_CLKO_SEL1)	= { IN0_CLKON };
MUX_TABLE(CDU_CLKO_SEL2)	= { IN1_CLKON };
MUX_TABLE(CDU_CLKO_SEL3)	= { IN0_CLKON, IN1_CLKON };
MUX_TABLE(CDU_CLKO_SEL4)	= { IN0_CLKON, IN1_CLKON, IN2_CLKON };
MUX_TABLE(CDU_CLKO_SEL5)	= { IN0_CLKON, IN2_CLKON, IN3_CLKON };
MUX_TABLE(CDU_CLKO_SEL6)	= { IN0_CLKON, IN1_CLKON, IN2_CLKON, IN3_CLKON };

/* ADSP-SC573 and ADSP-SC589 common CDU parents */
PDATA(sc589_573_cdu_sharc_parents)	= { { .fw_name = "cclk0_0"  }, { .fw_name = "sysclk_0"  }, };
PDATA(sc589_573_cdu_arm_parents)	= { { .fw_name = "cclk1_0"  }, { .fw_name = "sysclk_0"  }, };
PDATA(sc589_573_cdu_ddr_parents)	= { { .fw_name = "dclk_0"   }, { .fw_name = "dclk_1"    }, };
PDATA(sc589_573_cdu_spdif_parents)	= { { .fw_name = "oclk_0"   }, { .fw_name = "oclk_1"    },
					    { .fw_name = "dclk_1"   }, { .fw_name = "dclk_0"    }, };
PDATA(sc589_573_cdu_gige_parents)	= { { .fw_name = "sclk1_0"  }, { .fw_name = "sclk1_1"   },
					    { .fw_name = "cclk0_1"  }, { .fw_name = "oclk_0"    }, };
PDATA(sc589_573_cdu_sdio_parents)	= { { .fw_name = "oclk_0/2" }, { .fw_name = "cclk1_1/2" },
					    { .fw_name = "cclk1_1"  }, { .fw_name = "dclk_1"    }, };

/* ADSP-SC573 CDU parents */
PDATA(sc573_cdu_can_parents)		= { { .fw_name = "oclk_0" }, { .fw_name = "oclk_1"   },
					    { .fw_name = "dclk_1" }, { .fw_name = "oclk_0/2" }, };

/* ADSP-SC589 CDU parents */
PDATA(sc589_cdu_can_parents)		= { { .fw_name = "oclk_0"  }, { .fw_name = "oclk_1"  },
					    { .fw_name = "dclk_1"  }, };
PDATA(sc589_cdu_reserved_parents)	= { { .fw_name = "oclk_0"  }, { .fw_name = "cclk0_1" }, };
PDATA(sc589_cdu_lp_parents)		= { { .fw_name = "sclk0_0" }, { .fw_name = "sclk0_1" },
					    { .fw_name = "cclk1_1" }, { .fw_name = "dclk_1"  }, };

/* ADSP-SC594 and ADSP-SC598 common CDU parents */
PDATA(sc59x_cdu_sharc_parents)		= { { .fw_name = "cclk0_0"  }, };
PDATA(sc59x_cdu_ddr_parents)		= { { .fw_name = "dclk_0"   }, { .fw_name = "dclk_1"  }, };
PDATA(sc59x_cdu_spdif_parents)		= { { .fw_name = "sclk1_0"  }, };
PDATA(sc59x_cdu_spi_parents)		= { { .fw_name = "sclk0_0"  }, { .fw_name = "oclk_0"  }, };
PDATA(sc59x_cdu_lp_parents)		= { { .fw_name = "oclk_0"   }, { .fw_name = "sclk0_0" },
					    { .fw_name = "cclk0_1"  }, };
PDATA(sc59x_cdu_lpddr_parents)		= { { .fw_name = "oclk_0"   }, { .fw_name = "dclk_0"  },
					    { .fw_name = "sysclk_1" }, };
PDATA(sc59x_cdu_ospi_refclk_parents)	= { { .fw_name = "sysclk_0" }, { .fw_name = "sclk0_0" },
					    { .fw_name = "sclk1_1"  }, };
PDATA(sc59x_cdu_trace_parents)		= { { .fw_name = "sclk0_0"  }, };

/* ADSP-SC594 CDU parents */
PDATA(sc594_cdu_arm_parents)		= { { .fw_name = "cclk1_0" }, };
PDATA(sc594_cdu_can_parents)		= { { .fw_name = "oclk_0"  }, { .fw_name = "oclk_1"  }, };
PDATA(sc594_cdu_gige_parents)		= { { .fw_name = "sclk0_0" }, { .fw_name = "sclk0_1" }, };

/* ADSP-SC598 CDU parents */
PDATA(sc598_cdu_arm_parents)		= { { .fw_name = "cclk1_0"   }, { .fw_name = "cclk2_0"  },
					    { .fw_name = "cclk2_1"   }, };
PDATA(sc598_cdu_can_parents)		= { { .fw_name = "oclk_1"    }, };
PDATA(sc598_cdu_gige_parents)		= { { .fw_name = "sclk0_0"   }, { .fw_name = "sclk0_1"  },
					    { .fw_name = "oclk_0"    }, };
PDATA(sc598_cdu_emmc_parents)		= { { .fw_name = "oclk_0"    }, { .fw_name = "sclk0_1"  },
					    { .fw_name = "dclk_0/2"  }, { .fw_name = "dclk_1/2" }, };
PDATA(sc598_cdu_emmc_timer_parents)	= { { .fw_name = "sclk1_1/2" }, };

/* ADSP CLKINSEL parents */
PDATA(adsp_clkinsel_parents)		= { { .fw_name = "sys_clkin0" }, { .fw_name = "sys_clkin1" } };

static const struct adsp_cdu_clks sc573_mux_clks[] = {
	CDU(ADSP_SC573_CLK_CDU_SHARC0, sc589_573_cdu_sharc_parents,
		CDU_CLKO_SEL3, "cdu_sharc0", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO0),
	CDU(ADSP_SC573_CLK_CDU_SHARC1, sc589_573_cdu_sharc_parents,
		CDU_CLKO_SEL3, "cdu_sharc1", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO1),
	CDU(ADSP_SC573_CLK_CDU_ARM, sc589_573_cdu_arm_parents,
		CDU_CLKO_SEL3, "cdu_arm", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO2),
	CDU(ADSP_SC573_CLK_CDU_DDR, sc589_573_cdu_ddr_parents,
		CDU_CLKO_SEL3, "cdu_ddr", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO3),
	CDU(ADSP_SC573_CLK_CDU_CAN, sc573_cdu_can_parents,
		CDU_CLKO_SEL6, "cdu_can", ADSP_CDU_CLK_FLAGS, CDU_CLKO4),
	CDU(ADSP_SC573_CLK_CDU_SPDIF, sc589_573_cdu_spdif_parents,
		CDU_CLKO_SEL6, "cdu_spdif", ADSP_CDU_CLK_FLAGS, CDU_CLKO5),
	CDU(ADSP_SC573_CLK_CDU_GIGE, sc589_573_cdu_gige_parents,
		CDU_CLKO_SEL6, "cdu_gige", ADSP_CDU_CLK_FLAGS, CDU_CLKO7),
	CDU(ADSP_SC573_CLK_CDU_SDIO, sc589_573_cdu_sdio_parents,
		CDU_CLKO_SEL6, "cdu_sdio", ADSP_CDU_CLK_FLAGS, CDU_CLKO9),
};

static const struct adsp_cdu_clks sc589_mux_clks[] = {
	CDU(ADSP_SC589_CLK_CDU_SHARC0, sc589_573_cdu_sharc_parents,
		CDU_CLKO_SEL3, "cdu_sharc0", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO0),
	CDU(ADSP_SC589_CLK_CDU_SHARC1, sc589_573_cdu_sharc_parents,
		CDU_CLKO_SEL3, "cdu_sharc1", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO1),
	CDU(ADSP_SC589_CLK_CDU_ARM, sc589_573_cdu_arm_parents,
		CDU_CLKO_SEL3, "cdu_arm", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO2),
	CDU(ADSP_SC589_CLK_CDU_DDR, sc589_573_cdu_ddr_parents,
		CDU_CLKO_SEL3, "cdu_ddr", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO3),
	CDU(ADSP_SC589_CLK_CDU_CAN, sc589_cdu_can_parents,
		CDU_CLKO_SEL4, "cdu_can", ADSP_CDU_CLK_FLAGS, CDU_CLKO4),
	CDU(ADSP_SC589_CLK_CDU_SPDIF, sc589_573_cdu_spdif_parents,
		CDU_CLKO_SEL6, "cdu_spdif", ADSP_CDU_CLK_FLAGS, CDU_CLKO5),
	CDU(ADSP_SC589_CLK_CDU_RESERVED, sc589_cdu_reserved_parents,
		CDU_CLKO_SEL3, "cdu_reserved", ADSP_CDU_CLK_FLAGS, CDU_CLKO6),
	CDU(ADSP_SC589_CLK_CDU_GIGE, sc589_573_cdu_gige_parents,
		CDU_CLKO_SEL6, "cdu_gige", ADSP_CDU_CLK_FLAGS, CDU_CLKO7),
	CDU(ADSP_SC589_CLK_CDU_LP, sc589_cdu_lp_parents,
		CDU_CLKO_SEL6, "cdu_lp", ADSP_CDU_CLK_FLAGS, CDU_CLKO8),
	CDU(ADSP_SC589_CLK_CDU_SDIO, sc589_573_cdu_sdio_parents,
		CDU_CLKO_SEL6, "cdu_sdio", ADSP_CDU_CLK_FLAGS, CDU_CLKO9),
};

static const struct adsp_cdu_clks sc594_mux_clks[] = {
	CDU(ADSP_SC594_CLK_CDU_SHARC0, sc59x_cdu_sharc_parents,
		CDU_CLKO_SEL1, "cdu_sharc0", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO0),
	CDU(ADSP_SC594_CLK_CDU_SHARC1, sc59x_cdu_sharc_parents,
		CDU_CLKO_SEL1, "cdu_sharc1", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO1),
	CDU(ADSP_SC594_CLK_CDU_ARM, sc594_cdu_arm_parents,
		CDU_CLKO_SEL1, "cdu_arm", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO2),
	CDU(ADSP_SC594_CLK_CDU_DDR, sc59x_cdu_ddr_parents,
		CDU_CLKO_SEL3, "cdu_ddr", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO3),
	CDU(ADSP_SC594_CLK_CDU_CAN, sc594_cdu_can_parents,
		CDU_CLKO_SEL3, "cdu_can", ADSP_CDU_CLK_FLAGS, CDU_CLKO4),
	CDU(ADSP_SC594_CLK_CDU_SPDIF, sc59x_cdu_spdif_parents,
		CDU_CLKO_SEL1, "cdu_spdif", ADSP_CDU_CLK_FLAGS, CDU_CLKO5),
	CDU(ADSP_SC594_CLK_CDU_SPI, sc59x_cdu_spi_parents,
		CDU_CLKO_SEL3, "cdu_spi", ADSP_CDU_CLK_FLAGS, CDU_CLKO6),
	CDU(ADSP_SC594_CLK_CDU_GIGE, sc594_cdu_gige_parents,
		CDU_CLKO_SEL3, "cdu_gige", ADSP_CDU_CLK_FLAGS, CDU_CLKO7),
	CDU(ADSP_SC594_CLK_CDU_LP, sc59x_cdu_lp_parents,
		CDU_CLKO_SEL4, "cdu_lp", ADSP_CDU_CLK_FLAGS, CDU_CLKO8),
	CDU(ADSP_SC594_CLK_CDU_LPDDR, sc59x_cdu_lpddr_parents,
		CDU_CLKO_SEL4, "cdu_lpddr", ADSP_CDU_CLK_FLAGS, CDU_CLKO9),
	CDU(ADSP_SC594_CLK_CDU_OSPI_REFCLK, sc59x_cdu_ospi_refclk_parents,
		CDU_CLKO_SEL4, "cdu_ospi_refclk", ADSP_CDU_CLK_FLAGS, CDU_CLKO10),
	CDU(ADSP_SC594_CLK_CDU_TRACE, sc59x_cdu_trace_parents,
		CDU_CLKO_SEL1, "cdu_trace", ADSP_CDU_CLK_FLAGS, CDU_CLKO12),
};

static const struct adsp_cdu_clks sc598_mux_clks[] = {
	CDU(ADSP_SC598_CLK_CDU_SHARC0, sc59x_cdu_sharc_parents,
		CDU_CLKO_SEL1, "cdu_sharc0", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO0),
	CDU(ADSP_SC598_CLK_CDU_SHARC1, sc59x_cdu_sharc_parents,
		CDU_CLKO_SEL1, "cdu_sharc1", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO1),
	CDU(ADSP_SC598_CLK_CDU_ARM, sc598_cdu_arm_parents,
		CDU_CLKO_SEL5, "cdu_arm", ADSP_CDU_CLK_FLAGS_CRITICAL, CDU_CLKO2),
	CDU(ADSP_SC598_CLK_CDU_DDR, sc59x_cdu_ddr_parents,
		CDU_CLKO_SEL3, "cdu_ddr", ADSP_CDU_CLK_FLAGS, CDU_CLKO3),
	CDU(ADSP_SC598_CLK_CDU_CAN, sc598_cdu_can_parents,
		CDU_CLKO_SEL2, "cdu_can", ADSP_CDU_CLK_FLAGS, CDU_CLKO4),
	CDU(ADSP_SC598_CLK_CDU_SPDIF, sc59x_cdu_spdif_parents,
		CDU_CLKO_SEL1, "cdu_spdif", ADSP_CDU_CLK_FLAGS, CDU_CLKO5),
	CDU(ADSP_SC598_CLK_CDU_SPI, sc59x_cdu_spi_parents,
		CDU_CLKO_SEL3, "cdu_spi", ADSP_CDU_CLK_FLAGS, CDU_CLKO6),
	CDU(ADSP_SC598_CLK_CDU_GIGE, sc598_cdu_gige_parents,
		CDU_CLKO_SEL4, "cdu_gige", ADSP_CDU_CLK_FLAGS, CDU_CLKO7),
	CDU(ADSP_SC598_CLK_CDU_LP, sc59x_cdu_lp_parents,
		CDU_CLKO_SEL4, "cdu_lp", ADSP_CDU_CLK_FLAGS, CDU_CLKO8),
	CDU(ADSP_SC598_CLK_CDU_LPDDR, sc59x_cdu_lpddr_parents,
		CDU_CLKO_SEL4, "cdu_lpddr", ADSP_CDU_CLK_FLAGS, CDU_CLKO9),
	CDU(ADSP_SC598_CLK_CDU_OSPI_REFCLK, sc59x_cdu_ospi_refclk_parents,
		CDU_CLKO_SEL4, "cdu_ospi_refclk", ADSP_CDU_CLK_FLAGS, CDU_CLKO10),
	CDU(ADSP_SC598_CLK_CDU_TRACE, sc59x_cdu_trace_parents,
		CDU_CLKO_SEL1, "cdu_trace", ADSP_CDU_CLK_FLAGS, CDU_CLKO12),
	CDU(ADSP_SC598_CLK_CDU_EMMC, sc598_cdu_emmc_parents,
		CDU_CLKO_SEL6, "cdu_emmc", ADSP_CDU_CLK_FLAGS, CDU_CLKO13),
	CDU(ADSP_SC598_CLK_CDU_EMMC_TIMER_CMQ, sc598_cdu_emmc_timer_parents,
		CDU_CLKO_SEL2, "cdu_emmc_timer", ADSP_CDU_CLK_FLAGS, CDU_CLKO14),
};

/* Per SoC OF match data */
static const struct adsp_cdu_match_data sc573_cdu_info = {
	.clks		= sc573_mux_clks,
	.num_clks	= ARRAY_SIZE(sc573_mux_clks),
	.reserved_mask	= BIT(6) | BIT(8),
	.has_clkin	= true,
};

static const struct adsp_cdu_match_data sc589_cdu_info = {
	.clks		= sc589_mux_clks,
	.num_clks	= ARRAY_SIZE(sc589_mux_clks),
	.reserved_mask	= 0,
	.has_clkin	= true,
};

static const struct adsp_cdu_match_data sc594_cdu_info = {
	.clks		= sc594_mux_clks,
	.num_clks	= ARRAY_SIZE(sc594_mux_clks),
	.reserved_mask	= BIT(11),
	.has_clkin	= true,
};

static const struct adsp_cdu_match_data sc598_cdu_info = {
	.clks		= sc598_mux_clks,
	.num_clks	= ARRAY_SIZE(sc598_mux_clks),
	.reserved_mask	= BIT(11),
	.has_clkin	= true,
};

struct adsp_cdu {
	u8 cdu_clko;
	spinlock_t lock;
	void __iomem *base;
	struct clk_hw clk_hw;
	const u32 *mux_table;
};

static inline struct adsp_cdu *to_adsp_cdu(struct clk_hw *clk_hw)
{
	return container_of(clk_hw, struct adsp_cdu, clk_hw);
}

static int adsp_cdu_check_unlocked(u32 reg)
{
	/*
	 * We should not modify CDU_CFG[n] when LOCK is set.
	 * If the global SPU lock (GLCK) is also asserted, the
	 * write is blocked, we get a bus error and LWERR is
	 * set. Also we intentionally don't clear LWERR so
	 * it remains available for diagnostics.
	 */
	if (reg & ADSP_CDU_LOCK)
		return -EBUSY;

	return 0;
}

/*
 * CDU_STAT.CLKOn is set while a configuration change for CDU_CFG[n] is in
 * progress. Writes to CDU_CFG[n] must only happen when the corresponding
 * status bit is clear.
 */
static int adsp_cdu_wait_ready(struct adsp_cdu *cdu)
{
	u32 stat;

	return readl_poll_timeout_atomic(cdu->base + ADSP_CDU_STAT,
					 stat,
					 !(stat & BIT(cdu->cdu_clko)),
					 ADSP_CDU_POLL_DELAY,
					 ADSP_CDU_POLL_TIMEOUT);
}

static u32 adsp_cdu_readl(struct adsp_cdu *cdu, unsigned int offset)
{
	return readl(cdu->base + offset);
}

static void adsp_cdu_writel(struct adsp_cdu *cdu,
			    unsigned int offset, u32 val)
{
	writel(val, cdu->base + offset);
}

static unsigned int adsp_cdu_cfg(struct adsp_cdu *cdu)
{
	return ADSP_CDU_CFG(cdu->cdu_clko);
}

static int adsp_cdu_update_en(struct adsp_cdu *cdu, bool enable)
{
	u32 reg;
	int ret;

	reg = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));

	ret = adsp_cdu_check_unlocked(reg);
	if (ret)
		return ret;

	if (enable)
		reg |= ADSP_CDU_CFG_EN;
	else
		reg &= ~ADSP_CDU_CFG_EN;

	adsp_cdu_writel(cdu, adsp_cdu_cfg(cdu), reg);

	return 0;
}

static int adsp_cdu_set_parent(struct clk_hw *clk_hw, u8 index)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	unsigned long flags;
	unsigned int input_sel;
	u32 reg, readback;
	int ret;

	input_sel = clk_mux_index_to_val(cdu->mux_table, 0, index);

	spin_lock_irqsave(&cdu->lock, flags);

	ret = adsp_cdu_wait_ready(cdu);
	if (ret)
		goto out;

	reg = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));

	ret = adsp_cdu_check_unlocked(reg);
	if (ret)
		goto out;

	reg &= ~ADSP_CDU_CFG_SEL;
	reg |= FIELD_PREP(ADSP_CDU_CFG_SEL, input_sel);

	adsp_cdu_writel(cdu, adsp_cdu_cfg(cdu), reg);

	ret = adsp_cdu_wait_ready(cdu);

	/* Verify the mux update before returning success to CCF. */
	readback = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));
	if (FIELD_GET(ADSP_CDU_CFG_SEL, readback) != input_sel)
		ret = -EIO;

out:
	spin_unlock_irqrestore(&cdu->lock, flags);

	return ret;
}

static u8 adsp_cdu_get_parent(struct clk_hw *clk_hw)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	u32 reg, input_sel;
	int parent;

	reg = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));

	input_sel = FIELD_GET(ADSP_CDU_CFG_SEL, reg);

	parent = clk_mux_val_to_index(clk_hw, cdu->mux_table,
				      0, input_sel);
	if (parent < 0)
		return clk_hw_get_num_parents(clk_hw);

	return parent;
}

static int adsp_cdu_enable(struct clk_hw *clk_hw)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	unsigned long flags;
	int ret;

	spin_lock_irqsave(&cdu->lock, flags);

	ret = adsp_cdu_wait_ready(cdu);
	if (ret)
		goto out;

	ret = adsp_cdu_update_en(cdu, true);
	if (ret)
		goto out;

	ret = adsp_cdu_wait_ready(cdu);

out:
	spin_unlock_irqrestore(&cdu->lock, flags);

	return ret;
}

static void adsp_cdu_disable(struct clk_hw *clk_hw)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	unsigned long flags;
	int ret;

	spin_lock_irqsave(&cdu->lock, flags);

	ret = adsp_cdu_wait_ready(cdu);
	if (ret)
		goto out;

	ret = adsp_cdu_update_en(cdu, false);
	if (ret)
		goto out;

	adsp_cdu_wait_ready(cdu);

out:
	spin_unlock_irqrestore(&cdu->lock, flags);
}

static int adsp_cdu_is_enabled(struct clk_hw *clk_hw)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	u32 reg;

	reg = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));

	return !!(reg & ADSP_CDU_CFG_EN);
}

static int adsp_cdu_debug_show(struct seq_file *s, void *v)
{
	struct clk_hw *clk_hw;
	struct adsp_cdu *cdu;
	unsigned long flags;
	u32 cfg_reg, stat_reg;

	clk_hw = s->private;
	cdu = to_adsp_cdu(clk_hw);

	spin_lock_irqsave(&cdu->lock, flags);
	cfg_reg = adsp_cdu_readl(cdu, adsp_cdu_cfg(cdu));
	stat_reg = adsp_cdu_readl(cdu, ADSP_CDU_STAT);
	spin_unlock_irqrestore(&cdu->lock, flags);

	seq_printf(s, "CDU_CFG[%u]: 0x%08x\n", cdu->cdu_clko, cfg_reg);
	seq_printf(s, "  EN:   %u\n", !!(cfg_reg & ADSP_CDU_CFG_EN));
	seq_printf(s, "  SEL:  %lu\n", FIELD_GET(ADSP_CDU_CFG_SEL, cfg_reg));
	seq_printf(s, "  LOCK: %u\n", !!(cfg_reg & ADSP_CDU_LOCK));

	seq_printf(s, "CDU_STAT: 0x%08x\n", stat_reg);
	seq_printf(s, "  LWERR:  %u\n", !!(stat_reg & ADSP_CDU_STAT_LWERR));
	seq_printf(s, "  ADRERR: %u\n", !!(stat_reg & ADSP_CDU_STAT_ADRERR));
	seq_printf(s, "  CLKO%u: %u\n", cdu->cdu_clko,
					!!(stat_reg & BIT(cdu->cdu_clko)));

	return 0;
}
DEFINE_SHOW_ATTRIBUTE(adsp_cdu_debug);

static void adsp_cdu_debug_init(struct clk_hw *clk_hw, struct dentry *dentry)
{
	struct adsp_cdu *cdu = to_adsp_cdu(clk_hw);
	char debugfs_entry_name[12];

	snprintf(debugfs_entry_name, sizeof(debugfs_entry_name),
		 "cdu_cfg[%u]", cdu->cdu_clko);

	debugfs_create_file(debugfs_entry_name, 0444, dentry,
			    clk_hw, &adsp_cdu_debug_fops);
}

static const struct clk_ops adsp_cdu_ops = {
	.determine_rate = clk_hw_determine_rate_no_reparent,
	.set_parent = adsp_cdu_set_parent,
	.get_parent = adsp_cdu_get_parent,
	.enable = adsp_cdu_enable,
	.disable = adsp_cdu_disable,
	.is_enabled = adsp_cdu_is_enabled,
	.debug_init = adsp_cdu_debug_init,
};

struct adsp_cdu_clkin {
	void __iomem *reg;
	struct clk_hw clk_hw;
};

static inline struct adsp_cdu_clkin *to_adsp_cdu_clkin(struct clk_hw *clk_hw)
{
	return container_of(clk_hw, struct adsp_cdu_clkin, clk_hw);
}

static u8 adsp_cdu_clkin_get_parent(struct clk_hw *clk_hw)
{
	struct adsp_cdu_clkin *clkin = to_adsp_cdu_clkin(clk_hw);
	u32 reg;

	reg = readl(clkin->reg);

	return FIELD_GET(ADSP_CDU_CLKINSEL_CGU1, reg);
}

static int adsp_cdu_clkin_set_parent(struct clk_hw *clk_hw, u8 index)
{
	struct adsp_cdu_clkin *clkin = to_adsp_cdu_clkin(clk_hw);
	u32 reg;
	int ret;

	reg = readl(clkin->reg);

	ret = adsp_cdu_check_unlocked(reg);
	if (ret)
		return ret;

	reg &= ~ADSP_CDU_CLKINSEL_CGU1;
	reg |= FIELD_PREP(ADSP_CDU_CLKINSEL_CGU1, index);

	writel(reg, clkin->reg);

	return 0;
}

static const struct clk_ops adsp_cdu_clkin_ops = {
	.determine_rate = clk_hw_determine_rate_no_reparent,
	.set_parent = adsp_cdu_clkin_set_parent,
	.get_parent = adsp_cdu_clkin_get_parent,
};

/**
 * adsp_cdu_clkin_register - Register an ADSP CLKIN mux
 * @dev: device pointer
 * @base: Base address of the CDU register block.
 * @parent_data: Parent data for this clock.
 * @num_parents: Number of parent clocks.
 *
 * Register the CDU_CLKINSEL.CGU1 mux. This selects whether CGU1 receives
 * CLKIN0 or CLKIN1. By default it is set to 0 (CLKIN0).
 *
 * On ADSP-SC598 SoCs, CDU_CLKINSEL.CGU1 selects whether CGU1 and the
 * additional CGU2/third PLL use CLKIN0 or CLKIN1.
 *
 * Return: Clock specific clk_hw data on success, or an ERR_PTR() on failure.
 */
static struct clk_hw *adsp_cdu_clkin_register(struct device *dev, void __iomem *base,
						const struct clk_parent_data *parent_data,
						unsigned int num_parents)
{
	struct adsp_cdu_clkin *clkin;
	struct clk_init_data init = { };
	int ret;

	clkin = devm_kzalloc(dev, sizeof(*clkin), GFP_KERNEL);
	if (!clkin)
		return ERR_PTR(-ENOMEM);

	init.name = "cdu_clkinsel";
	init.ops = &adsp_cdu_clkin_ops;
	init.parent_data = parent_data;
	init.num_parents = num_parents;
	init.flags = 0;

	clkin->reg = base + ADSP_CDU_CLKINSEL;
	clkin->clk_hw.init = &init;

	ret = devm_clk_hw_register(dev, &clkin->clk_hw);
	if (ret)
		return ERR_PTR(ret);

	return &clkin->clk_hw;
}

/**
 * adsp_cdu_register - Register an ADSP SoC CDU output clock mux.
 * @dev: device pointer
 * @clk: CDU clock description
 * @base: Base address of the CDU register block.
 * @reserved_mask: mask of non configurable CDU outputs
 *
 * Register a clock for one CDU mux output. CDU_CFG[n]
 * controls the mux selection and output gating for CDU_CLKOn.
 *
 * The mux preserves the bootloader selected input clocks during rate changes.
 * Reparenting must be requested explicitly.
 *
 * Return: Clock specific clk_hw data on success, or an ERR_PTR() on failure.
 */
static struct clk_hw *adsp_cdu_register(struct device *dev,
					const struct adsp_cdu_clks *clk,
					void __iomem *base,
					unsigned int reserved_mask)
{
	struct adsp_cdu *cdu;
	struct clk_init_data init = { };
	int ret;

	/*
	 * Certain CDU outputs are used internally by
	 * the processor and are not user configurable
	 */
	if (reserved_mask & BIT(clk->cdu_clko))
		return ERR_PTR(-EINVAL);

	cdu = devm_kzalloc(dev, sizeof(*cdu), GFP_KERNEL);
	if (!cdu)
		return ERR_PTR(-ENOMEM);

	init.name = clk->clock_name;
	init.ops = &adsp_cdu_ops;
	init.parent_data = clk->parent_data;
	init.num_parents = clk->num_parents;
	init.flags = clk->clock_flags;

	cdu->clk_hw.init = &init;
	cdu->base = base;
	cdu->mux_table = clk->mux_table;
	cdu->cdu_clko = clk->cdu_clko;
	spin_lock_init(&cdu->lock);

	ret = devm_clk_hw_register(dev, &cdu->clk_hw);
	if (ret)
		return ERR_PTR(ret);

	return &cdu->clk_hw;
}

static int adsp_cdu_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	const struct adsp_cdu_match_data *cdu_match_data;
	struct clk_hw_onecell_data *clk_onecell;
	unsigned int num_provider_clks;
	void __iomem *base;
	struct clk_hw *hw;
	u32 revid, major, rev;
	int ret;

	cdu_match_data = of_device_get_match_data(dev);
	if (!cdu_match_data)
		return -EINVAL;

	base = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(base))
		return PTR_ERR(base);

	revid = readl(base + ADSP_CDU_REVID);
	major = FIELD_GET(ADSP_CDU_REVID_MAJOR, revid);
	rev = FIELD_GET(ADSP_CDU_REVID_REV, revid);

	dev_dbg(dev, "CDU revision: major=%u rev=%u (0x%08x)\n",
		major, rev, revid);

	/* If SoC has CLKIN account for that in clk_onecell */
	num_provider_clks = cdu_match_data->num_clks +
				cdu_match_data->has_clkin;

	clk_onecell = devm_kzalloc(dev, struct_size(clk_onecell,
				   hws, num_provider_clks),
				   GFP_KERNEL);
	if (!clk_onecell)
		return -ENOMEM;

	clk_onecell->num = num_provider_clks;

	if (cdu_match_data->has_clkin) {
		hw = adsp_cdu_clkin_register(dev, base, adsp_clkinsel_parents,
					     ARRAY_SIZE(adsp_clkinsel_parents));
		if (IS_ERR(hw))
			return PTR_ERR(hw);

		clk_onecell->hws[cdu_match_data->num_clks] = hw;
	}

	for (unsigned int i = 0; i < cdu_match_data->num_clks; i++) {
		const struct adsp_cdu_clks *clk = &cdu_match_data->clks[i];

		if (clk->id >= cdu_match_data->num_clks)
			return dev_err_probe(dev, -EINVAL,
					     "%s has invalid clock ID %u\n",
					     clk->clock_name, clk->id);

		hw = adsp_cdu_register(dev, clk, base,
				       cdu_match_data->reserved_mask);
		if (IS_ERR(hw))
			return PTR_ERR(hw);

		clk_onecell->hws[clk->id] = hw;
	}

	ret = devm_of_clk_add_hw_provider(dev, of_clk_hw_onecell_get,
					  clk_onecell);
	if (ret)
		return dev_err_probe(dev, ret,
				     "failed to register clock provider\n");
	return 0;
}

static const struct of_device_id adsp_cdu_of_match[] = {
	{ .compatible = "adi,adsp-sc573-cdu", .data = &sc573_cdu_info },
	{ .compatible = "adi,adsp-sc589-cdu", .data = &sc589_cdu_info },
	{ .compatible = "adi,adsp-sc594-cdu", .data = &sc594_cdu_info },
	{ .compatible = "adi,adsp-sc598-cdu", .data = &sc598_cdu_info },
	{ },
};

static struct platform_driver adsp_cdu_driver = {
	.driver	= {
		.name = "adsp-cdu",
		.of_match_table = adsp_cdu_of_match,
		.suppress_bind_attrs = true,
	},
	.probe = adsp_cdu_probe,
};
module_platform_driver(adsp_cdu_driver);

MODULE_AUTHOR("Qasim Ijaz <qasim.ijaz@analog.com>");
MODULE_DESCRIPTION("Analog Devices ADSP SoC CDU clock driver");
MODULE_LICENSE("GPL");
