# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)

obj-$(CONFIG_COMMON_CLK_ADI_PLL)	+= clk-adi-pll.o
obj-$(CONFIG_COMMON_CLK_ADI_SC598)	+= clk-adi-sc598.o
obj-$(CONFIG_COMMON_CLK_ADI_SC594)	+= clk-adi-sc594.o
obj-$(CONFIG_COMMON_CLK_ADI_SC58X)	+= clk-adi-sc58x.o
obj-$(CONFIG_COMMON_CLK_ADI_SC57X)	+= clk-adi-sc57x.o
