# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause
#
# Makefile for AD9545 Network Clock Generator/Synchronizer
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_COMMON_CLK_AD9545) += clk-ad9545.o
obj-$(CONFIG_COMMON_CLK_AD9545_I2C) += clk-ad9545-i2c.o
obj-$(CONFIG_COMMON_CLK_AD9545_SPI) += clk-ad9545-spi.o
