/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/* SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */

#ifndef DT_BINDINGS_THERMAL_NVIDIA_TEGRA264_BPMP_H
#define DT_BINDINGS_THERMAL_NVIDIA_TEGRA264_BPMP_H

#define TEGRA264_THERMAL_ZONE_TJ_MAX		0
#define TEGRA264_THERMAL_ZONE_TJ_MIN		1
#define TEGRA264_THERMAL_ZONE_GPU_AVG		2
#define TEGRA264_THERMAL_ZONE_CPU_AVG		3
#define TEGRA264_THERMAL_ZONE_SOC_012_AVG	4
#define TEGRA264_THERMAL_ZONE_SOC_45_AVG	5
#define TEGRA264_THERMAL_ZONE_SOC_3_AVG		6
#define TEGRA264_THERMAL_ZONE_GPU_MAX		7
#define TEGRA264_THERMAL_ZONE_CPU_MAX		8
#define TEGRA264_THERMAL_ZONE_SOC_012_MAX	9
#define TEGRA264_THERMAL_ZONE_SOC_345_MAX	10
#define TEGRA264_THERMAL_ZONE_TJ_AVG		11

#endif /* DT_BINDINGS_THERMAL_NVIDIA_TEGRA264_BPMP_H */
