/* SPDX-License-Identifier: BSD-3-Clause-Clear */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef ATH12K_DP_STATS_H
#define ATH12K_DP_STATS_H

enum ath12k_wbm_err_drop_reason {
	WBM_ERR_DROP_GET_SW_DESC,
	WBM_ERR_DROP_DESC_PARSE,
	WBM_ERR_DROP_INV_HW_ID,
	WBM_ERR_DROP_NULL_PRTNR_DP,
	WBM_ERR_DROP_NULL_PROC_DP,
	WBM_ERR_DROP_NULL_PDEV,
	WBM_ERR_DROP_NULL_AR,
	WBM_ERR_DROP_CAC_RUNNING,
	WBM_ERR_DROP_SG,
	WBM_ERR_DROP_INV_NWIFI_HDR,
	WBM_ERR_DROP_REO_GENERIC,
	WBM_ERR_DROP_RXDMA_GENERIC,
	WBM_ERR_DROP_MAX,
};

#endif /* ATH12K_DP_STATS_H */
