dtb-$(CONFIG_ARCH_FSL_IMX8MM) += emcraft-imx8mm-som.dtb \
				 emcraft-imx8m-som-mipi-adv7535.dtb \
				 emcraft-imx8m-som-lcdif-mipi-adv7535.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
