# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)-or-later
obj-$(CONFIG_ADI_SRAM_CONTROLLER)	+= sram.o
obj-$(CONFIG_ADI_SRAM_MMAP_V7)		+= sram_mmap_v7.o
obj-$(CONFIG_ADI_SRAM_MMAP)		+= sram_mmap.o

