imx-dcss-objs := dcss-drv.o dcss-dev.o dcss-blkctl.o dcss-ctxld.o dcss-dtg.o \
				 dcss-ss.o dcss-dpr.o dcss-scaler.o dcss-kms.o dcss-crtc.o \
				 dcss-plane.o dcss-dec400d.o dcss-hdr10.o dcss-wrscl.o \
				 dcss-rdsrc.o dcss-dtrc.o

obj-$(CONFIG_DRM_IMX_DCSS) += imx-dcss.o

