#
# Makefile for IIO linear and angular position sensors
#

# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_ADMT4000_POS) += admt4000.o
obj-$(CONFIG_ADMT4000_ADG714) += adg714.o
obj-$(CONFIG_HID_SENSOR_CUSTOM_INTEL_HINGE) += hid-sensor-custom-intel-hinge.o
obj-$(CONFIG_IQS624_POS)	+= iqs624-pos.o
