name: LLM Agent

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag, PR number, or SHA to checkout
        required: false
        type: string
      run-id:
        description: Explicit workflow run to analyse, optional.
        required: false
        type: string
      prompt:
        description: Prompt to use, overwrites the default.
        required: false
        type: string
        default: ""
      prompt-extra:
        description: Extra prompt to concatenate.
        required: false
        type: string
        default: ""
      prompt-repository:
        description: Repository with LLM skills, overwrites the default.
        required: false
        type: string
        default: ""
      model-small:
        required: false
        type: string
        default: "@vertexai-global/anthropic.claude-haiku-4-5@20251001"
      model-medium:
        required: false
        type: string
        default: "@vertexai-global/anthropic.claude-sonnet-4-5@20250929"
      model-large:
        required: false
        type: string
        default: "@vertexai-global/anthropic.claude-opus-4-5@20251101"

jobs:
  llm:
    uses: analogdevicesinc/linux/.github/workflows/llm.yml@ci
    permissions:
      contents: read
      checks: read
    secrets:
      ANTHROPIC_CUSTOM_HEADERS: ${{ secrets.ANTHROPIC_CUSTOM_HEADERS }}
      ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL }}
      ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
    with:
      ref: ${{ inputs.ref }}
      run-id: ${{ inputs.run-id }}
      prompt: ${{ inputs.prompt }}
      prompt-extra: ${{ inputs.prompt }}
      prompt-repository: ${{ inputs.prompt-repository }}
      model-small: ${{ inputs.model-small }}
      model-medium: ${{ inputs.model-medium }}
      model-large: ${{ inputs.model-large }}

