name: Kernel build

on:
  workflow_dispatch:
  push:
    branches:
      - 'adsp-[0-9]+.[0-9]+*-y'
      - 'adsp-ehp2-[0-9]+.[0-9]+*-y'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  checks:
    uses: analogdevicesinc/linux/.github/workflows/checks.yml@ci
    if: (github.event_name != 'push' || github.repository_owner == 'analogdevicesinc')
    secrets: inherit
    permissions:
      contents: read
  build_gcc_aarch64:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    if: (github.event_name != 'push' || github.repository_owner == 'analogdevicesinc')
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "adi_ci_defconfig"
  build_gcc_arm:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    needs: [checks]
    if: (github.event_name != 'push' || github.repository_owner == 'analogdevicesinc')
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "adi_ci_defconfig"
  assert_checks:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-slim' }}
    permissions:
      contents: read
    needs:
      - checks
      - build_gcc_aarch64
      - build_gcc_arm

    steps:
      - name: Assert
        env:
          job_checks: ${{needs.checks.outputs.summary}}
          job_build_gcc_aarch64: ${{needs.build_gcc_aarch64.outputs.summary}}
          job_build_gcc_arm: ${{needs.build_gcc_arm.outputs.summary}}
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o runner_env.sh \
            https://raw.githubusercontent.com/analogdevicesinc/linux/ci/ci/runner_env.sh
          source ./runner_env.sh
          assert_job_summary

  deploy_cloudsmith_checks:
    needs: [assert_checks]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
        CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: write
      actions: read
    with:
      artifacts: >
        adi_ci_defconfig-*

  build_gcc_arm_sc573-ezlite_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "sc573-ezlite_defconfig"
      auto_from_range: false
  build_gcc_arm_sc589-mini_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "sc589-mini_defconfig"
      auto_from_range: false
  build_gcc_arm_sc594-som-ezkit_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "sc594-som-ezkit_defconfig"
      auto_from_range: false
  build_gcc_arm_sc594-som-ezlite_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "sc594-som-ezlite_defconfig"
      auto_from_range: false
  build_gcc_aarch64_sc598-som-ezkit_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "sc598-som-ezkit_defconfig"
      auto_from_range: false
      checks: true
  build_gcc_aarch64_sc598-som-ezlite_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "sc598-som-ezlite_defconfig"
      auto_from_range: false
  build_gcc_aarch64_sc846-som-ezkit_defconfig:
    needs: [assert_checks]
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "sc846-som-ezkit_defconfig"
      auto_from_range: false
  assert_build:
    runs-on: ${{ vars.RUNNER != '' && fromJSON(vars.RUNNER) || 'ubuntu-slim' }}
    permissions:
      contents: read
    needs:
      - build_gcc_arm_sc573-ezlite_defconfig
      - build_gcc_arm_sc589-mini_defconfig
      - build_gcc_arm_sc594-som-ezkit_defconfig
      - build_gcc_arm_sc594-som-ezlite_defconfig
      - build_gcc_aarch64_sc598-som-ezkit_defconfig
      - build_gcc_aarch64_sc598-som-ezlite_defconfig
      - build_gcc_aarch64_sc846-som-ezkit_defconfig
    steps:
      - name: Assert
        env:
          job_build_gcc_arm_sc573-ezlite_defconfig: ${{needs.build_gcc_arm_sc573-ezlite_defconfig.outputs.summary}}
          job_build_gcc_arm_sc589-mini_defconfig: ${{needs.build_gcc_arm_sc589-mini_defconfig.outputs.summary}}
          job_build_gcc_arm_sc594-som-ezkit_defconfig: ${{needs.build_gcc_arm_sc594-som-ezkit_defconfig.outputs.summary}}
          job_build_gcc_arm_sc594-som-ezlite_defconfig: ${{needs.build_gcc_arm_sc594-som-ezlite_defconfig.outputs.summary}}
          job_build_gcc_aarch64_sc598-som-ezkit_defconfig: ${{needs.build_gcc_aarch64_sc598-som-ezkit_defconfig.outputs.summary}}
          job_build_gcc_aarch64_sc598-som-ezlite_defconfig: ${{needs.build_gcc_aarch64_sc598-som-ezlite_defconfig.outputs.summary}}
          job_build_gcc_aarch64_sc846-som-ezkit_defconfig: ${{needs.build_gcc_aarch64_sc598-som-ezlite_defconfig.outputs.summary}}
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o runner_env.sh \
            https://raw.githubusercontent.com/analogdevicesinc/linux/ci/ci/runner_env.sh
          source ./runner_env.sh
          assert_job_summary

  deploy_cloudsmith_build:
    needs: [assert_build]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
        CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: write
      actions: read
    with:
      artifacts: >
        sc573-ezlite_defconfig-*
        sc589-mini_defconfig-*
        sc594-som-ezkit_defconfig-*
        sc594-som-ezlite_defconfig-*
        sc598-som-ezkit_defconfig-*
        sc598-som-ezlite_defconfig-*
