name: Kernel build

on:
  push:
    branches:
      - 'rpi-*.y'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  build_gcc_arm_adi_bcm2709_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "adi_bcm2709_defconfig"
      auto_from_range: false
  build_gcc_arm_adi_bcm2711_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "adi_bcm2711_defconfig"
      auto_from_range: false
  build_gcc_arm_adi_bcmrpi_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm"
      defconfig: "adi_bcmrpi_defconfig"
      auto_from_range: false
  build_gcc_aarch64_adi_bcm2711_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "adi_bcm2711_defconfig"
      auto_from_range: false
  build_gcc_aarch64_adi_bcm2712_defconfig:
    uses: analogdevicesinc/linux/.github/workflows/build.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      arch: "arm64"
      defconfig: "adi_bcm2712_defconfig"
      auto_from_range: false
  compile_devicetrees:
    uses: analogdevicesinc/linux/.github/workflows/compile-devicetrees.yml@ci
    secrets: inherit
    permissions:
      contents: read
    with:
      compiler: "gcc"
      archs: "arm arm64"
      dts_files: >
        arch/arm/boot/dts/broadcom/bcm*-rpi-*.dts
        arch/arm64/boot/dts/broadcom/bcm*-rpi-*.dts
        arch/arm/boot/dts/overlays/*.dts
        arch/arm64/boot/dts/overlays/*.dts
  assert_build:
    runs-on: [self-hosted, repo-only]
    permissions:
      contents: read
    needs:
      - build_gcc_arm_adi_bcm2709_defconfig
      - build_gcc_arm_adi_bcm2711_defconfig
      - build_gcc_arm_adi_bcmrpi_defconfig
      - build_gcc_aarch64_adi_bcm2711_defconfig
      - build_gcc_aarch64_adi_bcm2712_defconfig
      - compile_devicetrees
    steps:
      - name: Assert
        env:
          job_warn_build_gcc_arm_adi_bcm2709_defconfig: ${{needs.build_gcc_arm_adi_bcm2709_defconfig.outputs.warn}}
          job_warn_build_gcc_arm_adi_bcm2711_defconfig: ${{needs.build_gcc_arm_adi_bcm2711_defconfig.outputs.warn}}
          job_warn_build_gcc_arm_adi_bcmrpi_defconfig: ${{needs.build_gcc_arm_adi_bcmrpi_defconfig.outputs.warn}}
          job_warn_build_gcc_aarch64_adi_bcm2711_defconfig: ${{needs.build_gcc_aarch64_adi_bcm2711_defconfig.outputs.warn}}
          job_warn_build_gcc_aarch64_adi_bcm2712_defconfig: ${{needs.build_gcc_aarch64_adi_bcm2712_defconfig.outputs.warn}}
          job_warn_compile_devicetrees: ${{needs.compile_devicetrees.outputs.warn}}
          job_fail_build_gcc_arm_adi_bcm2709_defconfig: ${{needs.build_gcc_arm_adi_bcm2709_defconfig.outputs.fail}}
          job_fail_build_gcc_arm_adi_bcm2711_defconfig: ${{needs.build_gcc_arm_adi_bcm2711_defconfig.outputs.fail}}
          job_fail_build_gcc_arm_adi_bcmrpi_defconfig: ${{needs.build_gcc_arm_adi_bcmrpi_defconfig.outputs.fail}}
          job_fail_build_gcc_aarch64_adi_bcm2711_defconfig: ${{needs.build_gcc_aarch64_adi_bcm2711_defconfig.outputs.fail}}
          job_fail_build_gcc_aarch64_adi_bcm2712_defconfig: ${{needs.build_gcc_aarch64_adi_bcm2712_defconfig.outputs.fail}}
          job_fail_compile_devicetrees: ${{needs.compile_devicetrees.outputs.fail}}
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o runner_env.sh \
            https://raw.githubusercontent.com/analogdevicesinc/linux/ci/ci/runner_env.sh
          source ./runner_env.sh
          assert_labels
  deploy_cloudsmith_build:
    needs: [assert_build]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'push' }}
    uses: analogdevicesinc/linux/.github/workflows/upload-to-cloudsmith.yml@ci
    secrets:
        CLOUDSMITH_SERVICE_SLUG: ${{ secrets.CLOUDSMITH_SERVICE_SLUG }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    permissions:
      id-token: write
      contents: write
      actions: read
    with:
      artifacts: >
        adi_bcm*_defconfig-*
        dtb-*
