# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)

# todo modularize; already depends on CONFIG_ARCH_SC59X_64 though

obj-$(CONFIG_ARCH_SC59X_64)	+= pads_system.o system.o
obj-$(CONFIG_ARCH_SC59X_64)	+= mach-sc59x/
obj-$(CONFIG_ARCH_SC59X_64)	+= mach-sc5xx/

obj-$(CONFIG_ARCH_SC5XX)	+= pads_system.o system.o
obj-$(CONFIG_ARCH_SC5XX)	+= mach-sc5xx/
