# SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause)

obj-$(CONFIG_ADI_SYSTEM_CONFIG)	+= system.o
obj-$(CONFIG_ADI_PADS_SYSTEM)	+= pads_system.o
obj-$(CONFIG_ARCH_SC59X_64)	+= mach-sc59x/
obj-$(CONFIG_ARCH_SC59X_64)	+= mach-sc5xx/
obj-$(CONFIG_ARCH_SC5XX)	+= mach-sc5xx/
